### ISSUE TITLE
tcpdns not using socks5

### ISSUE THREAD

**Issue by chengen** [semigodking/redsocks#100]
I tested tcpdns last night, It's a pretty brilliant feature. But it's not using the exist socks5 proxy.  Could you please tell me your consideration?   When I connect 8.8.8.8  directly as upstream dns server, it still get poisoned.

**Comment by semigodking** [comment]
you could simply add iptables rules redirect TCP connections to target DNS to your ss-local or redsocks' local listening port.

**Comment by chengen** [comment]
That work, thank you very much!
iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDSOCKS
