### ISSUE TITLE
Support PORT REUSE on linux

### ISSUE THREAD

**Issue by bettermanbao** [semigodking/redsocks#101]
Hello Semigodking,

I'm current using redsocks on my openwrt router. It has a 2 core cpu(mt7621). As I know, redsocks can only utilize 1 core. May I know is it possible to add port reuse support on redsocks? So that I could start 2 redsocks and listen on same port to fully utilize 2 cores on my router. Thanks.

The SO_REUSEPORT socket option
https://lwn.net/Articles/542629/

**Comment by semigodking** [comment]
Interesting, will look into it.

**Comment by bettermanbao** [comment]
Thanks, you may have a look at the code of shadowsocks-libev. It has TFO implemented.

**Comment by semigodking** [comment]
Reuseport is now supported. See 4133bcf5f9ee7dd7687ab55bd36c051d149eb3ea. Please have a try.

**Comment by bettermanbao** [comment]
Perfect, let me have a try. Thanks.
