### ISSUE TITLE
How to disable shadowsocks and keep redirection and DNS feature？

### ISSUE THREAD

**Issue by angusding** [semigodking/redsocks#109]
Only require redsocks2 to use as a redirector to redirect traffice to SOCKS proxy server and keep some dns forward or via proxy feature.  How to remove redundant code for compliing? Just like original redsocks without more bugs.

**Comment by semigodking** [comment]
See #84.
Apply the patch in patches/ to disable support of shadowsocks.

**Comment by angusding** [comment]
Thanks a lot!
