### ISSUE TITLE
建议重新考虑黑名单的添加

### ISSUE THREAD

**Issue by 1294822** [semigodking/redsocks#11]
在faq里提到不支持黑名单是因为可以直接iptables流量到代理，但目前的版本支持了shadowsocks，再开一个ss-local显然是不合适的。因此建议重新考虑黑名单的添加。

**Comment by semigodking** [comment]
不用再开 S's-local啊，在配置文件中多配置一个 redsocks就行了，redsocks是可以配多个的

Semigod King
2015年5月9日 下午9:48于 "1294822" <notifications@github.com>写道：

**Comment by 1294822** [comment]
哦，明白了。谢谢。
