### ISSUE TITLE
Feature request: Precompiled release (distribution packages)

### ISSUE THREAD

**Issue by PantherJohn** [semigodking/redsocks#111]

**Comment by fanmingyi** [comment]
I don't know what platform you need 。
Don't know if this can help you 
https://github.com/fanmingyi/redsocks2Android

**Comment by PantherJohn** [comment]
@fanmingyi The platform is LEDE Openwrt x86_64 and I've already got the problem sorted by **manually compiling the source code (well it's actually from [darkk/redsocks](https://github.com/darkk/redsocks) for whatever reason) along with a bunch of dependencies!** on my budget AMD router. Thanks for your help anyway :)
