### ISSUE TITLE
redsocks2网络兼容性问题

### ISSUE THREAD

**Issue by hero18688** [semigodking/redsocks#12]
我测试了两种网络，1、电信有公网ip的，可以一直正常使用，2、长城宽带，无公网ip，出口ip时常变的。只能在重启路由后能用，一会儿就不能用了，打开要翻的网站都提示dns错误，然而之前，ss+redsocks+dns2socks方案是一直能用的。这问题可能跟issue #8有关联。

**Comment by semigodking** [comment]
这个情况不应该是redsocks的问题，而应该是你的系统配置及ＤＮＳ配置问题。你应该在出现问题时仔细检查iptables的配置情况和dnsmasq等服务的情况。这个和内外网ＩＰ是没有关系的。

**Comment by hero18688** [comment]
不能用时有以下提示
Fri Jul 10 15:57:51 2015 kern.info kernel: [  620.960000] TCP: too many orphaned sockets
Fri Jul 10 15:57:53 2015 kern.info kernel: [  622.560000] TCP: too many orphaned sockets
Fri Jul 10 15:57:55 2015 kern.info kernel: [  624.480000] TCP: too many orphaned sockets
Fri Jul 10 15:57:56 2015 kern.info kernel: [  625.120000] TCP: too many orphaned sockets
Fri Jul 10 15:57:56 2015 kern.info kernel: [  625.120000] TCP: too many orphaned sockets
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52105->144.76.155.228:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52107->144.76.155.228:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52093->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52095->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52096->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52092->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52097->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52077->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52078->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52076->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52081->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52079->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52080->216.58.220.174:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 daemon.err redsocks[2292]: [192.168.2.184:52085->216.58.220.161:443]: shutdown(client, SHUT_RD): Transport endpoint is not connected
Fri Jul 10 15:57:59 2015 kern.info kernel: [  628.960000] TCP: too many orphaned sockets
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52093->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52095->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52096->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52081->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52079->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52077->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52080->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52092->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52078->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52085->216.58.220.161:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52097->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52076->216.58.220.174:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52105->144.76.155.228:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:00 2015 daemon.err redsocks[2292]: [192.168.2.184:52107->144.76.155.228:443]: shutdown(client, SHUT_WR): Transport endpoint is not connected
Fri Jul 10 15:58:08 2015 kern.info kernel: [  637.600000] TCP: too many orphaned sockets
Fri Jul 10 15:58:09 2015 kern.info kernel: [  638.240000] TCP: too many orphaned sockets
