### ISSUE TITLE
License

### ISSUE THREAD

**Issue by corani** [semigodking/redsocks#120]
I noticed you're releasing your changes under Apache-2, by the notice in the C files. Is the whole project supposed to be Apache-2, or are there parts under different licenses?

If the whole project is Apache-2, could you add a LICENSE file to the project to make this clear? That way potential users don't need to hunt through all of the files 😄

**Comment by semigodking** [comment]
License for whole project is Apache2. Good suggestion. Will do it later. A PR is also welcome.
