### ISSUE TITLE
tcpdns怎么用

### ISSUE THREAD

**Issue by FH0** [semigodking/redsocks#122]
```
tcpdns {
	local_ip = 0.0.0.0; 
	local_port = 1053; 
	tcpdns1 = 8.8.4.4;
	tcpdns2 = 8.8.8.8;
	timeout = 4;
}
```

我使用这样的命令来重置dns请求
`iptables -t nat -I OUTPUT -p udp --dport 53 -j REDIRECT --to 1053`

但是得不到服务器的回复，请问这个tcpdns是这样用的吗?

**Comment by semigodking** [comment]
wiki [TCP DNS](https://github.com/semigodking/redsocks/wiki/%E5%B7%A7%E7%94%A8TCPDNS%E5%81%9A%E5%A4%87%E7%94%A8DNS)中有讲，但现在使用效果如何不知道了。

**Comment by FH0** [comment]
> wiki [TCP DNS](https://github.com/semigodking/redsocks/wiki/%E5%B7%A7%E7%94%A8TCPDNS%E5%81%9A%E5%A4%87%E7%94%A8DNS)中有讲，但现在使用效果如何不知道了。

好吧，知道了，它不支持iptables的DNAT，谢谢
