### ISSUE TITLE
twalk的隐式定义问题

### ISSUE THREAD

**Issue by FH0** [semigodking/redsocks#123]
```
redudp.c:655:5: warning: implicit declaration of function 'twalk' is invalid in C99
      [-Wimplicit-function-declaration]
    twalk(root_bound_udp4, bound_udp4_action);
```

上面是静态编译时的一个warning，如果是动态编译，这个warning会变成error，如下:
```
redudp.o:redudp.c:function redudp_audit: error: undefined reference to 'twalk'
```

我查看了系统的/usr/include/search.h，发现里面包含了twalk这个函数，但编译器仍然error，而且静态编译出来的redsocks2在使用tproxy代理udp时没有问题。

想请教一下怎么解决这个error，以成功使用动态编译。

**Comment by FH0** [comment]
我在redudp.c中把这个函数的依赖去掉了，成功编译出来了，也可以正常使用(tproxy)，但还是希望能够解决这个问题

`sed -i "655s|.*|    puts(\"\")\;|" redudp.c`

**Comment by semigodking** [comment]
这个问题不太好统一解决。twalk之类的函数是在glibc 标准库stdlib.h中申明的。但在android中，又没有这些函数。你现在又指出了一个另外的申明。好为难。。。

**Comment by FH0** [comment]
> 这个问题不太好统一解决。twalk之类的函数是在glibc 标准库stdlib.h中申明的。但在android中，又没有这些函数。你现在又指出了一个另外的申明。好为难。。。

并不是安卓的头文件中没有twalk的函数，而且谷歌对于twalk进行了限制，只有api大于21才能使用
```
#if __ANDROID_API__ >= 21
void twalk(const void* __root, void (*__visitor)(const void*, VISIT, int)) __INTRODUCED_IN(21);
#endif
```
只要在编译时临时修改search.h文件就行了，你的wiki里也改一下吧，不需要twalk.c那些文件的，也不需要extra/search.h这个文件

另外，希望tcpdns支持iptables的DNAT，不然在透明代理时还需要一个pdnsd

**Comment by semigodking** [comment]
麻烦你帮忙改下wiki?  Android相关的东西我并不熟悉，免得写错。
到于tcpdns 支持dnat这个，一直没有这个需求。这个如果加了DNAT支持的话，是需要tproxy配合的，同时也不能自动选择最快服务器走了。另外，真实目标也不一定支持tcp dns吧

**Comment by FH0** [comment]
> 麻烦你帮忙改下wiki? Android相关的东西我并不熟悉，免得写错。
> 到于tcpdns 支持dnat这个，一直没有这个需求。这个如果加了DNAT支持的话，是需要tproxy配合的，同时也不能自动选择最快服务器走了。另外，真实目标也不一定支持tcp dns吧

wiki写好了，排版可能有点问题，你看看

另外tcpdns不需要tproxy，像pdnsd在DNAT下也可以正常工作，dns服务器基本上都支持tcp的查询

**Comment by semigodking** [comment]
谢谢！

FH0 <notifications@github.com> 於 2019年6月27日 週四 下午4:41 寫道：
