### ISSUE TITLE
udp转发可以用ss但不能用socks5

### ISSUE THREAD

**Issue by wltc2005** [semigodking/redsocks#125]
版本0.67，redsocks2把流量交给v2ray，v2ray同时开了socks5和ss，且都能转发udp。此时用redsocks的redudp配置udp转发时，像楼主样例里的用ss转发没问题，但是用socks5转发就不行。而用其它软件比如sstap测试，socks5是可以转发udp的。
求解的同时顺路赞一下楼主用爱发电完成redsocks2。

**Comment by semigodking** [comment]
这个我记得是测过可以的。你首先要确保你的socks5 server是支持udp的。你可以用这个小工具检测一下
https://github.com/semigodking/socks5chk

**Comment by wltc2005** [comment]
感谢回复，问题已解决。原因是v2ray转发udp默认本机ip127.0.0.1
