### ISSUE TITLE
IPv6 commits break master

### ISSUE THREAD

**Issue by attila123** [semigodking/redsocks#127]
Hi, the last 2 commits (regarding IPv6 support) on master break redsocks2.
So the last/best working version is b9cafa94664551362fb6a17b2933c1fefc14bf8f
I think it would be worth creating a tag for that.
Also, just an idea, probably you know, use it if you like it: it is a better practice to use feature branches to develop new features and merge to master when the feature is tested and working. Then the latest master is always working.
Summary, please:
- create a tag for b9cafa94664551362fb6a17b2933c1fefc14bf8f
- create an ipv6 dev branch from master, push it
- revert the IPv6 commits in master

**Comment by semigodking** [comment]
Yes. I agree. Guess what, I intentionally push the IPv6 changes to master branch. Because I have no time to test it. I am hoping some one interested in IPv6 feature could try it and report issues identified. If I push it to a dev branch, I am pretty sure no one would care about it.

**Comment by semigodking** [comment]
So far as I know, IPv6 works for most features except UDP forwarding
