### ISSUE TITLE
redirect和tproxy有什么区别？

### ISSUE THREAD

**Issue by AttufliX** [semigodking/redsocks#13]
redsocks始终不去连接shadowsocks

**Comment by semigodking** [comment]
朋友，你什么也不说，就只这么一句，想帮你也不行啊

Semigod King
2015年7月27日 下午2:34于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
奥不好意思刚才有点烦躁哈哈。。

我笔记本上的redsocks2.conf是这样的

base {
    log_debug = off;
    log_info = on;
    log = "file:/tmp/redsocks2.log";
    daemon = on;
    redirector= iptables;
}
redsocks {
  local_ip = 127.0.0.1;
  local_port = 1079;
  ip = 127.0.0.1;
  port = 1082;
  type = socks5;
  timeout = 5;
  autoproxy = 1;
 }
autoproxy {
  quick_connect_timeout = 2;
}
ipcache {
  cache_file = "./ipcache.txt";
  stale_time = 7200;
  autosave_interval = 3600;
  port_check = 1;
}

使用sudo redsocks2 -c redsocks2.conf 运行

然后ss在1082口正常监听，直接访问可以代理。

然后我的iptables规则是这样的：

sudo iptables -t nat -A REDSOCKS -d ss_server_ip -j RETURN
sudo iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN

sudo iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 1079

sudo iptables -t nat -A PREROUTING -p tcp -j REDSOCKS
sudo iptables -t nat -A OUTPUT -p tcp -j REDSOCKS

我理解是，现在流量会被redirect到1079这个端口，然后redsocks会把流量转发给1082，然后实际没有，因为我看服务器那边ss都没有连接的记录。

**Comment by semigodking** [comment]
local_ip不可以使用127.0.0.0/8 的地址，需使用局域网同网段ip

Semigod King
2015年7月27日 下午7:14于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
我 ip addr 查看我的ip是192.168.1.102，我把local ip改成192.168.1.102了，可是还是不行。

**Comment by semigodking** [comment]
你这不是网关？如果不是的话不能用redirect 应使用tproxy

Semigod King
2015年7月27日 下午7:48于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
奥，酱紫，我电脑连接到路由器，所以我电脑不是网关。我看看tproxy。README里好像没有区分这两种情形呀

**Comment by AttufliX** [comment]
我想问下为什么不是网关的话就不能使用redirect??

**Comment by semigodking** [comment]
你的redirect都是加在nat 表里，你的机器不是网关，一般就不会有nat,就不会走nat表。即使是网关也要应用使用局域网接口才能起作用

Semigod King
2015年7月27日 下午9:48于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by semigodking** [comment]
It is not software issue.

**Comment by AttufliX** [comment]
我现在是想在自己的Linux电脑上实现自动翻墙，而不想借助路由器的redirect。我添加用了TProxy规则，但是结果发现它只能用于PREROUTING链，不能用在OUTPUT链上，所以没法把本机的流量转发到redsocks上。折腾了好久都没有头绪，您能不能指点下我应该怎么做呢？

**Comment by semigodking** [comment]
你这种情况可以使用REDIRECTE在OUTPUT chain 完成。
2015年8月21日 下午11:19于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
你看我上面贴的已经有这句话了 sudo iptables -t nat -A OUTPUT -p tcp -j REDSOCKS，可是不起作用呀。是我哪里搞错了么？

**Comment by semigodking** [comment]
没看到你贴什么啊。还要让redsocks2的监听ip为0.0.0.0，在OUTPUT
chain要记得把到redsocks2监听端口的连接先return回去， 到其它目标的才REDIRECT.
2015年8月22日 上午10:08于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
我本来是这样弄的：redsocks监听127.0.0.1:1079
```
sudo iptables -t nat -A REDSOCKS -d ss_server_ip -j RETURN
sudo iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN

sudo iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 1079
sudo iptables -t nat -A OUTPUT -p tcp -j REDSOCKS
```

看了您刚才回复，我是要这么做么？
1. 把redsocks的127.0.0.1改成0.0.0.0
2. 在倒数第二行插入 
```
sudo iptables -t nat -A OUTPUT -p tcp --dport 1079 -j return
```

您是这个意思么？

**Comment by semigodking** [comment]
是的
2015年8月22日 上午10:26于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
谢谢！解决了
