### ISSUE TITLE
Configure redsocks on ddwrt router

### ISSUE THREAD

**Issue by devzone777** [semigodking/redsocks#132]
Hi,

I have redsocks running on my router but don't know how to make iptables send all HTTP/HTTPS traffic to redsocks permanently. I have an external socks5 proxy server to connect to. I've looked all over the internet but the instructions are very unclear how to set iptables. I think the problem is that I have redsocks on the same machine as iptables. Many people say they have done this successfully but their instructions don't work. I think with this version of redsocks, the supporting iptables need to be clarified. All instructions found appear to be old and outdated.

What I would like to know is:
1. How to properly setup redsocks to connect to my external socks5 proxy. (so that it actually works)
2. How to set iptables to route all traffic to redsocks on the "same" machine. (so that it actually works)

This way, any device connected to the LAN or WLAN on my router will have it's traffic routed through redsocks and then from redsocks to my external socks5 proxy (and back of course :-)  )

--------------------------------------------------------------------
My redsocks config file:

```
base {
    log_debug = on;
    log_info = on;
    log = "file:/opt/var/log/redsocks.log";
    daemon = on;
    redirector = iptables;
}

redsocks {
    local_ip = 0.0.0.0;
    local_port = 12345;

    ip = <my_external_socks5_ip_address>;
    port = <my_external_socks5_port>;

    type = socks5;
}
```

-----------------------------------------------------------------------------------

I have also tried 3 sets of iptables which both seem to be not working, they are the below:

iptables set 1 
---------------

```
iptables -I PREROUTING 1 -t mangle -s 192.168.1.1 ! -d `nvram get lan_ipaddr`/`nvram get lan_netmask` -p tcp -m multiport --dports 80,443 -j MARK --set-mark 3
iptables -I PREROUTING 2 -t mangle -s 192.168.1.1 ! -d `nvram get lan_ipaddr`/`nvram get lan_netmask` -p tcp -m multiport --dports 80,443 -j CONNMARK --save-mark
iptables -I PREROUTING 3 -t mangle -s 192.168.1.1 ! -d `nvram get wan_ipaddr` -p tcp -m multiport --dports 80,443 -j MARK --set-mark 3
iptables -I PREROUTING 4 -t mangle -s 192.168.1.1 ! -d `nvram get wan_ipaddr` -p tcp -m multiport --dports 80,443 -j CONNMARK --save-mark

ip rule add fwmark 3 table 13
ip route add default via 192.168.1.1 table 13
```

iptables set 2
---------------

***#create the REDSOCKS target***
iptables -t nat -N REDSOCKS

***#don’t route unroutable addresses***
iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN

***#redirect statement sends everything else to the redsocks proxy input port***
iptables -t nat -A REDSOCKS -p tcp -j REDIRECT –to-ports $REDSOCKS_TCP_PORT

***#if it came in on eth0, and it is tcp, send it to REDSOCKS***
iptables -t nat -A PREROUTING -i $SUBNET_INTERFACE -p tcp -j REDSOCKS

***#Use this one instead of the above if you want to proxy the local
networking in addition to the subnet stuff. Redsocks listens on
all interfaces with local_ip = 0.0.0.0 so no other changes are
necessary.***
iptables -t nat -A PREROUTING -p tcp -j REDSOCKS

***#don’t forget to accept the tcp packets from eth0***
iptables -A INPUT -i $SUBNET_INTERFACE -p tcp –dport $REDSOCKS_TCP_PORT -j ACCEPT

iptables set 3
---------------

iptables -t nat -N TRANSPARENT_PROXY
iptables -t nat -A TRANSPARENT_PROXY -d 0.0.0.0/8 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 10.0.0.0/8 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 100.64.0.0/10 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 127.0.0.0/8 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 169.254.0.0/16 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 172.16.0.0/12 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 192.168.0.0/16 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 198.18.0.0/15 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 224.0.0.0/4 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -d 240.0.0.0/4 -j RETURN
iptables -t nat -A TRANSPARENT_PROXY -p udp --dport 53 -j DNAT --to 127.0.0.1:53
iptables -t nat -A TRANSPARENT_PROXY -p tcp --dport 53 -j DNAT --to 127.0.0.1:53
iptables -t nat -A TRANSPARENT_PROXY -p tcp -j DNAT --to 127.0.0.1:12345
iptables -t nat -A OUTPUT -p tcp -j TRANSPARENT_PROXY
iptables -t nat -A PREROUTING -p tcp -j TRANSPARENT_PROXY

-----------------------------------------------------------------------------------------

Where am I going wrong with iptables? Any help would be greatly appreciated :)

**Comment by devzone777** [comment]
I've made some progress. Now i have what looks like the correct iptables config but the connection randomly accepts or  I get error: out of file descriptors too many open files.

Log:
```
1572450041.589315 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41458-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.590504 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41459-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.591563 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41460-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.592629 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41461-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.593720 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41462-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.594798 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41463-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.595882 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41464-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.596928 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41465-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.597995 redsocks.c:703 redsocks_accept_client(...) [10.0.0.122:41466-><<socks5_ip>>:<<socks5_port>>]: accepted
1572450041.599062 redsocks.c:638 redsocks_accept_client(...) accept: out of file descriptors, backing off for 65 ms: Too many open files
1572450041.669993 redsocks.c:638 redsocks_accept_client(...) accept: out of file descriptors, backing off for 104 ms: Too many open files
1572450041.779914 redsocks.c:638 redsocks_accept_client(...) accept: out of file descriptors, backing off for 347 ms: Too many open files
1572450042.130050 redsocks.c:638 redsocks_accept_client(...) accept: out of file descriptors, backing off for 25 ms: Too many open files
```

**Comment by devzone777** [comment]
> 
> 
> First of all, remove all UDP rules:
> 
> ```
> iptables -t nat -A TRANSPARENT_PROXY -p udp --dport 53 -j DNAT --to 127.0.0.1:53
> iptables -t nat -A TRANSPARENT_PROXY -p tcp --dport 53 -j DNAT --to 127.0.0.1:53
> ```
> 
> and
> 
> `iptables -t nat -A OUTPUT -p tcp -j TRANSPARENT_PROXY`
> 
> then test on other device but not on router self.

@rampageX Thanks,  I removed those rules. Using another device on the LAN, I get no response in the redsocks.log.  If I disable redsocks and remove the iptables entries I can browse just fine from a machine on the LAN. It looks like a rule needs to be added to allow traffic from the LAN to go out on the WAN. But I'm not sure how to do that and make it work with redsocks.

**Comment by devzone777** [comment]
@rampageX Once again thanks for your help! I was able to get it working with your advice and it runs out that I had to put the LAN gateway instead of the loopback address in the following rule:

iptables -t nat -A TRANSPARENT_PROXY -p tcp -j DNAT --to 127.0.0.1:12345
changed to
iptables -t nat -A TRANSPARENT_PROXY -p tcp -j DNAT --to 192.168.1.1:12345

**Comment by devzone777** [comment]
Next I must figure out how to route DNS through the socks5

**Comment by semigodking** [comment]
there are examples in Wiki.
https://github.com/semigodking/redsocks/wiki/UDP透明代理配置示例

devzone777 <notifications@github.com> 于 2019年10月31日周四 12:53写道：
