### ISSUE TITLE
RedUDP error failing to extract original destination address via Tproxy

### ISSUE THREAD

**Issue by johnwigley** [semigodking/redsocks#136]
I'm having a problem where redUDP is failing to extract the original address on UDP packets.

Error message per UDP packet is:

1574372848.796038 warning utils.c:98 red_recv_udp_pkt(...) unexepcted cmsg (level,type) = (0,20)
1574372848.796075 warning utils.c:102 red_recv_udp_pkt(...) (SOL_IP, IP_ORIGDSTADDR) not found

Looking in the code in utils.c around 98 you can see it's trying to get the original destination address, but what does the error unexpected cmsg (0,20) mean?

What's the best way to debug this?

Thanks

Config file is standard:

base {
 log_debug = on;
 log_info = on;
 daemon = off;
 redirector= generic;
}

redudp {
	bind = "0.0.0.0:12345";
	relay = "172.20.0.1:1080";
	type = socks5;
	//dest = "8.8.8.8:53";
	//udp_timeout = 3;
}

redsocks {
 bind = "0.0.0.0:12345";
 relay = "172.20.0.1:1080";
 type = socks5; // I use socks5 proxy for GFW'ed IP
 autoproxy = 0; // I want autoproxy feature enabled on this section.
 // timeout is meaningful when 'autoproxy' is non-zero.
 // It specified timeout value when trying to connect to destination
 // directly. Default is 10 seconds. When it is set to 0, default
 // timeout value will be used.
 // NOTE: decreasing the timeout value may lead increase of chance for
 // normal IP to be misjudged.
 timeout = 1;
}

**Comment by semigodking** [comment]
Thanks for reporting. The issue should be fixed in 3a46f2fd6094e4811eb6054567a0aabdc35605d7

**Comment by johnwigley** [comment]
Thanks for that quick fix, about to test and will feedback.

**Comment by johnwigley** [comment]
Confirmed fixed, although unfortunately now another error - opened a new issue for it.
Thank you very much.
