### ISSUE TITLE
redUDP error - Received packet from unexpected IP address

### ISSUE THREAD

**Issue by johnwigley** [semigodking/redsocks#137]
When redUDP is forwarding via Socks5 proxy (V2ray) it is failing with error:
 
notice socks5-udp.c:178 socks5_pkt_from_socks(...) [192.168.1.10:57836->192.168.1.1:53]: Got packet from unexpected address 172.20.0.1:1080.

The problem is that it is then dropping the response packet from the Socks5 proxy, I have commented out the section at socks5-udp.c:178, and then it does appear to work and process the response packet, however not successfully and then seems to be misreading the length of the response.

What doesn't seem to make sense is that you can see in the log that it is talking to the socks5 proxy on 172.20.0.1:1080 and intends to talk to it because before the error it logs:

 debug socks5-udp.c:383 socks5_relay_connected(...) [192.168.1.10:57836->192.168.1.1:53]: via 172.20.0.1:1080

So then when it receives a response back from 172.20.0.1:1080 it is strange that it then logs:
   
notice socks5-udp.c:178 socks5_pkt_from_socks(...) [192.168.1.10:57836->192.168.1.1:53]: Got packet from unexpected address 172.20.0.1:1080.

Despite the fact that it is coming back from the correct ip:port on the socks5 proxy that it initiated the connection to?

I think there is in fact MORE THAN ONE error going on here, as when I comment out the check at socks5-udp.c:178 then it appears to process successfully but misreads the response size to sends back incorrect UDP data to the client connecting to Redsocks2. I will try and also identify what exactly is happening there.

Thanks for your help as always!

Full log:

root@OpenMPTCProuter:~# ip netns exec netns1 /root/redsocks2 -c /root/redsocks2.conf

1574449328.363687 info redudp.c:596 redudp_init_instance(...) redudp @ 0.0.0.0:12345: TPROXY
1574449328.363711 notice main.c:255 main(...) redsocks started with: epoll
1574449355.739794 debug redudp.c:383 redudp_first_pkt_from_client(...) [192.168.1.10:57836->192.168.1.1:53]: got 1st packet from client
1574449355.739952 debug socks5-udp.c:383 socks5_relay_connected(...) [192.168.1.10:57836->192.168.1.1:53]: via 172.20.0.1:1080
1574449355.740457 debug socks5-udp.c:338 socks5_read_auth_methods(...) [192.168.1.10:57836->192.168.1.1:53]: <trace>
1574449355.740618 debug socks5-udp.c:227 socks5_read_assoc_reply(...) [192.168.1.10:57836->192.168.1.1:53]: <trace>
1574449355.740639 debug redudp.c:336 redudp_flush_queue(...) [192.168.1.10:57836->192.168.1.1:53]: Starting UDP relay
1574449355.751659 notice socks5-udp.c:178 socks5_pkt_from_socks(...) [192.168.1.10:57836->192.168.1.1:53]: Got packet from unexpected address 172.20.0.1:1080.
1574449357.746211 debug redudp.c:383 redudp_first_pkt_from_client(...) [192.168.1.10:57837->192.168.1.1:53]: got 1st packet from client
1574449357.746485 debug socks5-udp.c:383 socks5_relay_connected(...) [192.168.1.10:57837->192.168.1.1:53]: via 172.20.0.1:1080
1574449357.746724 debug socks5-udp.c:338 socks5_read_auth_methods(...) [192.168.1.10:57837->192.168.1.1:53]: <trace>
1574449357.747132 debug socks5-udp.c:227 socks5_read_assoc_reply(...) [192.168.1.10:57837->192.168.1.1:53]: <trace>
1574449357.747196 debug redudp.c:336 redudp_flush_queue(...) [192.168.1.10:57837->192.168.1.1:53]: Starting UDP relay
1574449357.807675 notice socks5-udp.c:178 socks5_pkt_from_socks(...) [192.168.1.10:57837->192.168.1.1:53]: Got packet from unexpected address 172.20.0.1:1080.
1574449359.748127 debug redudp.c:383 redudp_first_pkt_from_client(...) [192.168.1.10:57838->192.168.1.1:53]: got 1st packet from client
1574449359.748432 debug socks5-udp.c:383 socks5_relay_connected(...) [192.168.1.10:57838->192.168.1.1:53]: via 172.20.0.1:1080
1574449359.748664 debug socks5-udp.c:338 socks5_read_auth_methods(...) [192.168.1.10:57838->192.168.1.1:53]: <trace>
1574449359.749436 debug socks5-udp.c:227 socks5_read_assoc_reply(...) [192.168.1.10:57838->192.168.1.1:53]: <trace>
1574449359.749510 debug redudp.c:336 redudp_flush_queue(...) [192.168.1.10:57838->192.168.1.1:53]: Starting UDP relay
1574449359.760563 notice socks5-udp.c:178 socks5_pkt_from_socks(...) [192.168.1.10:57838->192.168.1.1:53]: Got packet from unexpected address 172.20.0.1:1080.
1574449385.748524 debug redudp.c:350 redudp_timeout(...) [192.168.1.10:57836->192.168.1.1:53]: Client timeout. First: 1574449355, last_client: 1574449355, last_relay: 0.
1574449385.748563 debug redudp.c:239 redudp_drop_client(...) [192.168.1.10:57836->192.168.1.1:53]: Dropping client @ state: 0
1574449387.748317 debug redudp.c:350 redudp_timeout(...) [192.168.1.10:57837->192.168.1.1:53]: Client timeout. First: 1574449357, last_client: 1574449357, last_relay: 0.
1574449387.748354 debug redudp.c:239 redudp_drop_client(...) [192.168.1.10:57837->192.168.1.1:53]: Dropping client @ state: 0
1574449389.758278 debug redudp.c:350 redudp_timeout(...) [192.168.1.10:57838->192.168.1.1:53]: Client timeout. First: 1574449359, last_client: 1574449359, last_relay: 0.
1574449389.758315 debug redudp.c:239 redudp_drop_client(...) [192.168.1.10:57838->192.168.1.1:53]: Dropping client @ state: 0

**Comment by semigodking** [comment]
The bug should be fixed. However, socks5 udp is known to not working with IPv6.

**Comment by johnwigley** [comment]
Confirmed that the issue is resolved. Thank you!

**Comment by laseryuan** [comment]
I still got this issue. I tried following commits:
a11c058d9fc9d757e27bf9d683dba1e9919311af
ebbd1d0c04e47bc52706aeac3febcab0b6b35424
4cc0fefadb20ebac7f3da24a7c3a161167a9b3ae

The socks5 port seems to be fine.
```
$python udpchk.py -p 127.0.0.1 -P 1080
UDP check passed
```

```
1585834323.168124 debug redudp.c:383 redudp_first_pkt_from_client(...) [192.168.1.109:41268->8.8.8.8:53]: got 1st packet from client
1585834323.168390 debug socks5-udp.c:389 socks5_relay_connected(...) [192.168.1.109:41268->8.8.8.8:53]: via 127.0.0.1:1080
1585834323.170033 debug socks5-udp.c:344 socks5_read_auth_methods(...) [192.168.1.109:41268->8.8.8.8:53]: <trace>
1585834323.170853 debug socks5-udp.c:233 socks5_read_assoc_reply(...) [192.168.1.109:41268->8.8.8.8:53]: <trace>
1585834323.170931 debug redudp.c:336 redudp_flush_queue(...) [192.168.1.109:41268->8.8.8.8:53]: Starting UDP relay
1585834323.250411 notice socks5-udp.c:184 socks5_pkt_from_socks(...) [192.168.1.109:41268->8.8.8.8:53]: Got packet from unexpected address 127.0.0.1:1080.
1585834327.222405 debug redsocks.c:934 redsocks_audit_instance(...) Audit client list for instance (socks5 @ 0.0.0.0:60080):
1585834327.222435 debug redsocks.c:956 redsocks_audit_instance(...) End of auditing client list.
1585834342.778594 debug redsocks.c:522 redsocks_event_error(...) [192.168.1.109:52338->13.75.46.153:443]: relay, what: READING|0|EOF|0|0|0|0x0: Success
1585834342.778650 debug redsocks.c:321 process_shutdown_on_write_(...) [192.168.1.109:52338->13.75.46.153:443]: WCB client, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
1585834342.778961 debug redsocks.c:522 redsocks_event_error(...) [192.168.1.109:52338->13.75.46.153:443]: client, what: READING|0|EOF|0|0|0|0x0: Success
1585834342.779012 debug redsocks.c:321 process_shutdown_on_write_(...) [192.168.1.109:52338->13.75.46.153:443]: WCB relay, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
1585834342.779090 debug redsocks.c:495 redsocks_shutdown(...) [192.168.1.109:52338->13.75.46.153:443]: both client and server disconnected
1585834342.779100 debug redsocks.c:421 redsocks_drop_client(...) [192.168.1.109:52338->13.75.46.153:443]: dropping client @ state: 5
1585834343.170779 debug redudp.c:350 redudp_timeout(...) [192.168.1.109:41268->8.8.8.8:53]: Client timeout. First: 1585834313, last_client: 1585834313, last_relay: 0.
1585834343.170876 debug redudp.c:239 redudp_drop_client(...) [192.168.1.109:41268->8.8.8.8:53]: Dropping client @ state: 0
1585834348.170598 debug redudp.c:350 redudp_timeout(...) [192.168.1.109:41268->8.8.8.8:53]: Client timeout. First: 1585834318, last_client: 1585834318, last_relay: 0.
1585834348.170662 debug redudp.c:239 redudp_drop_client(...) [192.168.1.109:41268->8.8.8.8:53]: Dropping client @ state: 0
```

**Comment by semigodking** [comment]
udp replay is not well verified in recent commits. may need to debug when i
have time.
