### ISSUE TITLE
quick_connect_timeout   的值无法设置成0

### ISSUE THREAD

**Issue by rickly** [semigodking/redsocks#14]
if (!config->quick_connect_timeout)
        err = "Timeout value for quick check can not be 0. Default: 3";

quick_connect_timeout = 0; // 别检查了，如果认为被屏蔽了就直接走代理吧
无法启动

**Comment by AttufliX** [comment]
我这里也报错了，我设置成1了

**Comment by semigodking** [comment]
这是个bug,我会随后修复，谢谢

Semigod King
2015年7月27日 下午9:46于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by semigodking** [comment]
sorry,　经过确认，这不是一个代码BUG，而是文档写错了。这里应该是将~no_quick_check_seconds~设置为０　。我会修改文档。
