### ISSUE TITLE
[feature request] 可否实现一个fake IP的功能？

### ISSUE THREAD

**Issue by forever8938** [semigodking/redsocks#142]
就是内置一个DNS服务器，只支持A和AAAA就行，对每个域名返回一个唯一的fake IP，并保存域名和IP的映射。透明代理转socks5的时候，再把IP换成域名。这样就不用查询真实IP了。

我不会编程，只是把原版redsocks的dnstc改了改，勉强能用。原版有很多毛病，如果您这边能添加这个功能就好了，非常简单。

**Comment by semigodking** [comment]
哈哈哈哈！这是一个非常有趣的思路。如果我有空了可以考虑一下实现。

forever8938 <notifications@github.com> 于 2020年3月2日周一 16:15写道：

**Comment by fbion** [comment]
https://github.com/xjasonlyu/tun2socks
https://github.com/FlowerWrong/tun2socks

**Comment by forever8938** [comment]
> https://github.com/xjasonlyu/tun2socks
> https://github.com/FlowerWrong/tun2socks

无一例外都是go语言写的，性能堪忧。而c语言做这个事情几乎没有性能损失。
