### ISSUE TITLE
MacOS 10.11无法编译

### ISSUE THREAD

**Issue by fsjack** [semigodking/redsocks#15]
make 显示 .depend:1: *** missing separator.  Stop.
是gcc问题？MacOSX的gcc是基于LLVM的，可能因为这个的原因？

**Comment by semigodking** [comment]
我没有mac环境，无法测试。

Semigod King
2015年8月3日 下午12:12于 "Jackie" <notifications@github.com>写道：

**Comment by fsjack** [comment]
谢谢您回复~
想请教另外一个问题是内置的TCP DNS解析是不是可以取代掉ChinaDNS的作用呢？

**Comment by semigodking** [comment]
不建议用tcp dns的方式来解决这个问题。 如果你使用shadowsocks代理的话，建议你使用redudp的方式来解决。

Semigod King
2015年8月4日 下午2:30于 "Jackie" <notifications@github.com>写道：

**Comment by leenchan** [comment]
@semigodking 
请教一个问题 关于转发DNS
udp转发，redudp{} 里面一定要设置 dest ip 和 dest port 吗？如果是中转dns，是直接把这一节的local port作为上游dns服务器？例如 127.0.0.1#1053，还需要iptables吗？
如果能不设置 dest，是否可以 把指定到dest ip 的 udp 通过 iptables 转发到这节的 local port

**Comment by semigodking** [comment]
用Tproxy就不设置，否则需要设置。如指定了dest,刚可直接做为上游dns 服务器，否则不行。

Semigod King
2015年8月9日 下午8:58于 "leenchan" <notifications@github.com>写道：

**Comment by Eveink** [comment]
用ChinaDNS更好，redudp转发解析由于好多WEB服务是有CDN的返回结果是国外节点。

**Comment by soffchen** [comment]
推荐用 redudp + dnsmasq + dnsmasq-china-list

**Comment by realgtk** [comment]
Mac OSX 下编译失败，查询下来是Makefile文件中"for I in $(wildcard *.h); do"那一段下面的tab过多引起的，删除1个就可以了。
解决步骤：
1、复制dl目录下的redsocks2-0.65-02a53ce90413c73895fd3d126319478540c46571.tar.bz2到其他目录并解压
2、修改Makefile文件，删除多余的tab
3、删除原包重新打包：tar cjvf redsocks2-0.65-02a53ce90413c73895fd3d126319478540c46571.tar.bz2 redsocks2-0.65 重新覆盖到dl目录下
4、make package/redsock2/compile 
如果要一劳永逸的话还是请semigodking修改下Makefile

**Comment by semigodking** [comment]
我无环境，没法测，请改好它测好后发 push request，我来merge。谢谢
2015年11月20日 下午2:17，"realgtk" <notifications@github.com>写道：

**Comment by realgtk** [comment]
OSX下无法编译的问题，经过重新测试过后，发现不是tab的原因，而是Makefile里：echo -n >$(DEPS);这段生成.depend的问题。
在OSX下生成的.depend文件是如下内容：
-n
-n parser.o: 
parser.c log.h parser.h utils.h
正常的应该是：
parser.o: parser.c log.h parser.h utils.h

安装coreutils，修改Makefile把echo改成gecho就可以编译。
很诡异的问题，OSX下“echo -n >.depend”命令行下是正常的，但是在脚本里执行却把-n认为是字符，继续查找原因中...

**Comment by rampageX** [comment]
不是所有编译环境默认 SHELL 都一样的，特别是 bash 并不是每个系统都自带的，sh 比较通用；改成 SHELL = /bin/bash 后 tomatoware 就无法编译了，因为 /bin/ 下根本没 bash。 OSX 这个编译 BUG 和 DD-WRT 下有点类似，只要自己设置 SHELL 环境变量即可，程序 Makefile 无需更改我觉得。

硬要改我觉得就是首先优先读取系统环境变量 SHELL 值，没有默认就是 /bin/sh，如果是 OSX 就设为 /bin/bash。

**Comment by semigodking** [comment]
好，那我把这个改回去
2016年3月21日 下午2:48，"rampageX" <notifications@github.com>写道：
