### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by chenrui333** [semigodking/redsocks#150]
I am trying to help keep redsocks up to date, unfortunately, the original fork is not well maintained. 

So I wonder if you can make a new release and I can switch to use your latest release (so that the users can use the up to date software).

Thanks!

---

relates to Homebrew/homebrew-core#8267
also relates to https://github.com/darkk/redsocks/issues/96

**Comment by chenrui333** [comment]
Currently, I am still having build issue with the latest master:

```
==> make
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/redsocks/01.make:
./encrypt.h:92:18: error: field has incomplete type 'cipher_evp_t' (aka 'struct evp_cipher_ctx_st')
    cipher_evp_t evp;
                 ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
encrypt.c:919:17: error: variable has incomplete type 'cipher_kt_t' (aka 'struct evp_cipher_st')
    cipher_kt_t cipher_info;
                ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:89:16: note: forward declaration of 'struct evp_cipher_st'
typedef struct evp_cipher_st EVP_CIPHER;
               ^
2 errors generated.
make: *** [encrypt.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by semigodking** [comment]
Do you really need shadowsocks support? if not, you can disable it and
compile.

chenrui <notifications@github.com> 于 2020年7月5日周日 13:24写道：

**Comment by chenrui333** [comment]
yeah, I can give it a shot.
