### ISSUE TITLE
在android上运行redsocks时，使用shadowsocks方式读取配置文件出错。

### ISSUE THREAD

**Issue by taosiming** [semigodking/redsocks#153]
按照wiki上的文档，编译在android下的运行文件，在android上运行redsocks时，使用shadowsocks方式读取配置文件出错。换其他的方式（direct，socks5），没有问题，或者相同配置文件在linux下也没有问题。
配置如下：
base {
log_debug = on;
log_info = on;
log = stderr;
daemon = off;
redirector = iptables;
}

redsocks {
bind = "0.0.0.0:12345";
type = shadowsocks;
relay = "x.x.x.x.:xx";
timeout = 120;
autoproxy = 0;
login = "aes-256-cfb";
password = "cfb";
}

**Comment by taosiming** [comment]
> 按照wiki上的文档，编译在android下的运行文件，在android上运行redsocks时，使用shadowsocks方式读取配置文件出错。换其他的方式（direct，socks5），没有问题，或者相同配置文件在linux下也没有问题。
> 配置如下：
> base {
> log_debug = on;
> log_info = on;
> log = stderr;
> daemon = off;
> redirector = iptables;
> }
> 
> redsocks {
> bind = "0.0.0.0:12345";
> type = shadowsocks;
> relay = "x.x.x.x.:xx";
> timeout = 120;
> autoproxy = 0;
> login = "aes-256-cfb";
> password = "cfb";
> }

CC=arm-linux-androideabi-gcc CFLAGS=-I/root/android-arm/include LDFLAGS=-L/root/android-arm/lib make ENABLE_STATIC=true DISABLE_SHADOWSOCKS=true
已解决

**Comment by taosiming** [comment]
我在编译的时候去掉disable shadowsocks，编译出错
./encrypt.h:92:18: error: field has incomplete type 'cipher_evp_t' (aka 'struct evp_cipher_ctx_st')
    cipher_evp_t evp;
                 ^
/root/android-arm/include/openssl/ossl_typ.h:90:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
encrypt.c:919:17: error: variable has incomplete type 'cipher_kt_t' (aka 'struct evp_cipher_st')
    cipher_kt_t cipher_info;
                ^
/root/android-arm/include/openssl/ossl_typ.h:89:16: note: forward declaration of 'struct evp_cipher_st'
typedef struct evp_cipher_st EVP_CIPHER;
               ^
2 errors generated.
<builtin>: recipe for target 'encrypt.o' failed

**Comment by semigodking** [comment]
没有足够的错误信息呀。

taosiming <notifications@github.com> 于 2020年7月31日周五 17:35写道：
