### ISSUE TITLE
Do not create a redsocks/redsocks file after execution make

### ISSUE THREAD

**Issue by SasanFouladi** [semigodking/redsocks#157]
I use openssl 1.1.1+ and run
make DISABLE_SHADOWSOCKS=true

But  dont create a redsocks/redsocks file for set config
redsocks/redsocks -c redsocks/redsocks.conf

How can I solve the problem?

**Comment by semigodking** [comment]
I guess you mean the redsocks exits immediately. This is usually caused by
bad config file. Please double check your config file.

SasanFouladi <notifications@github.com> 于 2021年1月4日周一 17:53写道：

**Comment by SasanFouladi** [comment]
I think I could not express my meaning correctly
According to the https://github.com/darkk/redsocks  repository, which creates the redsocks executable file after make, and then it can be used to change the configuration, etc.
But here the redsocks executable file is not created after make command and the following error is received.

redsocks/redsocks -c  redsocks/redsocks.conf
-bash: redsocks/redsocks: No such file or directory

**Comment by SasanFouladi** [comment]
i solved this problem
The following command had to be executed

redsocks/redsocks2 -c redsocks/redsocks.conf

after run make, create redsocks2 executable file
