### ISSUE TITLE
autoproxy不起作用，国内网站也自动走代理

### ISSUE THREAD

**Issue by AttufliX** [semigodking/redsocks#16]
我设置了antoproxy=1可是仍然不起作用，不是说能自动区分墙内和墙外流量么？还是我得有ipset辅助？

**Comment by semigodking** [comment]
请仔细阅读wiki上的使用说明。 由于你没有提供任何详细信息我没办法帮到你。

Semigod King
2015年8月3日 下午10:23于 "Lu Chenxiang" <notifications@github.com>写道：

**Comment by AttufliX** [comment]
不好意思，错怪redsocks了。openwrt上的shadowsocks-libev-spec添加了全局转发到ss本地端口的iptables规则，所以有问题。其实shadowsocks-libev-spec和官方的shadowsocks-libev+redsocks2。
