### ISSUE TITLE
无法关闭日志？

### ISSUE THREAD

**Issue by zhfreal** [semigodking/redsocks#17]
根据最新版编译，conf中设置：
log_debug = off;
log_info = off;
这种设置应该能关闭绝大部分日志吧？但实际上还是打出了一大堆详细日志，太多（路由上面运行，而且重定向所有TCP和UDP包），根本不敢写入日志文件。临时只有将其输出重定向到 /dev/null。这个是bug？还是理解错误，配置错误？

1438847131.333197 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:50608->165.254.42.72:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 287, tin: 287
1438847131.333429 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:50608->165.254.42.72:80]: WCB relay, fs: 0, ts: 0, fin: 287, fout: 0, tin: 0
1438847131.333479 autoproxy.c:276 handle_write_to_relay(...) [192.168.2.101:50608->165.254.42.72:80]: sent: 287, recv: 0, in:287, out:0
1438847131.530038 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:50608->165.254.42.72:80]: relay in: 232
1438847131.530138 autoproxy.c:187 on_connection_confirmed(...) [192.168.2.101:50608->165.254.42.72:80]: IP Confirmed
1438847131.530371 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:50608->165.254.42.72:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438847137.634997 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438847137.635574 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1238->192.168.2.5:12345]: got 1st packet from client
1438847137.635676 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1238->192.168.2.5:12345]: via 192.168.2.5:1080
1438847137.636691 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438847137.637444 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438847137.637574 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1238->192.168.2.5:12345]: Starting UDP relay
1438847137.637784 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1238->192.168.2.5:12345]: socks5_relay_error
1438847137.637830 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1238->192.168.2.5:12345]: Dropping...
1438847143.539098 main.c:188 main(...) redsocks goes down
1438847143.539361 redsocks.c:1013 redsocks_fini_instance(...) There are connected clients during shutdown! Disconnecting them.
1438847143.539443 redsocks.c:388 redsocks_drop_client(...) [192.168.2.101:50608->165.254.42.72:80]: dropping client

**Comment by semigodking** [comment]
这个应该是没有bug的，请仔细检查你的配置。我用下面的设置都只有很少log.

    base {
     log_debug = off;
     log_info = on;
     daemon = on;
     redirector= iptables;
    }

**Comment by zhfreal** [comment]
就这几行配置。
base {
    log_debug = off;
    log_info = off;
    log = stderr;
    daemon = off;
    redirector = iptables;
}
然后：
1438849149.904643 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1238->192.168.2.5:12345]: via 192.168.2.5:1080
1438849149.905747 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849149.906782 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849149.907282 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1238->192.168.2.5:12345]: Starting UDP relay
1438849149.908510 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1238->192.168.2.5:12345]: socks5_relay_error
1438849149.908973 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1238->192.168.2.5:12345]: Dropping...
1438849151.568652 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51128->218.110.22.8:443]: relay in: 510
1438849151.569595 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51128->218.110.22.8:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849151.571118 autoproxy.c:615 auto_event_error(...) [192.168.2.101:51128->218.110.22.8:443]: client, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438849151.571625 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51128->218.110.22.8:443]: WCB relay, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
1438849151.574243 redsocks.c:795 redsocks_accept_client(...) [192.168.2.101:51129->218.110.22.8:443]: accepted
1438849151.665601 autoproxy.c:615 auto_event_error(...) [192.168.2.101:51128->218.110.22.8:443]: relay, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438849151.666180 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51128->218.110.22.8:443]: WCB client, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
1438849151.666719 redsocks.c:459 redsocks_shutdown(...) [192.168.2.101:51128->218.110.22.8:443]: both client and server disconnected
1438849151.667093 redsocks.c:388 redsocks_drop_client(...) [192.168.2.101:51128->218.110.22.8:443]: dropping client
1438849151.669070 redsocks.c:376 redsocks_start_relay(...) [192.168.2.101:51129->218.110.22.8:443]: data relaying started
1438849151.669507 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51129->218.110.22.8:443]: WCB relay, fs: 0, ts: 0, fin: 235, fout: 0, tin: 0
1438849151.669879 autoproxy.c:276 handle_write_to_relay(...) [192.168.2.101:51129->218.110.22.8:443]: sent: 0, recv: 0, in:235, out:0
1438849151.670282 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51129->218.110.22.8:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 235, tin: 235
1438849151.670931 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51129->218.110.22.8:443]: WCB relay, fs: 0, ts: 0, fin: 235, fout: 0, tin: 0
1438849151.671324 autoproxy.c:276 handle_write_to_relay(...) [192.168.2.101:51129->218.110.22.8:443]: sent: 235, recv: 0, in:235, out:0
1438849151.777509 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51129->218.110.22.8:443]: relay in: 883
1438849151.777977 autoproxy.c:187 on_connection_confirmed(...) [192.168.2.101:51129->218.110.22.8:443]: IP Confirmed
1438849151.778561 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51129->218.110.22.8:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849151.780448 autoproxy.c:375 direct_relay_clientreadcb(...) [192.168.2.101:51129->218.110.22.8:443]: client in: 310
1438849151.781050 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51129->218.110.22.8:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849152.371824 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849152.373349 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1195->192.168.2.5:12345]: got 1st packet from client
1438849152.373906 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1195->192.168.2.5:12345]: via 192.168.2.5:1080
1438849152.375017 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849152.375939 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849152.376570 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1195->192.168.2.5:12345]: Starting UDP relay
1438849152.377862 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1195->192.168.2.5:12345]: socks5_relay_error
1438849152.378327 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1195->192.168.2.5:12345]: Dropping...
1438849152.800266 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51129->218.110.22.8:443]: relay in: 43
1438849152.801007 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51129->218.110.22.8:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849152.803467 autoproxy.c:375 direct_relay_clientreadcb(...) [192.168.2.101:51129->218.110.22.8:443]: client in: 2513
1438849152.804219 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51129->218.110.22.8:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849153.631586 autoproxy.c:375 direct_relay_clientreadcb(...) [192.168.2.101:51087->119.81.145.163:443]: client in: 1189
1438849153.632385 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51087->119.81.145.163:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849153.666636 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51087->119.81.145.163:443]: relay in: 325
1438849153.667324 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51087->119.81.145.163:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849154.294777 autoproxy.c:375 direct_relay_clientreadcb(...) [192.168.2.101:51087->119.81.145.163:443]: client in: 1221
1438849154.295544 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51087->119.81.145.163:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849154.330401 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51087->119.81.145.163:443]: relay in: 325
1438849154.331015 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51087->119.81.145.163:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849162.900126 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51129->218.110.22.8:443]: relay in: 507
1438849162.901044 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51129->218.110.22.8:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849162.902611 autoproxy.c:615 auto_event_error(...) [192.168.2.101:51129->218.110.22.8:443]: client, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438849162.903231 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51129->218.110.22.8:443]: WCB relay, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
1438849162.995471 autoproxy.c:615 auto_event_error(...) [192.168.2.101:51129->218.110.22.8:443]: relay, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438849162.996006 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51129->218.110.22.8:443]: WCB client, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
1438849162.996526 redsocks.c:459 redsocks_shutdown(...) [192.168.2.101:51129->218.110.22.8:443]: both client and server disconnected
1438849162.996907 redsocks.c:388 redsocks_drop_client(...) [192.168.2.101:51129->218.110.22.8:443]: dropping client
1438849163.611325 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849163.612496 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:12708->192.168.2.5:12345]: got 1st packet from client
1438849163.613221 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:12708->192.168.2.5:12345]: via 192.168.2.5:1080
1438849163.614301 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:12708->192.168.2.5:12345]: <trace>
1438849163.615342 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:12708->192.168.2.5:12345]: <trace>
1438849163.615848 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:12708->192.168.2.5:12345]: Starting UDP relay
1438849163.616997 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:12708->192.168.2.5:12345]: socks5_relay_error
1438849163.617591 redudp.c:196 redudp_drop_client(...) [192.168.2.101:12708->192.168.2.5:12345]: Dropping...
1438849170.969894 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.101:51108->192.30.252.88:443]: relay in: 31
1438849170.970798 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.101:51108->192.30.252.88:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849170.972451 autoproxy.c:375 direct_relay_clientreadcb(...) [192.168.2.101:51108->192.30.252.88:443]: client in: 35
1438849170.973241 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.101:51108->192.30.252.88:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438849174.593362 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849174.594837 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1195->192.168.2.5:12345]: got 1st packet from client
1438849174.595401 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1195->192.168.2.5:12345]: via 192.168.2.5:1080
1438849174.596546 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849174.597463 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849174.598090 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1195->192.168.2.5:12345]: Starting UDP relay
1438849174.599339 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1195->192.168.2.5:12345]: socks5_relay_error
1438849174.599804 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1195->192.168.2.5:12345]: Dropping...
1438849177.062331 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849177.063659 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1238->192.168.2.5:12345]: got 1st packet from client
1438849177.063820 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1238->192.168.2.5:12345]: via 192.168.2.5:1080
1438849177.064625 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849177.065314 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849177.065492 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1238->192.168.2.5:12345]: Starting UDP relay
1438849177.065799 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1238->192.168.2.5:12345]: socks5_relay_error
1438849177.065873 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1238->192.168.2.5:12345]: Dropping...
1438849178.297076 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849178.298566 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1195->192.168.2.5:12345]: got 1st packet from client
1438849178.299131 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438849178.300275 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1238->192.168.2.5:12345]: got 1st packet from client
1438849178.300795 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1195->192.168.2.5:12345]: via 192.168.2.5:1080
1438849178.301405 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1238->192.168.2.5:12345]: via 192.168.2.5:1080
1438849178.302281 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849178.303849 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849178.304382 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1195->192.168.2.5:12345]: <trace>
1438849178.304990 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1195->192.168.2.5:12345]: Starting UDP relay
1438849178.306653 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1195->192.168.2.5:12345]: socks5_relay_error
1438849178.307118 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1195->192.168.2.5:12345]: Dropping...
1438849178.307810 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438849178.308298 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1238->192.168.2.5:12345]: Starting UDP relay
1438849178.309623 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1238->192.168.2.5:12345]: socks5_relay_error
1438849178.310086 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1238->192.168.2.5:12345]: Dropping.

**Comment by zhfreal** [comment]
上面这些属什么日志 debug, info ？ 还是本来就不受控制要打出的

**Comment by semigodking** [comment]
属于DEBUG. 你试下去掉log = stderr;

**Comment by zhfreal** [comment]
还是不行，去掉 log = stderr

base {
    log_debug = off;
    log_info = off;
    // log = stderr;
    daemon = off;
    redirector = iptables;
}
还是打出一大堆：
1438851178.149283 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.150146 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.150753 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.151111 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1712
1438851178.151405 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.152529 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.152728 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1452
1438851178.153394 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.154475 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.154675 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1712
1438851178.154980 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.156064 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.156565 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1452
1438851178.157322 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.157685 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.158519 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.158814 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.206407 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.206619 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1712
1438851178.207550 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.207758 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.208098 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.209226 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.210150 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.210357 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.211629 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.211983 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.212174 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1712
1438851178.212484 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.213433 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.214213 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.214656 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.214931 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1452
1438851178.216056 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.216497 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.217039 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 3164
1438851178.217334 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.217939 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1452
1438851178.218399 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.263563 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 2904
1438851178.263825 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1452
1438851178.264174 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.265461 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 4096
1438851178.265686 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 1712
1438851178.266383 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851178.267158 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:60302->222.73.28.97:80]: relay in: 3316
1438851178.267534 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:60302->222.73.28.97:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851179.633607 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.112:58349->54.149.120.93:443]: relay in: 37
1438851179.634085 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.112:58349->54.149.120.93:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851181.154028 redsocks.c:795 redsocks_accept_client(...) [192.168.2.110:60009->115.231.102.164:80]: accepted
1438851181.194624 redsocks.c:376 redsocks_start_relay(...) [192.168.2.110:60009->115.231.102.164:80]: data relaying started
1438851181.194737 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.110:60009->115.231.102.164:80]: WCB relay, fs: 0, ts: 0, fin: 374, fout: 0, tin: 0
1438851181.194808 autoproxy.c:276 handle_write_to_relay(...) [192.168.2.110:60009->115.231.102.164:80]: sent: 0, recv: 0, in:374, out:0
1438851181.194925 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.110:60009->115.231.102.164:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 374, tin: 374
1438851181.195197 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.110:60009->115.231.102.164:80]: WCB relay, fs: 0, ts: 0, fin: 374, fout: 0, tin: 0
1438851181.195271 autoproxy.c:276 handle_write_to_relay(...) [192.168.2.110:60009->115.231.102.164:80]: sent: 374, recv: 0, in:374, out:0
1438851181.236320 autoproxy.c:388 direct_relay_relayreadcb(...) [192.168.2.110:60009->115.231.102.164:80]: relay in: 177
1438851181.236429 autoproxy.c:187 on_connection_confirmed(...) [192.168.2.110:60009->115.231.102.164:80]: IP Confirmed
1438851181.236721 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.110:60009->115.231.102.164:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1438851181.254290 autoproxy.c:615 auto_event_error(...) [192.168.2.110:60009->115.231.102.164:80]: client, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438851181.254463 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.2.110:60009->115.231.102.164:80]: WCB relay, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
1438851181.294548 autoproxy.c:615 auto_event_error(...) [192.168.2.110:60009->115.231.102.164:80]: relay, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
1438851181.295092 redsocks.c:287 process_shutdown_on_write_(...) [192.168.2.110:60009->115.231.102.164:80]: WCB client, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
1438851181.295883 redsocks.c:459 redsocks_shutdown(...) [192.168.2.110:60009->115.231.102.164:80]: both client and server disconnected
1438851181.296281 redsocks.c:388 redsocks_drop_client(...) [192.168.2.110:60009->115.231.102.164:80]: dropping client
1438851181.880612 utils.c:68 red_recv_udp_pkt(...) IP_ORIGDSTADDR: 192.168.2.5:12345
1438851181.881843 redudp.c:335 redudp_first_pkt_from_client(...) [192.168.2.101:1238->192.168.2.5:12345]: got 1st packet from client
1438851181.882399 socks5-udp.c:355 socks5_relay_connected(...) [192.168.2.101:1238->192.168.2.5:12345]: via 192.168.2.5:1080
1438851181.883673 socks5-udp.c:310 socks5_read_auth_methods(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438851181.884806 socks5-udp.c:205 socks5_read_assoc_reply(...) [192.168.2.101:1238->192.168.2.5:12345]: <trace>
1438851181.885315 redudp.c:284 redudp_flush_queue(...) [192.168.2.101:1238->192.168.2.5:12345]: Starting UDP relay
1438851181.886518 socks5-udp.c:381 socks5_relay_error(...) [192.168.2.101:1238->192.168.2.5:12345]: socks5_relay_error
1438851181.887093 redudp.c:196 redudp_drop_client(...) [192.168.2.101:1238->192.168.2.5:12345]: Dropping...

**Comment by semigodking** [comment]
看了一下代码，你需要在去掉log = stderr;这一行的同时，把daemon改成daemon = on; 或者，你可以直接指定log =
syslog:daemon;

**Comment by zhfreal** [comment]
好吧。log输出到syslog是可以不打debug日志的。但在终端或者自定义日志文件中，无法关闭debug。log_info和log_debug有点像摆设。个人认为log_info和log_debug之类的选项应该是控制log内容输出。而log=xxx和daemon选项应该是控制log输出路径。目前这个有点混乱。日志这模块还是之前redsocks的么？如果有可能，还是改一下吧。

不管怎样，多谢。

**Comment by semigodking** [comment]
我也觉得该改下。

Semigod King
2015年8月6日 下午9:29于 "zhfreal" <notifications@github.com>写道：

**Comment by semigodking** [comment]
The behavior of logging is corrected.
