### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by srvh** [semigodking/redsocks#170]
Hello.

When I run "make" command, then I get error:

cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o parser.o parser.c
In file included from parser.c:29:0:
utils.h:7:26: fatal error: event2/event.h: No such file or catalog

I have installed:
libevent 2.0.21
libevent-devel 2.0.21
gcc

CentOS 7 system.

What is wrong?

**Comment by semigodking** [comment]
Usually, this is due to include path is not properly set.  Export CFLAGS
with correct  path to libevent2 headers and library helps.

Denis ***@***.***> 于 2022年1月10日周一 01:43写道：
