### ISSUE TITLE
关于新chacha20实现

### ISSUE THREAD

**Issue by wongsyrone** [semigodking/redsocks#18]
发现在目前的开发版libsodium中实现了一个[IETF兼容的chacha20poly1305](https://github.com/jedisct1/libsodium/commit/bf920dc717f5ac48b7baf3512afe98fc9d71af08)，不知菊苣有什么看法，这个和之前的有什么区别吗

**Comment by semigodking** [comment]
请查看wiki中的faq。 这个功能是不打算去支持的，没有实际意义，而且还会增加额外库的依赖。

Semigod King
2015年8月11日 下午8:45于 "Syrone Wong" <notifications@github.com>写道：

**Comment by wongsyrone** [comment]
在ARM平台下因为缺少AES指令集，还是有点用的

**Comment by semigodking** [comment]
那点速度的提升可能根本比不了内存复制所带来的性能下降，还要增加依赖库，不值得啊。

Semigod King
2015年8月11日 下午10:24于 "Syrone Wong" <notifications@github.com>写道：

**Comment by wongsyrone** [comment]
ARM下的许多内存都DDR3了，MIPS的话确实比较坑

**Comment by semigodking** [comment]
还有很多性能一般的路由器啊！

Semigod King
2015年8月11日 下午10:28于 "Syrone Wong" <notifications@github.com>写道：

**Comment by wongsyrone** [comment]
可以做成开关提供的说，想编译的就自己加 -D，感觉给出选择会比较好

**Comment by semigodking** [comment]
这也是一种解决方法。

Semigod King
2015年8月11日 下午10:33于 "Syrone Wong" <notifications@github.com>写道：
