### ISSUE TITLE
建议加入负载均衡及后端可用性检查支持

### ISSUE THREAD

**Issue by Nexpro** [semigodking/redsocks#19]
目前后端多台ss-server希望加入负载均衡及后端可用性检查功能

如果没有这方面计划, 那么通过第三方的软件有没有什么好的解决方案?

**Comment by semigodking** [comment]
可用性检查可以用curl来做。 负载均衡，目前唯一能做的就是多个进程分别代理不同业务。

Semigod King
2015年8月12日 下午7:05于 "Nexpro" <notifications@github.com>写道：

**Comment by 70599** [comment]
可以给一个用curl检查可用性的实例吗？

**Comment by semigodking** [comment]
curl --socks5 93.118.77.235:8800 https://www.google.com

但对于 shadowsocks, 你可能要用其它方法
2015年8月15日 下午7:25于 "70599" <notifications@github.com>写道：

**Comment by babylon882004** [comment]
70599 curl可用性检测可以看我的https://github.com/babylon882004/sstest里面的叫examip Bash脚本，脚本中lkblk函数就是用curl来检测可用性的！

**Comment by babylon882004** [comment]
另外负载均衡可以试试haproxy

**Comment by semigodking** [comment]
一般家用而已，要求不高，不要太折腾，要是商用才需考虑。
2016年2月26日 下午10:26，"Cheng Bill Wong" <notifications@github.com>写道：

**Comment by babylon882004** [comment]
现在的墙很智能化，我们这里能通过流量特征来阻断内容数据包，通过shadowsocks代理curl -I加域名测试能返回正确的http头，curl加域名获取域名对应网站的http内容的数据包就被拦截了，用浏览器访问的结果就是显示空白页，太缺德了！

**Comment by semigodking** [comment]
那只能换移动了
2016年2月26日 下午10:57，"Cheng Bill Wong" <notifications@github.com>写道：
