### ISSUE TITLE
使用TPROXY，udp穿透失败

### ISSUE THREAD

**Issue by zglqaq** [semigodking/redsocks#195]
1705915385.219948 warning redudp.c:298 redudp_fwd_pkt_to_sender(...) [172.16.168.53:59739->114.114.114.114:53]: bound_udp_get failure
1705915387.149023 err redudp.c:151 bound_udp_get(...) bind: Address already in use
1705915387.149063 warning redudp.c:298 redudp_fwd_pkt_to_sender(...) [172.16.168.53:59740->114.114.114.114:53]: bound_udp_get failure
1705915389.161856 err redudp.c:151 bound_udp_get(...) bind: Address already in use
1705915389.161887 warning redudp.c:298 redudp_fwd_pkt_to_sender(...) [172.16.168.53:59741->114.114.114.114:53]: bound_udp_get failure
1705915391.165874 err redudp.c:151 bound_udp_get(...) bind: Address already in use
1705915391.165900 warning redudp.c:298 redudp_fwd_pkt_to_sender(...) [172.16.168.53:59742->114.114.114.114:53]: bound_udp_get failure
1705915393.181151 err redudp.c:151 bound_udp_get(...) bind: Address already in use
1705915393.181186 warning redudp.c:298 redudp_fwd_pkt_to_sender(...) [172.16.168.53:59743->114.114.114.114:53]: bound_udp_get failure

**Comment by zglqaq** [comment]
redudp {
	bind = "0.0.0.0:10053";
	relay = "x.x.x.x:1080";
	//login = username;// field 'login' is reused as encryption
	                 // method of shadowsocks
	//password = pazzw0rd;

	// know types: socks5, shadowsocks
	type = socks5;

	// redsocks knows about two options while redirecting UDP packets at
	// linux: TPROXY and REDIRECT.  TPROXY requires more complex routing
	// configuration and fresh kernel (>= 2.6.37 according to squid
	// developers[1]) but has hack-free way to get original destination
	// address, REDIRECT is easier to configure, but requires `dest`
	// to be set, limiting packet redirection to single destination.
	// [1] http://wiki.squid-cache.org/Features/Tproxy4
	//dest = "8.8.8.8:53";

	udp_timeout = 30;
	// udp_timeout_stream = 180;
}

**Comment by semigodking** [comment]
感谢反馈和调试。最近比较忙，没时间修复。如果你能查出原因并修复最好。提供线索我抽时间看看。

**Comment by semigodking** [comment]
刚才快速偷空看了几眼。问题可能出在socks5-udp.c的208和215行。这里没做ntoh转换！

**Comment by semigodking** [comment]
花了点时间调查了一下。你这个问题我没办法确认。你看到的端口错误其实是因为你打印的时候没有做ntohs。#194 的问题没解决之前，兼容性是个问题。

**Comment by zglqaq** [comment]
的确是打印错误，但是我已经找到了原因。当udp穿透的目标端口是53时，如果允许redsocks的主机上已经运行了dns服务就会出现bound_udp_get(...) bind: Address already in use。同样的我上面提到的目标端口是5010的错误也是因为本机udp5010端口已经被占用了。当我把5010端口所在的服务监听的地址从绑定所有地址0.0.0.0:5010改成其中一个地址172.16.0.8:5010后错误就消失了。虽然错误解决了，但是我不理解为什么redsocks转发udp数据时要在本机上绑定目标端口，这是TPROXY机制吗？

**Comment by semigodking** [comment]
要绑定的是目标地址，以便以目标地址向客户端发响应数据。
