### ISSUE TITLE
UDP socks client

### ISSUE THREAD

**Issue by madhanraj** [semigodking/redsocks#20]
I am trying to redirect the udp packet to particular port where I run
my proxy (SOCKS) . I am supposed to obtain the original destination
ipaddress of the client to add to the data field of socks message as
per the RFC .

However , when I use REDIRECT chain as it sets the dest addr to the LO
address i get the LO address 127.0.0.1 and the port where socks proxy
client runs .

I tried patching SO_ORIGINAL_DST to obtain for UDP protocol also . In
this case it would work if I use single FD for single dest . However
when I use single FD for multiple connection it might not work .

I cannot add as part of rsvmsg , as I have to send to the proxy server
in advance .

TPROXY works in prerouting , I am not sure how we use in the client
side to send the first packet with the dest address . (I am not sure
about the TPROXYing though)

Can you please suggest the method to overcome the problem . Thanks in advance.

**Comment by semigodking** [comment]
For UDP, unless you specify destination ip:port in config section for
redudp, you must use tproxy to redirect. REDIRECT does not work with UDP!

Semigod King
2015年8月13日 上午12:15于 "madhanraj" <notifications@github.com>写道：

**Comment by madhanraj** [comment]
Can you please mention exactly what should be added in the tproxy in the redsocks client ? 
As I know , we do the TPROXY in the prerouting and hence it wont matter for the first packet sent out of the client . It would be for intermediate routers or bridges .  Correct me if I am wrong , I am new to TPROXY concept

**Comment by semigodking** [comment]
To use tproxy with UDP in redsocks, your config section for REDUDP is like
this:

redudp {
>
  local_ip = 192.168.0.1;
>
  local_port = 1053;
>
  ip = your.socks5-server.com;
>
  port = 1080;
>
  type = socks5;
>
  login = username;
>
  password = "password";
>
   udp_timeout = 3;
>
}


>
For iptables and rules to use TPROXY, see here
https://www.kernel.org/doc/Documentation/networking/tproxy.txt

**Comment by qwIvan** [comment]
Can I add a TPROXY rule in OUTPUT chain?

**Comment by semigodking** [comment]
No. Tproxy rules can only be added into PREROUTING chain.
2015年9月15日 下午2:17，"qwIvan" <notifications@github.com>写道：
