### ISSUE TITLE
DST.ADDR and DST.PORT of UDP Associate Request is wrong, thus incompatible with Dante

### ISSUE THREAD

**Issue by ge9** [semigodking/redsocks#210]
A recent commit c8e1e6c4c1d623b2e540528ac9efd06dde952006 contains a [change](https://github.com/semigodking/redsocks/commit/c8e1e6c4c1d623b2e540528ac9efd06dde952006#diff-c5eec5d34c1236a88e49266049e94d26dbce900422408ddb21217b85c8396ad5R54), which uses the destination address/port of the UDP associate as DST.ADDR and DST.PORT fields, instead of previous all-zero data.

However, actually, DST.ADDR and DST.PORT fields of UDP Associate Request should be **the source address/port that the client plans to use to send packets from**, not the remote destination port. 

The explanation in RFC1928 is somewhat confusing and similar issue happened in https://github.com/ginuerzh/gost/issues/96.

Not all SOCKS5 servers seem to care about these fields (e.g. 3proxy doesn't), but Dante does.

Thus, we have to use all-zero here like before (or the exact source port to be used).

**Comment by semigodking** [comment]
Yes, you are right. Will address it when I have time. PR is always welcomed!
