### ISSUE TITLE
redsocks2内存占用过高

### ISSUE THREAD

**Issue by huxim** [semigodking/redsocks#24]
运行一个白天剩余内存就只有3M了,然后redsocks2自己就很容易挂掉.
貌似是有内存泄漏
使用的是
https://github.com/aa65535/openwrt-redsocks2
编译版

**Comment by semigodking** [comment]
请使用我的repo上的版本，我的连续运行几个月都没问题。其它repo中的代码我不熟，没办法判断问题。
2015年10月5日 下午6:41，"huxim" <notifications@github.com>写道：

**Comment by huxim** [comment]
有编译好的ipk么?

**Comment by semigodking** [comment]
没有
2015年10月5日 下午8:07，"huxim" <notifications@github.com>写道：
