### ISSUE TITLE
编译出现错误！

### ISSUE THREAD

**Issue by houzi-** [semigodking/redsocks#25]
您好！我用BRCM53XX的SDK出现一下的错误，用toolchain-arm编译也是一样！

arm-openwrt-linux-gcc -I/home/houzi/OpenWrt-SDK-15.05-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/include/ -L/home/houzi/OpenWrt-SDK-15.05-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64/staging_dir/toolchain-arm_cortex-a9_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib/ -fPIC -O3 -std=gnu99 -Wall -DUSE_CRYPTO_OPENSSL   -c -o parser.o parser.c
In file included from parser.c:29:0:
utils.h:6:19: fatal error: event.h: No such file or directory
 #include <event.h>
                   ^
compilation terminated
make: *** [parser.o] 错误 1

**Comment by semigodking** [comment]
请先编译 libevent2 ，参照 wiki 说明
2015年10月6日 下午4:35，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 谢谢您的指导！已经在Tomato-arm编译成功！
tomato-arm的编译参数:
首先得先编译openssl和libevent2
```shell
export PATH=$PATH:/opt/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin
export STAGING_DIR=/opt/arm-xiaomi-linux-uclibcgnueabi
export CFLAGS="-I/opt/arm-xiaomi-linux-uclibcgnueabi/include -L/opt/arm-xiaomi-linux-uclibcgnueabi/usr/lib/"
make CC=arm-xiaomi-linux-uclibcgnueabi-gcc LD=arm-xiaomi-linux-uclibcgnueabi-ld
```

**Comment by houzi-** [comment]
@semigodking 您好！为什么判断如此慢！还有ipcache.txt并没有生成！还有开启要等待差不多1分钟左右才出视频！
这是我的配置文件:
```shell
base {
  log_debug = off; 
  log_info = on;
  daemon = on;
  redirector= iptables;
}

redsocks {
 local_ip = 192.168.1.1;
 local_port = 1088;
 ip = xxx.xxxx.xxx.xxxx;
 port = xxxxx;
 type = shadowsocks;
 timeout = 12;
 autoproxy = 1;
 login = "rc4-md5";
 password = "xxxxxx";
}

autoproxy {
 no_quick_check_seconds = 0;
 quick_connect_timeout = 2;
}

ipcache {

 cache_size = 4;
 cache_file = "/opt/var/log/ipcache.txt";
 stale_time = 900;
 autosave_interval = 3600;
 port_check = 1;
}
```

**Comment by semigodking** [comment]
把timeout = 12改小点，比如４。 根据你的配置，那个文件要一个小时才生成。
2015年10月6日 下午8:05，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 我是用chinadns防污染的！不知道redsocks2是否能通过TCP查询防污染！

**Comment by semigodking** [comment]
请看 wiki 中tcpdns 及 redudp相关章节
2015年10月6日 下午8:18，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 那文件一小时生成，会对DNS缓存有所改善吧？

**Comment by semigodking** [comment]
有
2015年10月6日 下午8:33，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 多谢您的共享和多谢您的解答！使用一段时间看看！
