### ISSUE TITLE
如何实现利用tcpdns解决DNS污染？

### ISSUE THREAD

**Issue by houzi-** [semigodking/redsocks#26]
您好！如果使用tcpdns查询来解决污染，那iptables应该如何设置，能否给个例子！还有能否设置208.67.222.222:443 的非标准端口？

**Comment by semigodking** [comment]
可以，且不需要iptables的设置，除非你打算用tproxy 。另外建议使用redudp 来解决
2015年10月6日 下午10:42，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 
您好！有点不明白！
我是这样设置的，就不用转发到透明代理端口？就不用设置其他的？
```
tcpdns {
  local_ip = 192.168.1.1;
  local_port = 1053;
  tcpdns1 = 8.8.4.4; 
  tcpdns2 = 8.8.8.8; 
  timeout = 3;         
}
```

**Comment by semigodking** [comment]
如果要转透明代理，请在 Nat 表 OUTPUT chain 重定向到透明代理
2015年10月7日 下午8:50，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
@semigodking 我还是不明白tcpdns 如何防污染！而我不是想转透明代理如果把ChinaDNS撤掉，是被污染的，还有账号不支持UDP转发！所以用不到reudp!

**Comment by semigodking** [comment]
不想转透明代理就是不用动 iptables
2015年10月7日 下午9:37，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
效果无法跟chinadns相比！有时候会被污染！或者reudp才是最佳吧！还有如果我想wget Google一类的被墙URL,是不是把nat上的OUTPUT转发到透明代理上！但是我这样测试了表示是无效的！我应该怎么设置iptables

**Comment by semigodking** [comment]
终于可以在电脑上回复了。
是的，tcpdns的响应速度肯定慢于UDP的。至于效果，那看你怎么用。
如果你想不通过代理，直接将ＤＮＳ请求转发到上游dns服务器，那不用配iptables，只需要在dnsmasq里指定用这个端口做dns服务器就行了。
如果你希望你的TCP DNS请求通过代理走的话，你就需要再加一条iptables rule到OUTPUT chain里，将到TCP 8.8.8.8:53的流量转发到你redsocks2开放的透明代理的端口（这个端口不建议打开autoproxy功能）上去。

**Comment by houzi-** [comment]
好的！redsocks2在我的tomato-arm上运行的很好，就是设置延时短些可能会出现误判的情况！
还有其实我的想法是想让路由器自身走代理，因为这样可以让opkg起到代理加速的作用，并且还可以加速拖一些国外的源码，如果十一国内正常的速度去wget一些源码通常会很慢，但走代理就不一样了！
```
iptables -t nat -A OUTPUT -p tcp -m multiport --dports 80,443 -j REDSOCKS2
```
```
iptables -t nat -A OUTPUT -p tcp -m multiport --dports 80,443 -j REDIRECT --to-ports 1088
```
设置这两个也是无效的！

**Comment by semigodking** [comment]
对于你这种应用，会比较麻烦，要求redsocks2在 0.0.0.0上做监听，而在OUTPUT chain里，要将SS的ＩＰ首先排除，然后再做redirect。

**Comment by houzi-** [comment]
@semigodking SS的IP已经RETURN了？具体如何实施呢？

**Comment by houzi-** [comment]
@semigodking 0.0.0.0监听？

**Comment by semigodking** [comment]
即local_ip设置为0.0.0.0

**Comment by houzi-** [comment]
还是无法搞定！监听设置成0.0.0.0会导致翻不了墙！
```
redsocks {
  local_ip = 0.0.0.0;
  local_port = 1088;
  ip = xxx.xxx.xxx.43;
  port = xxxxx;
  type = shadowsocks;
  timeout = 4;
  autoproxy = 1;
  login = "rc4-md5";
  password = "xxxxxxx";
}
```
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain redir ports 5353
WANPREROUTING  all  --  anywhere             wan-ip
REDSOCKS2  tcp  --  anywhere             anywhere

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
RETURN     all  --  anywhere             xxx.xxx.xxx.43.vultr.com
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:www redir ports 1088
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 1088

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere
SNAT       all  --  192.168.1.0/24       192.168.1.0/24       to:192.168.1.1

Chain REDSOCKS2 (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             xxx.xxx.xxx.43.vultr.com
RETURN     all  --  anywhere             anywhere             match-set ss_spec_wan_ac dst
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:www redir ports 1088
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 1088
```

**Comment by semigodking** [comment]
Output 不要共用原翻墙用redsocks 2监听端口， 在redsocks2 中另外配多一个
2015年10月8日 下午7:00，"houzi-" <notifications@github.com>写道：

**Comment by houzi-** [comment]
还是换回chnroutes方案了！有点麻烦！还是未果！谢谢作者的解答！

**Comment by semigodking** [comment]
具体来说，你需要做的是这样的
redsocks {
  local_ip = 192.168.1.1;
  local_port = 1088;
  ip = xxx.xxx.xxx.43;
  port = xxxxx;
  type = shadowsocks;
  timeout = 4;
  autoproxy = 1;
  login = "rc4-md5";
  password = "xxxxxxx";
}
redsocks {
  local_ip = 0.0.0.0;
  local_port = 1089;
  ip = xxx.xxx.xxx.43;
  port = xxxxx;
  type = shadowsocks;
  autoproxy = 0;  // number zero
  login = "rc4-md5";
  password = "xxxxxxx";
}

tcpdns {
  local_ip = 192.168.1.1;
  local_port = 1053;
  tcpdns1 = 8.8.4.4; 
  tcpdns2 = 8.8.8.8; 
  timeout = 3;         
}

配置ＤＮＳＭＡＳＱ，让ＤＮＳＭＡＳＱ发送ＤＮＳ请求到 192.168.1.1:1053

iptables 设置
iptables -t nat -N REDSOCKS2_PRE
iptables -t nat -A PREROUTING -i br-lan -p tcp -j REDSOCKS2_PRE
# 其它 PRE的自己搞
iptables -t nat -N REDSOCKS2_OUT
iptables -t nat -I OUTPUT -d xxx.xxx.xxx.43 -j RETURN
iptables -t nat -A OUTPUT -p tcp -j REDSOCKS2_OUT
iptables -t nat -A REDSOCKS2_OUT -p tcp -d 8.8.8.8.8 --dport 80 -j REDIRECT --to-ports 1089

大约就是这样了，　没有仔细验证

**Comment by wltc2005** [comment]
我做验证了，确实如此。

**Comment by wltc2005** [comment]
我做验证了，确实如此。
问题主要出自于加出来的autoproxy = 0这个端口必须监听0.0.0.0

**Comment by wltc2005** [comment]
我做验证了，确实如此。
问题主要出自于加出来的autoproxy = 0这个端口必须监听0.0.0.0和
iptables -t nat -A OUTPUT -p tcp -d {dnsip} -j REDIRECT --to-ports {port}
