### ISSUE TITLE
传输自定义TCP协议，接收数据包很慢

### ISSUE THREAD

**Issue by mysteriouss** [semigodking/redsocks#27]
是否是深拷贝造成的? 另外，并不是每一次发送的大的字节流都慢，有的时候小字节流反而比大字节流慢。。

**Comment by semigodking** [comment]
不是，libevent 不进行深拷贝。你的具体实现可能有问题
2015年11月17日 上午7:23，"mysteriouss" <notifications@github.com>写道：

**Comment by mysteriouss** [comment]
也不是很慢，大概有1秒左右的延迟，不使用redsocks情况下是正常的，没有这个现象发生。。我改了好一会儿代码呢，然后切换了几次网络才发现（哭

**Comment by semigodking** [comment]
试试把TCL 的 no delay 打开
2015年11月17日 上午7:36，"mysteriouss" <notifications@github.com>写道：

**Comment by mysteriouss** [comment]
版本是 aa65535大编译的openwrt的0.60-2  
https://github.com/aa65535/openwrt-redsocks2/releases

好！服务端应该是打开了，客户端应该没有打开no delay，我先试一下！谢谢。

**Comment by semigodking** [comment]
那你先试试用最新版吧。且，就算打开也不至于影响到一秒，你打autoproxy 功能关掉试。
2015年11月17日 上午7:40，"mysteriouss" <notifications@github.com>写道：

**Comment by mysteriouss** [comment]
autoproxy关掉后，连不上服务器. 是一个国内服务器，TCP Server，没有TLS。

发送数据确认没有问题了，是接收服务器的回包慢。我一会儿看下返回的长度。

**Comment by semigodking** [comment]
解决了？
2015年11月24日 下午2:03，"mysteriouss" <notifications@github.com>写道：

**Comment by mysteriouss** [comment]
在没用redsocks的情况下也出现了，觉得是加解密部分的效率问题而不是代理的问题..一会儿我会把这部分代码去掉

**Comment by mysteriouss** [comment]
解决了，谢谢！
