### ISSUE TITLE
redsocks2前端还有一层ss代理时无法正确判断被封IP

### ISSUE THREAD

**Issue by dinstein** [semigodking/redsocks#28]
先描述下我的网络结构：
服务器（A）和路由器（B）在同一个局域网内，A 能直接联网，B 不能直接联网，但是可以连到A，因此在 A 上起了个ss 的 server，B 里起了个 ss-redir ，然后把B中 OUTPUT 链的流量全部导入 ss-redir 监听的端口，这样B上跑的程序都能正常联网。

redsocks2 跑在上述路由器B上，配置成ss模式（服务器为墙外一台VPS），将路由器中 PREROUTING 链的流量导入 redsocks2 监听的端口，此时在连接该路由器的PC机中访问被封网站，无法自动切换使用代理。
redsocks2日志如下：

    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: accepted
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: data relaying started
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: WCB relay, fs: 0, ts: 0, fin: 137, fout: 0, tin: 0
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: sent: 0, recv: 0, in:137, out:0
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 137, tin: 137
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: WCB relay, fs: 0, ts: 0, fin: 137, fout: 0, tin: 0
    Thu Nov  5 14:16:33 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: sent: 137, recv: 0, in:137, out:0
    Thu Nov  5 14:16:34 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: RECV Timeout, state: 10001, data_sent: 137
    Thu Nov  5 14:16:34 2015 daemon.debug redsocks[2574]: [192.168.2.157:49504->173.252.120.6:80]: IP Confirmed

我尝试了下， 如果只将路由器 OUTPUT 链中连接 VPS 的流量导入ss-redir 监听的端口，其余流量不处理，此时redsocks2能正常切换到ss代理模式并正常连接，日志如下：

    Thu Nov  5 14:18:47 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: accepted
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: relay, errno(0), State: 10000, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: IP Blocked
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: ADD IP to cache: 173.252.120.6
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: dropping relay only 
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: data relaying started
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB relay, fs: 0, ts: 0, fin: 137, fout: 0, tin: 0
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 160, tin: 0
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
    Thu Nov  5 14:18:49 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: client, what: READING|0|EOF|0|0|0|0x0: Success
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB relay, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: relay, what: READING|0|EOF|0|0|0|0x0: Success
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: WCB client, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: both client and server disconnected
    Thu Nov  5 14:18:51 2015 daemon.debug redsocks[2659]: [192.168.2.157:49541->173.252.120.6:80]: dropping client

**Comment by dinstein** [comment]
在上述描述中，采用第一种方法时，无法访问被封的IP，采用第二种方法时，所有IP都走VPS的代理了。这两种都不是期望的结果。

**Comment by semigodking** [comment]
何不试试把 redsocks2 放到 A, 在B 上用 TPROXY 把流量导到 A 上 redsocks2 的监听端口。
2015年11月20日 上午11:12，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
A 的系统是win7，用 cygwin 编译 redsocks2 是否可行？

**Comment by semigodking** [comment]
不行。那除了让A 做网关，B装 redsocks2就没什么好办法了
2015年11月20日 下午9:11，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
redsocks2自动代理方面，从日志看是否认为173.252.120.6这个IP没被封？  
在判断是否进行自动代理的逻辑这边做修改是否可行？

**Comment by semigodking** [comment]
可行但效果应该是不好的。原本依靠 connection reset
来判断的，你这种情况下要改成连接被远端关闭，且有发送无返回数据。可靠性有所下降，但应该可用，要改的地方也不多。
2015年11月20日 下午11:38，"dinstein" <notifications@github.com>写道：

**Comment by semigodking** [comment]
改改autoproxy.c 645 行的条件就行了。
2015年11月20日 下午11:43，"Semigod King" <semigodking@gmail.com>写道：

**Comment by dinstein** [comment]
ok，我看看，多谢解惑！ 不行我就在A上装个虚拟机跑redsocks2得了。。。

**Comment by dinstein** [comment]
看了下，把 651 行 “&& saved_errno == ECONNRESET ” 这句删了就可以简单粗暴的实现这个目的了吗？ 
这样带来的副作用就是有些不需要走代理的也会尝试走一遍代理，不会有无限循环代理的情况吧？

**Comment by dinstein** [comment]
另外还有个疑问，第一个日志中没有打印autoproxy.c 613行的日志信息，是不是没进 auto_event_error 这个函数？

**Comment by semigodking** [comment]
不行，条件应该是：
1. Eof
2. Data send > 0
3. Data recv = 0

不要改这个 if ， 在这个下面加上一个比较好
2015年11月22日 下午11:40，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
我试了下，在 autoproxy.c 645 行下面加重连的代码无效，因为这种情况下不会触发 auto_event_error；
最后我尝试在 autoproxy.c 226 行 (auto_recv_timeout_cb中) 加入重连的代码，这样能起作用，不过应该会导致一些不需要走代理的连接也走代理；
我看 auto_recv_timeout_cb 对应的定时器 aclient->recv_timer_event 的超时时间只有 0.6s，这个定时器的作用是什么？超时时间设为和 client->instance->config.timeout 一样会有问题不？

**Comment by semigodking** [comment]
有一种情况是，仅当 http
请求发出后连接才被重置。所以需要要发出http请求后等一下，看看连接有没有被重置，没重置就继续发。这个是用来处理这种情况的。既然你的情况会走到这里，那说明连接被重置后ss
server并不是正常关闭连接。那你调下这个timer也应该可以解决大部分问题
2015年11月24日 下午9:45，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
在你描述的这个情况下，这个超时时间没必要设为 0.6s 那么小，反而应该设大些才对（甚至无限大，即永远不要在接收到数据前确认连接正常），那样才可以处理发出 http 请求后经过较长延时才返回 reset 的情况吧？

**Comment by semigodking** [comment]
那如果跑的不是http 协议呢？即使是，也要考虑post 大文件这种不发完不回response的情况。
2015年11月24日 下午11:36，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
哦理解了，就是如果不确认连接正常，最开始发送的数据一直都保留着等待重发，这样很快发送缓存就满了？所以这个 0.6s 是个折中，即能包住reset的返回时间，又不会太影响性能。

**Comment by semigodking** [comment]
是的。现在大家网速都快了，0.6都有点多，不过总有网速慢的用户，所以一直没再往下调。
2015年11月25日 上午12:04，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
嗯，我想了下，我在 auto_recv_timeout_cb 这里改的话，会导致所有短时没有 response 的连接都走代理去了，算是勉强能实现我最初的需求吧。
插一句题外话，目前墙在起作用的时候，都还是会主动断开连接？会不会有像我的 ss server 一样一声不响就把连接掐了的情况？

**Comment by semigodking** [comment]
有， 那就对应了connection timeout的情况，所以才需要timeout这个设置。
你应该改下ss server, 让它遇到错误及时关闭连接。
2015年11月25日 上午12:14，"dinstein" <notifications@github.com>写道：

**Comment by dinstein** [comment]
connection timeout 是 writing timeout ，connected之后没有reading timeout吧？不过这个 reading timeout也确实不好定义，有可能远程本身就是不回任何消息。。。
我这个问题确实应该是ss server的问题，我先这么用着吧，抽空再看看ss的代码找找原因，多谢帮助！
