### ISSUE TITLE
可否指定某个网段必须走ss

### ISSUE THREAD

**Issue by hero18688** [semigodking/redsocks#30]
有的网段没被墙但是传输速度慢，比如github，走代理快很多，redsocks2可以实现吗？

**Comment by semigodking** [comment]
这种活交给iptables不是更好更简单吗？就像Google网段一样，直接iptables转到不开autoproxy的端口就行了。
2015年11月30日 上午9:12，"hero18688" <notifications@github.com>写道：

**Comment by hero18688** [comment]
那就需要开两个redsocks2进程一个开autoproxy，另一个不开吗

**Comment by semigodking** [comment]
同一个进程 同一个配置文件 可配置多份服务
2015年11月30日 下午8:02，"hero18688" <notifications@github.com>写道：
