### ISSUE TITLE
请问 redsocks2 is not enabled.Exit now. 是什么问题？

### ISSUE THREAD

**Issue by duffercn** [semigodking/redsocks#31]
安装完以后/etc/init.d/redsocks2 start就会出现这个错误：
redsocks2 is not enabled.Exit now.

直接用 /usr/sbin/redsocks2 -c xxx.conf 就可以。

小白我看了这段代码，但不太明白应该怎么改。求助，谢谢

if_enabled() {
	local cfg="$1"
	config_get_bool enabled "$cfg" 'enabled' '0'
	[ $enabled = '0' ] && {
		echo "redsocks2 is not enabled.Exit now."
		exit 1
	}
}

**Comment by semigodking** [comment]
在/etc/config/ 下应该有个redsocks2 的配置文件，里面没配，且里面'enabled'. =0
2015年12月21日 下午10:52，"duffercn" <notifications@github.com>写道：

**Comment by duffercn** [comment]
可是我的配置文件是在/etc/config/redsocks2.conf，我在文件第一行试着加了一行enabled="1"，还是不行。
感谢这么迅速的回复！

**Comment by semigodking** [comment]
你要自己看一下这文件的格式， 不是随便加的。
2015年12月21日 下午11:04，"duffercn" <notifications@github.com>写道：

**Comment by duffercn** [comment]
搞明白了，原来是配置文件的格式变了，然后运行时根据配置文件再生成redsocks2.conf。已搞定，再次感谢！
