### ISSUE TITLE
最新版本autoproxy不起作用

### ISSUE THREAD

**Issue by RobinHoo1973** [semigodking/redsocks#32]
从最新版本下载的源码编译成x86-64执行文件，redsock section的定义不起作用，无论在是shadowsocks/socks5模式下，autoproxy设成0/1，都无法重定向session，而且log文件无反应，server端也无数据。但是reudp可以工作，不知道为何？不知道是否可以放出4/5月份版本以供测试？

**Comment by semigodking** [comment]
不会不工作的，我也在用啊。应该是配置问题。如果你要旧版，直接got checkout到旧版再编译就是了。
2015年12月22日 上午7:56，"Robin Hoo" <notifications@github.com>写道：

**Comment by RobinHoo1973** [comment]
下面是我的配置，帮忙看下哪里的问题？谢谢了！
base {
        log_debug = on;
        log_info = on;
        log = "file:/var/log/redsocks2.log";
        daemon = off;
        redirector = iptables;
}
redsocks {
        local_ip = 0.0.0.0;
        local_port = 12345;
        ip = xxx.xxx.xxx.xx;
        port = xxxxx;
        type = shadowsocks;
        autoproxy = 1;
        timeout = 10;
        login = "aes-256-cfb";
        password = "Passw0rd";
}
redudp {
        local_ip = 127.0.0.1;
        local_port = 5353;
        ip = xxx.xxx.xxx.xx;
        port = xxxxx;
        login = "aes-256-cfb";
        password = "Passw0rd";
        type = shadowsocks;
        dest_ip = 8.8.8.8;
        dest_port = 53;
        udp_timeout = 3;
}
autoproxy {
    no_quick_check_seconds = 60;
    quick_connect_timeout = 3;
}
ipcache {
    cache_size = 4;
    stale_time = 900;
    port_check = 1;
    cache_file = "/tmp/ipcache.txt";
    autosave_interval = 3600;
}

**Comment by RobinHoo1973** [comment]
另外DNS有流量出去但是没有回复，下面是log细节：
1450793404.216663 main.c:184 main(...) redsocks started
1450793412.316009 redudp.c:374 redudp_first_pkt_from_client(...) [127.0.0.1:34955->8.8.8.8:53]: got 1st packet from client
1450793412.316059 redudp.c:332 redudp_flush_queue(...) [127.0.0.1:34955->8.8.8.8:53]: Starting UDP relay
1450793415.318230 redudp.c:346 redudp_timeout(...) [127.0.0.1:34955->8.8.8.8:53]: Client timeout. First: 1450793412, last_client: 1450793412, last_relay: 0.
1450793415.318273 redudp.c:245 redudp_drop_client(...) [127.0.0.1:34955->8.8.8.8:53]: Dropping UDP client
1450793419.317576 redudp.c:374 redudp_first_pkt_from_client(...) [127.0.0.1:34955->8.8.8.8:53]: got 1st packet from client
1450793419.317643 redudp.c:332 redudp_flush_queue(...) [127.0.0.1:34955->8.8.8.8:53]: Starting UDP relay
1450793422.321904 redudp.c:346 redudp_timeout(...) [127.0.0.1:34955->8.8.8.8:53]: Client timeout. First: 1450793419, last_client: 1450793419, last_relay: 0.
1450793422.321946 redudp.c:245 redudp_drop_client(...) [127.0.0.1:34955->8.8.8.8:53]: Dropping UDP client
1450793426.318397 redudp.c:374 redudp_first_pkt_from_client(...) [127.0.0.1:34955->8.8.8.8:53]: got 1st packet from client
1450793426.318463 redudp.c:332 redudp_flush_queue(...) [127.0.0.1:34955->8.8.8.8:53]: Starting UDP relay
1450793429.322391 redudp.c:346 redudp_timeout(...) [127.0.0.1:34955->8.8.8.8:53]: Client timeout. First: 1450793426, last_client: 1450793426, last_relay: 0.
1450793429.322434 redudp.c:245 redudp_drop_client(...) [127.0.0.1:34955->8.8.8.8:53]: Dropping UDP client
1450793433.318954 redudp.c:374 redudp_first_pkt_from_client(...) [127.0.0.1:34955->8.8.8.8:53]: got 1st packet from client
1450793433.319007 redudp.c:332 redudp_flush_queue(...) [127.0.0.1:34955->8.8.8.8:53]: Starting UDP relay
1450793436.322150 redudp.c:346 redudp_timeout(...) [127.0.0.1:34955->8.8.8.8:53]: Client timeout. First: 1450793433, last_client: 1450793433, last_relay: 0.
1450793436.322192 redudp.c:245 redudp_drop_client(...) [127.0.0.1:34955->8.8.8.8:53]: Dropping UDP client
1450793524.222103 redsocks.c:888 redsocks_audit_instance(...) Audit client list for instance 0x1d3b420(shadowsocks):
1450793524.222147 redsocks.c:909 redsocks_audit_instance(...) End of auditing client list.
1450793644.227105 redsocks.c:888 redsocks_audit_instance(...) Audit client list for instance 0x1d3b420(shadowsocks):
1450793644.227157 redsocks.c:909 redsocks_audit_instance(...) End of auditing client list.
1450793764.226828 redsocks.c:888 redsocks_audit_instance(...) Audit client list for instance 0x1d3b420(shadowsocks):
1450793764.226880 redsocks.c:909 redsocks_audit_instance(...) End of auditing client list.

**Comment by semigodking** [comment]
Udp需要你服务器端支持
2015年12月22日 下午10:17，"Robin Hoo" <notifications@github.com>写道：

**Comment by semigodking** [comment]
这里看不出什么问题
2015年12月22日 下午10:15，"Robin Hoo" <notifications@github.com>写道：

**Comment by RobinHoo1973** [comment]
关键是TCP autoproxy也不支持，这是关键

**Comment by RobinHoo1973** [comment]
老大,是我错了。可能是我的iptables配置问题，能帮我看看如下的配置是否有问题。谢谢了！
init_iptables() {
	iptables -t nat -N REDSOCKS2
	iptables -t nat -F REDSOCKS2
	
	# Ignore REDSOCKS2 server's IPv4 addresses
	iptables -t nat -A REDSOCKS2 -d 188.166.247.76 -j RETURN
	
	# Ignore LANs IP address
	iptables -t nat -A REDSOCKS2 -d 0.0.0.0/8 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 10.0.0.0/8 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 127.0.0.0/8 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 169.254.0.0/16 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 172.16.0.0/12 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 192.168.0.0/16 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 224.0.0.0/4 -j RETURN
	iptables -t nat -A REDSOCKS2 -d 240.0.0.0/4 -j RETURN
	iptables -t nat -A OUTPUT -j REDSOCKS2	
	# Redirect all tcp traffic
	iptables -t nat -A REDSOCKS2 -p tcp -j REDIRECT --to-ports 1080
	iptables -t nat -A REDSOCKS2 -p udp -j REDIRECT --to-ports 1080
	
	# Apply the rules
	iptables -t nat -I PREROUTING -p tcp -j REDSOCKS2
	iptables -t nat -I PREROUTING -p udp -j REDSOCKS2
}

**Comment by semigodking** [comment]
一般别加这句
iptables -t nat -A OUTPUT -j REDSOCKS2
2015年12月25日 下午4:32，"Robin Hoo" <notifications@github.com>写道：

**Comment by semigodking** [comment]
你确定这是你redsocks2 的local_port吗
-to-ports 1080
2015年12月25日 下午4:32，"Robin Hoo" <notifications@github.com>写道：

**Comment by RobinHoo1973** [comment]
port是正确的为了交叉测试shadowsocks和redsocks2所以设置了一样的，当然是任何时刻只有一个在运行状态。另外有没有那句OUTPUT都无法正常输出tcp。有那句OUTPUT，虽然也没有tcp出去，不过redsocks2.log很热闹，如果有输入wget www.google.com。但是没有任何数据出现在shadowsocks服务器端，自然本地wget也没输出。对了我是在CentOS6环境下测试。下面在给出一部分log输出。这次是有OUTPUT链的。如果没有OUTPUT 这句，log根本没有关于tcp流量的信息。感觉还是iptables配置问题。
````text
#wget www.google.com output
[root@localhost tmp]# !wget
wget www.google.com
--2015-12-25 12:44:25--  http://www.google.com/
Resolving www.google.com... 74.125.68.103, 74.125.68.147, 74.125.68.105, ...
Connecting to www.google.com|74.125.68.103|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-12-25 12:44:31--  (try: 2)  http://www.google.com/
Connecting to www.google.com|74.125.68.103|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

^C

````text
1451018650.049475 shadowsocks.c:369 ss_instance_init(...) using encryption method: aes-256-cfb
1451018650.049629 shadowsocks-udp.c:239 ss_instance_init(...) using encryption method: aes-256-cfb
1451018650.049652 redudp.c:581 redudp_init_instance(...) redudp @ 127.0.0.1:5353: destaddr=8.8.8.8:53
1451018650.049756 main.c:184 main(...) redsocks started
1451018665.652970 redudp.c:374 redudp_first_pkt_from_client(...) [127.0.0.1:44904->8.8.8.8:53]: got 1st packet from client
1451018665.653009 redudp.c:332 redudp_flush_queue(...) [127.0.0.1:44904->8.8.8.8:53]: Starting UDP relay
1451018666.003535 redsocks.c:795 redsocks_accept_client(...) [192.168.30.128:35523->74.125.68.103:80]: accepted
1451018666.003629 redsocks.c:795 redsocks_accept_client(...) [192.168.30.128:35524->74.125.68.103:80]: accepted
1451018666.003692 redsocks.c:376 redsocks_start_relay(...) [192.168.30.128:35523->74.125.68.103:80]: data relaying started
1451018666.003718 redsocks.c:795 redsocks_accept_client(...) [192.168.30.128:35525->74.125.68.103:80]: accepted
1451018666.003768 redsocks.c:376 redsocks_start_relay(...) [192.168.30.128:35524->74.125.68.103:80]: data relaying started
1451018666.003782 redsocks.c:287 process_shutdown_on_write_(...) [192.168.30.128:35523->74.125.68.103:80]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1451018666.003793 autoproxy.c:428 process_shutdown_on_write_2(...) [192.168.30.128:35523->74.125.68.103:80]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
1451018666.003800 autoproxy.c:276 handle_write_to_relay(...) [192.168.30.128:35523->74.125.68.103:80]: sent: 0, recv: 0, in:0, out:0
1451018666.003823 redsocks.c:795 redsocks_accept_client(...) [192.168.30.128:35526->74.125.68.103:80]: accepted
#REPEAT THE LOOP OF 795->376->287->428->276->795 in autoproxy.c UNTIL CTRL-C BREAK WGET

**Comment by semigodking** [comment]
知道你怎么用了  你这种情况需要保留OUTPUT但把所有由redsocks 发出的包根据pid  return。
具体怎么用--pid-owner自己查下吧。
2015年12月25日 下午5:40，"Robin Hoo" <notifications@github.com>写道：
