### ISSUE TITLE
redudp 转发dns好像有点问题。

### ISSUE THREAD

**Issue by xseven007** [semigodking/redsocks#35]
之前用darkk原版的遇到了这个问题
这是redsocks的日志
1453627149.720556 redudp.c:415 redudp_first_pkt_from_client(...) [127.0.0.1:47731->8.8.4.4:53]: got 1st packet from client
1453627149.720589 redudp.c:347 redudp_relay_connected(...) [127.0.0.1:47731->8.8.4.4:53]: <trace>
1453627149.722619 redudp.c:304 redudp_read_auth_methods(...) [127.0.0.1:47731->8.8.4.4:53]: <trace>
1453627149.722845 redudp.c:203 redudp_read_assoc_reply(...) [127.0.0.1:47731->8.8.4.4:53]: <trace>
1453627149.722890 redudp.c:186 redudp_flush_queue(...) [127.0.0.1:47731->8.8.4.4:53]: Starting UDP relay
1453627149.722938 redudp.c:373 redudp_relay_error(...) [127.0.0.1:47731->8.8.4.4:53]: redudp_relay_error
1453627149.722953 redudp.c:89 redudp_drop_client(...) [127.0.0.1:47731->8.8.4.4:53]: Dropping...
ss-loadl的日志是
 2016-01-24 01:18:59 INFO: [udp] cache miss: 8.8.4.4:53 <-> 127.0.0.1:60175
 2016-01-24 01:18:59 INFO: [udp] remote receive a packet
 2016-01-24 01:19:04 INFO: udp assc request accepted
 2016-01-24 01:19:04 INFO: [udp] server receive a packet
 2016-01-24 01:19:04 INFO: [udp] cache miss: 8.8.4.4:53 <-> 127.0.0.1:50688
 2016-01-24 01:19:05 INFO: [udp] remote receive a packet
 2016-01-24 01:19:09 INFO: udp assc request accepted
 2016-01-24 01:19:09 INFO: [udp] server receive a packet
 2016-01-24 01:19:09 INFO: [udp] cache miss: 8.8.4.4:53 <-> 127.0.0.1:51463
后来改用你的redsocks。仍然有此问题。服务端支持udp。

**Comment by semigodking** [comment]
原版问题多 我不再支持。 ss-loadl是什么？另外信息不足。
2016年1月24日 下午5:27，"phoenix.xie" <notifications@github.com>写道：

**Comment by xseven007** [comment]
你好，键盘按错，是ss-local。
redsocks2的日志信息是
1453689589.211426 redudp.c:586 redudp_init_instance(...) redudp @ 127.0.0.1:10053: destaddr=8.8.8.8:53
1453689589.211523 main.c:201 main(...) redsocks started
1453689608.946155 redudp.c:379 redudp_first_pkt_from_client(...) [127.0.0.1:59121->8.8.8.8:53]: got 1st packet from client
1453689608.946435 socks5-udp.c:354 socks5_relay_connected(...) [127.0.0.1:59121->8.8.8.8:53]: via 127.0.0.1:10099
1453689608.946635 socks5-udp.c:309 socks5_read_auth_methods(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689608.947102 socks5-udp.c:197 socks5_read_assoc_reply(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689608.947138 redudp.c:337 redudp_flush_queue(...) [127.0.0.1:59121->8.8.8.8:53]: Starting UDP relay
1453689608.947185 socks5-udp.c:380 socks5_relay_error(...) [127.0.0.1:59121->8.8.8.8:53]: socks5_relay_error
1453689608.947195 redudp.c:250 redudp_drop_client(...) [127.0.0.1:59121->8.8.8.8:53]: Dropping UDP client
1453689613.948785 redudp.c:379 redudp_first_pkt_from_client(...) [127.0.0.1:59121->8.8.8.8:53]: got 1st packet from client
1453689613.949144 socks5-udp.c:354 socks5_relay_connected(...) [127.0.0.1:59121->8.8.8.8:53]: via 127.0.0.1:10099
1453689613.951218 socks5-udp.c:309 socks5_read_auth_methods(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689613.951855 socks5-udp.c:197 socks5_read_assoc_reply(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689613.951907 redudp.c:337 redudp_flush_queue(...) [127.0.0.1:59121->8.8.8.8:53]: Starting UDP relay
1453689613.951961 socks5-udp.c:380 socks5_relay_error(...) [127.0.0.1:59121->8.8.8.8:53]: socks5_relay_error
1453689613.951975 redudp.c:250 redudp_drop_client(...) [127.0.0.1:59121->8.8.8.8:53]: Dropping UDP client
1453689618.964478 redudp.c:379 redudp_first_pkt_from_client(...) [127.0.0.1:59121->8.8.8.8:53]: got 1st packet from client
1453689618.964790 socks5-udp.c:354 socks5_relay_connected(...) [127.0.0.1:59121->8.8.8.8:53]: via 127.0.0.1:10099
1453689618.966727 socks5-udp.c:309 socks5_read_auth_methods(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689618.967344 socks5-udp.c:197 socks5_read_assoc_reply(...) [127.0.0.1:59121->8.8.8.8:53]: <trace>
1453689618.967415 redudp.c:337 redudp_flush_queue(...) [127.0.0.1:59121->8.8.8.8:53]: Starting UDP relay
1453689618.967527 socks5-udp.c:380 socks5_relay_error(...) [127.0.0.1:59121->8.8.8.8:53]: socks5_relay_error
1453689618.967551 redudp.c:250 redudp_drop_client(...) [127.0.0.1:59121->8.8.8.8:53]: Dropping UDP client
1453689709.232188 redsocks.c:879 redsocks_audit_instance(...) Audit client list for instance 0xed7430(socks5):
1453689709.232329 redsocks.c:900 redsocks_audit_instance(...) End of auditing client list.

**Comment by semigodking** [comment]
如果我没记错的话ss local 的 socks5 是不支持udp 的。
2016年1月25日 上午10:54，"phoenix.xie" <notifications@github.com>写道：

**Comment by xseven007** [comment]
开了-u之后应该是支持的啊。用sockcap测试过可以解析DNS。ss服务端那边也显示有
 2016-01-25 11:00:46 INFO: [udp] server receive a packet
 2016-01-25 11:00:46 INFO: [udp] cache miss: 8.8.8.8:53 <-> 124.226.58.66:57183
 2016-01-25 11:00:46 INFO: [udp] remote receive a packet
 2016-01-25 11:00:51 INFO: [udp] server receive a packet
 2016-01-25 11:00:51 INFO: [udp] cache miss: 8.8.8.8:53 <-> 124.226.58.66:57184
 2016-01-25 11:00:51 INFO: [udp] remote receive a packet
 2016-01-25 11:00:56 INFO: [udp] server receive a packet
 2016-01-25 11:00:56 INFO: [udp] cache miss: 8.8.8.8:53 <-> 124.226.58.66:57186
 2016-01-25 11:00:56 INFO: [udp] remote receive a packet

**Comment by semigodking** [comment]
我得看看ss local 代码才知道。 从表现上看是不支持，socks5 立即关闭了session
2016年1月25日 上午11:09，"phoenix.xie" <notifications@github.com>写道：

**Comment by semigodking** [comment]
你说的ss local 是指 python 版的吗？ 如果是的话那是不支持的
2016年1月25日 上午11:14，"Semigod King" <semigodking@gmail.com>写道：

**Comment by xseven007** [comment]
libev版本。

**Comment by semigodking** [comment]
我看了libev版代码，它并不支持udp association.
2016年1月25日 上午11:27，"phoenix.xie" <notifications@github.com>写道：

**Comment by xseven007** [comment]
好吧，原来是ss-local的锅

**Comment by semigodking** [comment]
如果你只是为了处理dns的话可以考虑tcp dns。
2016年1月25日 上午11:54，"phoenix.xie" <notifications@github.com>写道：
