### ISSUE TITLE
redudp搭配ss-local不能实现udp转发？

### ISSUE THREAD

**Issue by e2ge** [semigodking/redsocks#36]
现在已经成功实现TPROXY直接将udp转发至ss-redir，可以上网没有问题，ss-server已经加-u。
tcp使用redsocks2的autoproxy功能，所以就想同时使用redsocks2的redudp，这样就不用开一个ss-local还要再开一个ss-redir
所以，
设置redudp type为socks5 （没有直接使用shadowsocks，因为服务器开启了OTA）
ip和port为ss-local的的地址和端口，没有设置dest_ip和port，日志有TPROXY出现

redudp.c:576 redudp_init_instance(...) redudp @ 0.0.0.0:1024: TPROXY

ss-local也开启-u，结果是无法转发udp，日志中出现udp relay error
想问是设置问题，还是没有这个功能。

**Comment by semigodking** [comment]
Redudp 功能最近我仔细测过没有问题。sslocal 对udp 的支持我没验证过， 建议你先用第三方软件验证 sslocal 对socks5
udp的支持是正常的。
2016年1月24日 下午10:03，"e2ge" <notifications@github.com>写道：

**Comment by semigodking** [comment]
刚确认过 ss local 不支持 udp association
2016年1月24日 下午10:26，"Semigod King" <semigodking@gmail.com>写道：
