### ISSUE TITLE
blog.csdn.net Can't open, can't go. Agent

### ISSUE THREAD

**Issue by ghostry** [semigodking/redsocks#4]
blog.csdn.net 无法打开,不能走代理.

**Comment by semigodking** [comment]
请提供详细信息，如使用什么代理类型，不能打开的表现是什么？ redsocks2打开blog.csdn.net时的debug log等等

**Comment by ghostry** [comment]
无法显示此网页

隐藏详细信息
网址为 http://blog.csdn.net/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
错误代码：ERR_CONNECTION_ABORTED

shadowsocks.
debug不会看哦

**Comment by semigodking** [comment]
经过验证，无论是否开启智能代理，使用shadowsocks代理均可正常访问该网址。
