### ISSUE TITLE
Error Cross compiling redsocks2 to OpenWrt 

### ISSUE THREAD

**Issue by hillz1** [semigodking/redsocks#40]
This is the error log:
```
linux@x:/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2$ make package/redsocks2/compile V=99
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
#
# configuration written to .config
#
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
make[1]: Entering directory `/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
make[1]: *** No rule to make target `package/redsocks2/compile'.  Stop.
make[1]: Leaving directory `/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
make: *** [package/redsocks2/compile] Error 2
```
This is my `Makefile`:
```
#
# Copyright (C) 2014 OpenWrt-dist
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=redsocks2
PKG_VERSION:=0.60
PKG_RELEASE=2

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/aa65535/openwrt-redsocks2/releases/download/v$(PKG_VERSION)
PKG_MD5SUM:=b88bf23bf75fa7642f8d230db21f73b9

PKG_LICENSE:=GPLv2
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=Zhuofei Wang <SemigodKing@gmail.com>

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)/$(BUILD_VARIANT)/$(PKG_NAME)-$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk

define Package/redsocks2
	SECTION:=net
	CATEGORY:=Network
	TITLE:=Redirect any TCP connection to a SOCKS or HTTPS proxy server
	URL:=https://github.com/semigodking/redsocks
	DEPENDS:=+libevent2
endef

define Package/redsocks2/description
This is a modified version of original redsocks. \
The name is changed to be REDSOCKS2 since this release to distinguish with original redsocks. \
This variant is useful for anti-GFW (Great Fire Wall).
endef

define Package/redsocks2/conffiles
/etc/config/redsocks2
endef

define Package/redsocks2/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/redsocks2 $(1)/usr/bin
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_DATA) ./files/redsocks2.config $(1)/etc/config/redsocks2
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/redsocks2.init $(1)/etc/init.d/redsocks2
	$(INSTALL_DIR) $(1)/etc/redsocks2
	$(INSTALL_DATA) ./files/redsocks2.template $(1)/etc/redsocks2/config.template
endef

$(eval $(call BuildPackage,redsocks2))
```
Since I don't know anything about `Makefile` configurations I just copied it from https://github.com/aa65535/openwrt-redsocks2 Please help me to fix that problem.
I know I can just follow the tutorial at https://github.com/aa65535/openwrt-redsocks2 to compile it to openwrt, I have tried that and it works well but I think the version of redsocks2 on that link is outdated (it's on redsocks2 v0.60), and I can't use the option `tcpdns` if I use redsocks2 from that link

**Comment by semigodking** [comment]
Use this one:
https://github.com/wongsyrone/openwrt-1/tree/master/package/external/redsocks2

**Comment by hillz1** [comment]
I'm still unable to compile it, here's what I did:

1. cd OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2
2. git clone https://github.com/semigodking/redsocks.git package/redsocks2
3. Replace the original Makefile with the one you provided
4. Create a new folder inside "redsocks2" named "files" containing _redsocks2.config, redsocks2.include, redsocks2.init_ 
5. Run command: _make menuconfig_ and check the redsocks2 package
6. Run command: _make package/redsocks2/compile V=99_

This is the error:
```
galih@x:/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2$ make package/redsocks2/compile V=99
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
#
# configuration written to .config
#
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
make[1]: Entering directory `/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
Makefile:43: warning: overriding commands for target `clean'
package/Makefile:111: warning: ignoring old commands for target `clean'
make[1]: *** No rule to make target `package/redsocks2/compile'.  Stop.
make[1]: Leaving directory `/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2'
make: *** [package/redsocks2/compile] Error 2
```
Please tell me where I went wrong

**Comment by semigodking** [comment]
Incorrect building steps.
Reference: https://wiki.openwrt.org/doc/howto/obtain.firmware.sdk

**Comment by hillz1** [comment]
From the link you provided, first thing I should do is to check whether it needs dependencies, so I do:
`grep DEPENDS package/Makefile # The Makefile is from https://github.com/wongsyrone/openwrt-1/tree/master/package/external/redsocks2
`
It returns: `DEPENDS:=$(3)` I suppose it doesn't need any dependencies
Then I do:
`make package/redsock2/download`
But it returns something like this:
```
/media/Data/OpenWRT/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/tmp/info/.files-packageinfo.mk:2: *** target pattern contains no `%'.  Stop.
make[1]: *** [prepare-tmpinfo] Error 2
make: *** [package/redsock2/download] Error 2
```

**Comment by hillz1** [comment]
I moved the `Makefile` from `package/redsocks2/Makefile` to `package/Makefile`

**Comment by semigodking** [comment]
package/external/redsocks2 is for building openwrt IPK. its contents should be copied into WRT SDK/package/
Then you should build it like:
make package/redsocks2/compile

You should spend a little time on reading OpenWRT documents for building WRT packages.

**Comment by hillz1** [comment]
Yes I already put everything in that folder, check this out: http://s30.postimg.org/f88tu19up/image.png

**Comment by hillz1** [comment]
The `Makefile` is outside of the `redsocks2` directory http://s10.postimg.org/65bpjxhbd/image.png

**Comment by semigodking** [comment]
This is really a simple job:
 /tmp/redsocks2/ is from https://github.com/wongsyrone/openwrt-1/tree/master/package/external/redsocks2


[user1@localhost openwrt_cc_SDK]$ cd package/
[user1@localhost package]$ mv /tmp/redsocks2/ .
[user1@localhost openwrt_cc_SDK]$ ls -al package/redsocks2/
total 16
drwxr-xr-x  3 user1 user1 4096 Mar 24 15:23 .
drwxr-xr-x 12 user1 user1 4096 Mar 24 15:23 ..
-rw-r--r--  1 user1 user1 3028 Mar 24 15:23 Makefile
drwxr-xr-x  2 user1 user1 4096 Mar 24 15:23 files
[user1@localhost package]$ cd ..
[user1@localhost openwrt_cc_SDK]$ make package/redsocks2/compile
 make[1] package/redsocks2/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/libs/ocf-crypto-headers compile
 make[2] -C package/libs/zlib compile
 make[2] -C package/libs/openssl compile
 make[2] -C package/libs/libevent2 compile
 make[2] -C package/libs/polarssl compile
 make[2] -C package/redsocks2 compile
[user1@localhost openwrt_cc_SDK]$ ls -al bin/brcm63xx/packages/base/redsocks2_0.65-1_brcm63xx.ipk
-rw-r--r-- 1 user1 user1 61039 Mar 24 15:39 bin/brcm63xx/packages/base/redsocks2_0.65-1_brcm63xx.ipk

**Comment by hillz1** [comment]
I've tried everything I could but it always ended up like the error above, I've tried cloning the openwrt repository to my pc, and doing exactly the same thing like you did above but it still returns the same error. I even tried booting up with a fresh distro and started everything from scratch but still no luck, can you please compile it for me? I'm on OpenWrt Barrier Breaker and my router is Gl-iNet 6416 (ar71xx).

**Comment by semigodking** [comment]
[redsocks2_ar71xx.tg.zip](https://github.com/semigodking/redsocks/files/188950/redsocks2_ar71xx.tg.zip)
You may want to rename it to redsocks2_ar71xx.tgz.
Extract: tar -zxf redsocks2_ar71xx.tgz

**Comment by hillz1** [comment]
Thank you very much for compiling it for me. I installed it successfully.
