### ISSUE TITLE
日志小问题

### ISSUE THREAD

**Issue by muziling** [semigodking/redsocks#42]
把local ip 和 port 当作 代理地址了
shadowsocks.c:360 ss_instance_init(...) shadowsocks @ 192.168.1.1:60001: encryption method: aes-256-cfb

另外polarssl 版本基本没法用吧，启动起来一个网页都没法完整打开就退出了

**Comment by semigodking** [comment]
那个就是显示local IP port的。至于pollarssl, 我会再测下，很早之前测过是行的。

**Comment by muziling** [comment]
我的polarssl版本是1.3.9，不知道是否有关系

**Comment by semigodking** [comment]
polarssl问题已经修复。
