### ISSUE TITLE
在虚拟机内的 Debian Jessie 下编译错误

### ISSUE THREAD

**Issue by R1ct** [semigodking/redsocks#43]
本机系统：Ubuntu 16.04
虚拟机：VMware Workstation 12.1.1 build-3770994
系统：最新的 Debian Jessie 最小化安装版本

依赖包 及 Build-Essential 均已安装

症状：
编译时缺少 "parser.o" .
如图：
_[http://moefq.com/image/LNxSA](url)_

**Comment by semigodking** [comment]
看不到图。但你可查下为什么parser.c 没正常编译
2016年5月2日 20:24，"R1ct" <notifications@github.com>写道：
