### ISSUE TITLE
Redsocks2支持把本地DNS请求导给TorDNS？

### ISSUE THREAD

**Issue by naijim** [semigodking/redsocks#44]
感觉对于某些对于隐私非常敏感的场景，最好是能把所有外出请求，所有TCP和UDP请求导向Tor，然后Tor丢弃UDP请求，印象中Tor好像是不支持UDP的吧；对于DNS，把所有DNS请求导向TorDNS

**Comment by semigodking** [comment]
可以，比较曲折，不支持 tordns.
方法：将dns转给tcpdns, 再将tcpdns 发出的tcp连接用redsocks转到 tor的socks5即可。需对iptables较熟悉。
2016年5月10日 20:17，"Naiji Ma" <notifications@github.com>写道：

**Comment by naijim** [comment]
你觉得，只是简单把本地的nameserver设置成TorDNS能防止DNS泄漏么？

**Comment by semigodking** [comment]
不能。用户又不一定非用你本地的dns
2016年5月10日 21:40，"Naiji Ma" <notifications@github.com>写道：

**Comment by naijim** [comment]
好吧，不过对大多数情形应该够了。除非有什么程序绕过本地的DNS设定
