### ISSUE TITLE
www.flickr.com 好像没法自动通过代理走

### ISSUE THREAD

**Issue by muziling** [semigodking/redsocks#45]
开启了自动代理。

**Comment by semigodking** [comment]
我这里一切正常。
2016年5月15日 20:27，"muziling" <notifications@github.com>写道：

**Comment by muziling** [comment]
本地DNS解析出来，和AWS的一致，就是没办法自动翻墙，GOOGEL之类的都能自动出去

**Comment by semigodking** [comment]
你得抓点log 和包才知道是什么情况，否则说不清楚啊~
2016年5月15日 20:43，"muziling" <notifications@github.com>写道：

本地DNS解析出来，和AWS的一致，就是没办法自动翻墙，GOOGEL之类的都能自动出去

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/semigodking/redsocks/issues/45#issuecomment-219283721>

**Comment by muziling** [comment]
83.177.81.75:443]: IP Confirmed  这一行是指没走代理吧。


1463316993.947137 redsocks.c:797 redsocks_accept_client(...) [192.168.1.22:44019->74.125.204.188:5228]: accepted
1463316997.550557 redsocks.c:797 redsocks_accept_client(...) [192.168.1.2:59641->183.177.81.75:443]: accepted
1463316997.789117 redsocks.c:375 redsocks_start_relay(...) [192.168.1.2:59641->183.177.81.75:443]: data relaying started
1463316997.789257 autoproxy.c:426 process_shutdown_on_write_2(...) [192.168.1.2:59641->183.177.81.75:443]: WCB relay, fs: 0, ts: 0, fin: 202, fout: 0, tin: 0
1463316997.789317 autoproxy.c:274 handle_write_to_relay(...) [192.168.1.2:59641->183.177.81.75:443]: sent: 0, recv: 0, in:202, out:0
1463316997.789457 redsocks.c:287 process_shutdown_on_write_(...) [192.168.1.2:59641->183.177.81.75:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 202, tin: 202
1463316997.789777 autoproxy.c:426 process_shutdown_on_write_2(...) [192.168.1.2:59641->183.177.81.75:443]: WCB relay, fs: 0, ts: 0, fin: 202, fout: 0, tin: 0
1463316997.789877 autoproxy.c:274 handle_write_to_relay(...) [192.168.1.2:59641->183.177.81.75:443]: sent: 202, recv: 0, in:202, out:0
1463316997.924537 redsocks.c:797 redsocks_accept_client(...) [192.168.1.10:59556->99.247.43.48:23851]: accepted
1463316998.191117 autoproxy.c:221 auto_recv_timeout_cb(...) [192.168.1.2:59641->183.177.81.75:443]: RECV Timeout, state: 10001, data_sent: 202
1463316998.191257 autoproxy.c:191 on_connection_confirmed(...) [192.168.1.2:59641->183.177.81.75:443]: IP Confirmed
1463316999.950257 autoproxy.c:600 auto_event_error(...) [192.168.1.22:44019->74.125.204.188:5228]: relay, errno(0), State: 10000, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success

**Comment by semigodking** [comment]
感觉你dns问题或远端服务器问题。这是我这边的。

root@OpenWrt:~# nslookup www.flickr.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost.

Name:      www.flickr.com
Address 1: 121.101.144.112 r1.ycpi.vip.hka.yahoo.net
Address 2: 121.101.144.116 r2.ycpi.vip.hka.yahoo.net
root@OpenWrt:~#
2016年5月15日 20:59，"muziling" <notifications@github.com>写道：

**Comment by muziling** [comment]
opendns解析的，这个地址在AWS上可以访问。

**Comment by semigodking** [comment]
如果DNS正确的话，那我怀疑你遇到的是我最近一直在怀疑的一种新的block方式，即允许建立ＴＣＰ连接但连接后收不到任何数据，但目前一直未有足够证据表明这种方式的存在．比如你现在这个情况，仅是到这一个ＩＰ的连接有问题，说不定你ＤＮＳ返回另一个IP就正常了.那就有可能只是落地服务器或CDN服务器出了问题. 所以,我需要等足够证据才能出解决方案.

**Comment by muziling** [comment]
AWS的DNS和wget正常

# dig +tcp www.flickr.com @208.67.222.222 -p 5353

; <<>> DiG 9.9.5-3ubuntu0.6-Ubuntu <<>> +tcp www.flickr.com @208.67.222.222 -p 5353
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6243
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;www.flickr.com.			IN	A

;; ANSWER SECTION:
www.flickr.com.		281	IN	CNAME	flickr-panda-police.a00.yahoodns.net.
flickr-panda-police.a00.yahoodns.net. 7	IN A	183.177.81.75
flickr-panda-police.a00.yahoodns.net. 7	IN A	183.177.81.74

;; Query time: 2 msec
;; SERVER: 208.67.222.222#5353(208.67.222.222)
;; WHEN: Sun May 15 12:09:12 UTC 2016
;; MSG SIZE  rcvd: 125


# wget www.flickr.com
--2016-05-15 12:21:47--  http://www.flickr.com/
Resolving www.flickr.com (www.flickr.com)... 183.177.81.75, 183.177.81.74
Connecting to www.flickr.com (www.flickr.com)|183.177.81.75|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.flickr.com/ [following]
--2016-05-15 12:21:47--  https://www.flickr.com/
Connecting to www.flickr.com (www.flickr.com)|183.177.81.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 215974 (211K) [text/html]
Saving to: ‘index.html’

100%[=====================================================================================================================================================>] 215,974      280KB/s   in 0.8s   

2016-05-15 12:21:48 (280 KB/s) - ‘index.html’ saved [215974/215974]

**Comment by semigodking** [comment]
这样子来看就很有可能是新的blocking method，在出解决方案前我还需收集更多的证据及线索。如有其它类似现象请反馈并注明宽带运营商。
2016年5月16日 19:58，"muziling" <notifications@github.com>写道：

**Comment by realgtk** [comment]
@muziling redsocks2可以设置某些IP强制走代理，具体方法如下：
1、新增一个代理，端口54321，不勾选自动代理。
2、建立一个新IPLIST，放在/etc/force.list
3、修改/etc/init.d/redsocks2 在iptables下新增强制代理端口和iptables规则。
config_get dest_port2 "$cfg" 'dest_port2'
iptables ......
iptables ......
        [ "$forcelist_enabled" = '1' ] && {                                               
        sed -e "s/^/-A forcelist &/g" -e "1 i\-N forcelist nethash --hashsize 64" $ipset_forcelist | ipset -R -!
        iptables -t nat -A $CHAIN_NAME -p tcp -m set --match-set forcelist dst -j REDIRECT --to-ports "$dest_port2"
        }
luci相关文件也需要修改
这样某些IP就不通过redcosk2去判断，而是强制走代理。这个方法对某些网站禁止中国使用服务（可以访问，但无法使用其服务）也有效，例如namestation.com。
