### ISSUE TITLE
Question(s): Is building for Android 5.0+ possible, would tunneling OpenVPN(UDP) over Shadowsocks work, and what about Shadowsocks's One Time Auth feature? 

### ISSUE THREAD

**Issue by tonsimple** [semigodking/redsocks#47]
Hi!
I'm looking for a way to tunnel OpenVPN(UDP) over Shadowsocks on android.
Turns out Shadowsocks for Android isn't quite up for the task
https://github.com/shadowsocks/shadowsocks-android/issues/726#issuecomment-227027516

So... I started looking around, stumbled upon your project, and now I have a bunch of questions.

The questions are:

1) Can Redsocks2 be built for Android 5.0+ (PIE, etc) ?

2) If yes, how :-) ?

3) Can it be used to tunnel OpenVPN's UDP traffic over Shadowsocks ?

4) If yes, would it rely on TPROXY support in iptables ? _(many android devices don't have TPROXY destination support in iptables)_

5) And last (and somewhat unrelated) question, does Redsocks2  support Shadowsocks One-Time-Auth feature (https://shadowsocks.org/en/spec/one-time-auth.html)?

Thank you very much!

**Comment by semigodking** [comment]
Please see my comments inline.

2016年6月23日 00:39，"Simply Sarah" <notifications@github.com>写道：
>
> Hi!
> I'm looking for a way to tunnel OpenVPN(UDP) over Shadowsocks on android.
> Turns out Shadowsocks for Android isn't quite up for the task
> shadowsocks/shadowsocks-android#726 (comment)
>
> So... I started looking around, stumbled upon your project, and now I
have a bunch of questions.
>
> The questions are:
>
> 1) Can Redsocks2 be built for Android 5.0+ (PIE, etc) ?
>
> 2) If yes, how :-) ?
Yes. The instructions are on Wiki.
https://github.com/semigodking/redsocks
It is in Chinese. I am not sure if you can read.

>
> 3) Can it be used to tunnel OpenVPN's UDP traffic over Shadowsocks ?
>
Yes.

> 4) If yes, would it rely on TPROXY support in iptables ? (many android
devices don't have TPROXY destination support in iptables)
>
Given openVPN has determined destination IP and Port, UDP redirection can
be done without TPROXY. You need to generate redsocks' configuration
according to openvpn settings to let redsocks know the destination IP and
port.

> 5) And last (and somewhat unrelated) question, does Redsocks2 support
Shadowsocks One-Time-Auth feature (
https://shadowsocks.org/en/spec/one-time-auth.html)?
No.

**Comment by tonsimple** [comment]
Hi! Thanks for prompt reply

> Yes. The instructions are on Wiki.
> https://github.com/semigodking/redsocks
> It is in Chinese. I am not sure if you can read.

I'm not fluent in Chinese, but Google Translate seems to have done a decent enough job it seems

> Given openVPN has determined destination IP and Port, UDP redirection can
> be done without TPROXY. You need to generate redsocks' configuration
> according to openvpn settings to let redsocks know the destination IP and
> port.

Unfortunately that is not the case :-( 
Server is a hostname that resolves to different IPs based on VPN provider's load balancing shenanigans.

I reckon that, given no TPROXY support, I'm out of luck then ?

**Comment by semigodking** [comment]
Resolvable hostname is OK.
2016年6月24日 00:03，"Simply Sarah" <notifications@github.com>写道：
