### ISSUE TITLE
Help to compile and run redsocks2 on FreebBSD

### ISSUE THREAD

**Issue by v20z** [semigodking/redsocks#48]
Hello Gentlemen.

Had somebody successfully compile and use redsocks2 on modern branches of FreeBSD? Please share you experience, tricks and configuration tips.

Thank You.

**Comment by semigodking** [comment]
Here is a dirty patch which makes redsocks2 successfully compiled with FreeBSD 10.3. 
I did NOT do any functional verification.  You can verify it. 

To compile with FreeBSD:
``` shell
pkg install gmake
pkg install libevent2
setenv CFLAGS "-I/usr/local/include -L/usr/local/lib"

gmake
```

This is the patch
``` patch
diff --git a/Makefile b/Makefile
index 532bb51..1b49ca5 100644
--- a/Makefile
+++ b/Makefile
@@ -9,7 +9,7 @@ VERSION := 0.65

 LIBS := -levent
 CFLAGS +=-fPIC -O3
-override CFLAGS += -std=c99 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall
+override CFLAGS +=  -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall
 #LDFLAGS += -fwhole-program
 ifdef USE_CRYPTO_POLARSSL
 override LIBS += -lpolarssl
@@ -39,6 +39,9 @@ $(CONF):
        Linux*) \
                echo "#define USE_IPTABLES" >$(CONF) \
                ;; \
+       FreeBSD) \
+               echo "#define USE_IPF" >$(CONF) \
+               ;; \
        OpenBSD) \
                echo "#define USE_PF" >$(CONF) \
                ;; \
diff --git a/base.c b/base.c
index 0edc8db..8df15b4 100644
--- a/base.c
+++ b/base.c
@@ -18,6 +18,13 @@
 #include <sys/types.h>
 #include <sys/socket.h>
 #include <netinet/in.h>
+#include <netinet/ip.h>
+#include <net/if.h>
+# include <sys/ioctl.h>
+       #include        <netinet/ip_compat.h>
+       #include        <netinet/ip_fil.h>
+//       #include      <netinet/ip_proxy.h>
+       #include        <netinet/ip_nat.h>
 #include <netinet/tcp.h>
 #include <arpa/inet.h>
 #include <sys/stat.h>
@@ -32,6 +39,7 @@
 # include <limits.h>
 # include <linux/netfilter_ipv4.h>
 #endif
+
 #if defined USE_PF
 # include <net/if.h>
 # include <net/pfvar.h>
diff --git a/libc-compat.h b/libc-compat.h
index adcf63b..177b484 100644
--- a/libc-compat.h
+++ b/libc-compat.h
@@ -22,4 +22,8 @@
 #   define IP_TRANSPARENT 19
 #endif

+#ifndef SOL_IP
+#   warning Using hardcoded value for SOL_IP as libc headers do not define it.
+#   define SOL_IP IPPROTO_IP
+#endif
 #endif // 67C91670_FCCB_4855_BDF7_609F1EECB8B4
diff --git a/utils.c b/utils.c
index 6ecc685..a82a79f 100644
--- a/utils.c
+++ b/utils.c
@@ -131,7 +131,7 @@ struct bufferevent* red_connect_relay_if(const char *ifname,
         log_errno(LOG_ERR, "socket");
         goto fail;
     }
-
+/*
     if (ifname) {
         error = setsockopt(relay_fd, SOL_SOCKET, SO_BINDTODEVICE, ifname, strlen(ifname));
         if (error) {
@@ -139,7 +139,7 @@ struct bufferevent* red_connect_relay_if(const char *ifname,
             goto fail;
         }
     }
-
+*/
     error = evutil_make_socket_nonblocking(relay_fd);
     if (error) {
         log_errno(LOG_ERR, "evutil_make_socket_nonblocking");
diff --git a/utils.h b/utils.h
index a77bff9..199f18c 100644
--- a/utils.h
+++ b/utils.h
@@ -4,6 +4,11 @@
 #include <stddef.h>
 #include <time.h>
 #include <event.h>
+#include <netinet/in.h>
+#ifndef INADDR_LOOPBACK
+#define INADDR_LOOPBACK                0x7F000001
+#endif
+

 struct sockaddr_in;


```

**Comment by v20z** [comment]
Thanks for your reply.

Yes, it compiles and works when  autoproxy=0. 
When autoproxy=1 it infinitely accepts connection until exhausted sockets with error:
kern.ipc.maxsockets limit reached

Minimal patch.sh:
#!/bin/sh

SED_INPLACE="sed -i .bak"

$SED_INPLACE \
-e '/^override CFLAGS += -std=c99/c\
override CFLAGS += -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall\
' \
-e '/OpenBSD)/i\
\	FreeBSD) \\\
\		echo "#define USE_IPF" >$(CONF) \\\
\		;; \\\
' Makefile

$SED_INPLACE '/^#include <arpa\/inet\.h>/a\
#include <net/if.h>\
#include <netinet/ip_fil.h>\
#include <netinet/ip_nat.h>\
#include <sys/ioctl.h>\
' base.c 

$SED_INPLACE '/^#include <event\.h>/a\
#include <netinet/in.h>\
' utils.h

if [ ! -f libc-compat.h ]; then
export CFLAGS="$CFLAGS -D INADDR_LOOPBACK=0x7f000001 -D SOL_IP=IPPROTO_IP -D SO_BINDTODEVICE=IP_RECVIF"
else
$SED_INPLACE '/^#ifndef IP_TRANSPARENT/i\
#ifndef INADDR_LOOPBACK\
#   define INADDR_LOOPBACK 0x7F000001 \
#endif\
\
#ifndef SOL_IP\
#   define SOL_IP IPPROTO_IP\
#endif\
\
#ifndef SO_BINDTODEVICE\
#   define SO_BINDTODEVICE IP_RECVIF \
#endif\
\
' libc-compat.h
fi

**Comment by semigodking** [comment]
"infinitely accepts connection" usually implies redirection loop. You need to check PF rules to ensure no redirection loop. Note, when autoproxy = 1, outgoing connection is tried with default route and default interface before passing through proxy.

**Comment by v20z** [comment]
Works fine as autoproxy when running under specific user name, for example:

	user = redsocks;
	group = redsocks;
	...
	local_port = 1081;
	local_ip = localhost;

and then rule like this:

	ipfw add fwd 127.0.0.1,1081 tcp from any to any out via $INTERFACE
