### ISSUE TITLE
redsocks2 与 路由器端口映射冲突？

### ISSUE THREAD

**Issue by wang20150419** [semigodking/redsocks#49]
现象：在路由器(openwrt )设置内网机器的端口映射，如果启动 redsocks2，则映射后的端口无法使用。
如果关闭redsocks2，则正常。换成ss-redir也正常。

这个问题如何解决？

已通过iptables 设置了  iptables -t nat -A REDSOCKS2 -d 192.168.0.0/16 -j RETURN

**Comment by semigodking** [comment]
信息不够。你应该先确保redsocks2 没有在0.0.0.0上做监听。

2016年7月22日 05:05，"wang20150419" <notifications@github.com>写道：

**Comment by wang20150419** [comment]
哦，的确如此，不在0.0.0.0上做监听就正常了，谢谢！
