### ISSUE TITLE
和某些 app 例如 twitter.app 的兼容问题

### ISSUE THREAD

**Issue by nutinshell** [semigodking/redsocks#50]
路由器上转发到 socks5 代理，iOS 上使用 twitter.app 一段时间后（使用 - home键退出 - 玩会别的app - 再打开 twitter.app），会出现一直转菊花的情况，kill 掉app重开即可。或者重启 redsocks2 也可。

**Comment by semigodking** [comment]
这个“一段时间”是多长时间？有没有超过两个小时？另外，你应该尝试收点log，做TCPDUMP。否则很难知道发生了什么。

**Comment by nutinshell** [comment]
时长时短，10几20分钟的样子。我试试dump份数据看看。

**Comment by realgtk** [comment]
@nutinshell 老版本吧，尝试编译最新版本呢？我以前用网上其他人编译的老版本经常会出现问题，自己编译最新版本后一切正常。

**Comment by realgtk** [comment]
@nutinshell 我看到你是通过redsocks2<--->socks5？socks5传输是明文的，很容易被干扰。

**Comment by nutinshell** [comment]
@realgtk 最新的编译。socks5是转换后的，中间加密了。没发现别的什么问题，就这个毛病比较蛋疼。

**Comment by realgtk** [comment]
@nutinshell 我也尝试过redsocks2<--->stunnel<--->socks5<-->stunnel<--->vps，效果没有shadowsocks快。我觉得还是加密层效率的问题。

**Comment by nutinshell** [comment]
@realgtk 并不是效率问题很显然。性能非常好，能跑300Mbps+

**Comment by realgtk** [comment]
@nutinshell 300M+只表示你国内的带宽大，并不代表你翻出去的效率高。应该把你整个网络环境详细说明下，包括DNS防污染配置。我在MTK芯片以及AR9331这种低端路由上都没发现这种情况，应该不是redsocks2的问题。

**Comment by realgtk** [comment]
@nutinshell 300M+只表示你国内的带宽大，并不代表你翻出去的效率高。应该把你整个网络环境详细说明下，包括DNS防污染配置。我在MTK芯片以及AR9331这种低端路由上都没发现这种情况，应该不是redsocks2的问题。

**Comment by nutinshell** [comment]
@realgtk 不好意思。。300M+的确是翻出去的带宽，国内带宽不止这个。没有什么其它问题，唯独只有这个问题，dns单独走 ipsec vpn 出去。tcp 单独 iptables 转发给 redsocks2。

**Comment by realgtk** [comment]
@nutinshell 如果你是用UDP53，即使用IPSEC-VPN也会被GWF干扰。

**Comment by realgtk** [comment]
@nutinshell 另外，twitter在国内封锁的方式是污染DNS，实际的IP并没有屏蔽。也就是说如果DNS防污染做好，就算不翻墙也可以访问，只是速度上差一点。如果你打开了redsocks2的自动代理，有可能访问twitter是不走代理而是直连。

**Comment by nutinshell** [comment]
@realgtk udp53跑在ipsec tunnel里会被干扰？我书读的少...

**Comment by realgtk** [comment]
@nutinshell 2015年就被干扰了，你到现在还不知道？实在没招就抓包分析呗。
（最后一次回复）
