### ISSUE TITLE
tcpdns很难使用

### ISSUE THREAD

**Issue by gonejack** [semigodking/redsocks#51]
我的代理服务器是socks5，不是shadowsocks，使用pdnsd把udp请求转为到8.8.4.4的tcp包。再

```
ipset add gfwlist 8.8.4.4。
iptables -t nat -A OUTPUT -m -set --match-set gfwlist dst -j REDIRECT --to-port {redsocks2_port}
```

把包交给redsocks2代理，这里是没有问题的。

看到新版的redsocks2里关于redudp和tcpdns的介绍，也是摸索起来怎么把pdnsd省了。

但文档写得真的很简洁。

1、我不知道这两条通道的包是经过代理还是直接发出的。直接试失败，往OUTPUT链里加规则将包跳往redsocks2还是失败。

2、查看日志，又发现配置里base{}里 log debug 和 log info 的 off 和 on 开关无效，一定会写磁盘。

3、redudp可能是要shadowsocks服务器配合我不知道我的socks5行不行，文档也没写就不试了。

4、tcpdns 发出的包无论经不经过tcp代理，都是失败的，频繁报在tcpdns_event_error这个函数，错误信息看不懂。

翻代码发现下面，暂时需要作者解释。

```
/* connect to target directly without going through proxy */
        req->resolver = red_connect_relay2(destaddr,
                        tcpdns_readcb, tcpdns_connected, tcpdns_event_error, req, 
                        &tv);
```

最好的话能写一些交互性的安装脚本之类，至少大家用不动看不懂的时候，能够去翻看一下安装脚本在做什么，还能了解到一些

**Comment by semigodking** [comment]
使用ＴＣＰＤＮＳ可以不用iptables转发，直接把tcpdns的监听端口当做ＤＮＳ 的上游服务器使用即可。当然，如果你一定要把tcpdns发出的tcp连接转到加密的代理上的话，就需要iptables了。正常情况下，国内即使使用tcpdns，如果不加密直接连接的话，虽然不会被污染，但tcp连接会被重置。也就是说，对很多域名，你还是没法解析。

**Comment by AlexZhuo** [comment]
tcpdns功能配置文件书写如下
`base {
log_debug = off;
log_info = on;
daemon = on;
redirector = iptables;
}
tcpdns {
	local_ip = 0.0.0.0;
	local_port = 12345; 
	tcpdns1 = 8.8.8.8;   
	tcpdns2 = 8.8.4.4;
	timeout = 4;
}`
然后使用下面命令启动redsocks2
`/usr/sbin/redsocks2 -c $CFG_FILE -p $PID_FILE`
无法把udp的DNS请求转换为TCP请求，dig的请求结果如下
`
root@OpenWrt:~# dig @127.0.0.1 -p 12345 www.youku.com

; <<>> DiG 9.9.8-P3 <<>> @127.0.0.1 -p 12345 www.youku.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
`
但是我使用redudp的shadowsocks模式是可以的
希望能尽快修复tcpdns的问题，替换掉pdnsd

**Comment by semigodking** [comment]
TCPDNS没有问题啊。应该是你的ISP直接屏蔽了TCP到8.8.4.4和 8.8.8.8的连接吧。

`[kitty@default redsocks2]$ cat tcpdns.conf
base {
 log_debug = on;
 log_info = on;
 daemon = off;
 redirector= iptables;
}
tcpdns {
        local_ip = 127.0.0.1; // Local server to act as DNS server
        local_port = 1053;      // UDP port to receive UDP DNS requests
        tcpdns2 = 8.8.8.8;      // DNS server that supports TCP DNS requests
        timeout = 4;            // Timeout value for TCP DNS requests
}

[kitty@default redsocks2]$
[kitty@default redsocks2]$ ./redsocks2 -c tcpdns.conf  &
[1] 20994
[kitty@default redsocks2]$ 1485063981.803780 tcpdns.c:480 tcpdns_init_instance(...) tcpdns @ 127.0.0.1:1053
1485063981.803796 main.c:236 main(...) redsocks started with: epoll

[kitty@default redsocks2]$
[kitty@default redsocks2]$
[kitty@default redsocks2]$
[kitty@default redsocks2]$ dig @127.0.0.1 -p 1053 www.baidu.com
1485064001.497690 tcpdns.c:223 choose_tcpdns(...) Dealy of TCP DNS resolvers: 0, 0
1485064001.498781 tcpdns.c:108 tcpdns_readcb(...) [127.0.0.1:42510->127.0.0.1:1053]: response size: 92
1485064001.498873 tcpdns.c:78 tcpdns_drop_request(...) [127.0.0.1:42510->127.0.0.1:1053]: dropping request @ state: 2

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6_6.2 <<>> @127.0.0.1 -p 1053 www.baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27381
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          738     IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       7       IN      A       14.215.177.37
www.a.shifen.com.       7       IN      A       14.215.177.38

;; Query time: 1 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Sun Jan 22 13:46:41 2017
;; MSG SIZE  rcvd: 90

`

**Comment by AlexZhuo** [comment]
首先感谢作者的回答
我在Ubuntu上编译了0.66的版本，发现TCP DNS没有问题
于是我重新编译了0.66版本的OpenWrt版本发现TCP DNS也是正常的
之前的无法TCP DNS查询是0.65的版本（大约是2016年11月的master分支）
我测试将TCP DNS端口重定向到Redsocks2的透明代理端口，效果非常好，可以通过代理服务器查询DNS，速度也很快。（ps：如果不经过代理，那么使用国内DNS查询google是污染地址，使用国外DNS查询返回为空）

TCP DNS是非常好用的功能，配合代理服务器可以取代pdnsd了。唯一和pdnsd不同的是，pdnsd不经过代理也可以查询到无污染的地址。
真挚感谢作者的奉献

**Comment by semigodking** [comment]
其实，如果你的线路可以的话，你大可以试试用cdns，效果比这个好很多。
对于非53端口的支持，我有机会加进来。
你的IPK安装包，我先加进wiki吧，后面再加入readme。

**Comment by semigodking** [comment]
非53端口你也可以利用iptables DNAT等方式解决。

**Comment by AlexZhuo** [comment]
Redsocks2配置简单运行稳定，特来支持Redsocks2的普及，我在蝈蝈大神OpenWrt luci的基础上添加了TCP DNS的支持，SS UDP转发的支持，并修复了一些bug，改进了界面布局等等。包含了0.66版的绝大多数功能。分享一下：https://github.com/AlexZhuo/luci-app-redsocks2

**Comment by semigodking** [comment]
DNS over TCP也是被干扰的。虽然还是有办法避免干扰，但TCPDNS这个功能暂时不会再做加强。如果有需求，还是先试试[cdns](https://github.com/semigodking/cdns/)吧。
