### ISSUE TITLE
可否直接提供Android NDK交叉编译redsocks2需要的那几个文件

### ISSUE THREAD

**Issue by xseven007** [semigodking/redsocks#52]
分别是search.h,tsearch.c,twalk.c,twalk.c,tdelte.c,tdenstroy.c ，不知道网上找到的不对还是怎么样，无法编译通过。

**Comment by tofuliang** [comment]
解包Android版shadowsocks吧，里面有

phoenix.xie <notifications@github.com>于2016年8月18日周四 20:50写道：

**Comment by xseven007** [comment]
哪个位置？

**Comment by tofuliang** [comment]
apk里面

phoenix.xie <notifications@github.com>于2016年8月18日周四 21:12写道：

**Comment by xseven007** [comment]
apk文件内为何会有.c文件？我解包了，并没有

**Comment by xseven007** [comment]
@tofuliang 这几个文件是libc的文件，根本不会出现再便宜好的APK包里面好吗。

**Comment by tofuliang** [comment]
......    我说编译好的redsocks2

phoenix.xie <notifications@github.com>于2016年8月18日周四 21:21写道：

**Comment by xseven007** [comment]
你这样说相当于本末倒置了吧

**Comment by xseven007** [comment]
@yanggis 请问一下，我这边编译不通过，出现
[armeabi] Compile thumb  : redsocks <= main.c
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c: In function 'wait_for_network':
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c:95:25: error: 'IPPROTO_TCP' undeclared (first use in this function)
     hints.ai_protocol = IPPROTO_TCP; /* We want a TCP socket */
                         ^
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c:95:25: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/android-ndk/build/core/build-binary.mk:472: recipe for target '/opt/src/redsocks/android/obj/local/armeabi/objs/redsocks/main.o' failed
make: *** [/opt/src/redsocks/android/obj/local/armeabi/objs/redsocks/main.o] Error 1

**Comment by semigodking** [comment]
到musl里面有

2016年8月18日 20:50，"phoenix.xie" <notifications@github.com>写道：

**Comment by xseven007** [comment]
@semigodking 我在这里https://android.googlesource.com/platform/bionic/+/21eab513e7eec280a7a8bcb9482a1a8b61e59442/libc/bionic 找到了所有的文件，放到目录后，编译，出现上面的错误

**Comment by xseven007** [comment]
@semigodking musl的包里面只有tdestroy.c。估计有一部分在GNU？Libc可以找到？

**Comment by semigodking** [comment]
所需要的都在这几个文件里
https://git.musl-libc.org/cgit/musl/tree/src/search
头文件在include/search.h

**Comment by xseven007** [comment]
@semigodking 现在问题出在ndk-build过程中，出现这样的错误
[armeabi] Compile thumb  : redsocks <= main.c
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c: In function 'wait_for_network':
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c:95:25: error: 'IPPROTO_TCP' undeclared (first use in this function)
     hints.ai_protocol = IPPROTO_TCP; /* We want a TCP socket */
                         ^
/opt/src/redsocks/android/jni/openssl/ssl/../../../../main.c:95:25: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/android-ndk/build/core/build-binary.mk:472: recipe for target '/opt/src/redsocks/android/obj/local/armeabi/objs/redsocks/main.o' failed
make: *** [/opt/src/redsocks/android/obj/local/armeabi/objs/redsocks/main.o] Error 1

应该是main.c文件输出的时候出现了问题。请问有没解决方案？

**Comment by semigodking** [comment]
把那个函数和对其的调用注释掉比较简单粗暴

**Comment by lmzmem** [comment]
能否提供android可以直接编译的project，在现在的project上按照文档里面提供的NDK编译方法还是编译不出来

**Comment by semigodking** [comment]
什么问题？缺文件？！　　
我从没有在NDK上编译过 :)

**Comment by lmzmem** [comment]
文档说在git上找shadows-android，也不知道哪个是文档说的project。克隆了一个看起来最像的shadows-android里面有openssl和libevent，没有libevent2。https://git.musl-libc.org/cgit/musl/tree/src/search上面找不全tsearch.c,tfind.c,twalk.c,tdelte.c,tdenstroy.c，上面只有tdestroy.c，和include里面的search.h，其他文件都没有

**Comment by semigodking** [comment]
就在我说的那里，research_avl.c 文件名变了而已

**Comment by edveen** [comment]
感谢回复！那这个几个tsearch.c tdelete.c tdestroy.c tfind.c twalk.c文件分别对应里面的那几个文件？
实在是猜不出来对应关系

**Comment by semigodking** [comment]
主要是刚那个，还有year-round.c. 其它的可能不需要。我手机不方便看

2016年11月24日 22:10，"edveen" <notifications@github.com>写道：

**Comment by edveen** [comment]
感谢！等您方便的时候帮忙看下可以吗。

另外这个Android NDK编译教程是哪位大神写的，直接联系他获取这些文件也是一个可行的办法。

**Comment by semigodking** [comment]
那个wiki是  @yanggis  写的。
你所需要的文件:
https://git.musl-libc.org/cgit/musl/tree/include/search.h
https://git.musl-libc.org/cgit/musl/tree/src/search/tsearch_avl.c
如果编译器lsearch什么的没有定义的话，你还需要
https://git.musl-libc.org/cgit/musl/tree/src/search/lsearch.c

**Comment by edveen** [comment]
非常感谢！！！如果是改成search.h，tsearch_avl.c，lsearch.c的话，是不是就要修改Android.mk里面的LOCAL_SRC_FILES，把tsearch.c tdelete.c tdestroy.c tfind.c twalk.c改成tsearch_avl.c lsearch.c

**Comment by semigodking** [comment]
是的。

2016年11月25日 22:03，"edveen" <notifications@github.com>写道：

**Comment by edveen** [comment]
tsearch_avl.c编译报错：
/root/redsocks/android/jni/openssl/ssl/../../../../tsearch_avl.c:122:21: error: conflicting types for 'remove'
 static struct node *remove(struct node **n, const void *k,
                     ^
In file included from /root/redsocks/android/jni/openssl/ssl/../../../../bits/alltypes.h:31:0,
                 from /root/redsocks/android/jni/openssl/ssl/../../../../search.h:11,
                 from /root/redsocks/android/jni/openssl/ssl/../../../../tsearch_avl.c:2:
/root/android-ndk-r10e/platforms/android-14/arch-arm/usr/include/stdio.h:246:6: note: previous declaration of 'remove' was here
 int  remove(const char *);

**Comment by semigodking** [comment]
在tsearch_avl.c 开头加上个
undef remove 试试

2016年11月25日 22:13，"edveen" <notifications@github.com>写道：

**Comment by lmzmem** [comment]
还是通不过，还是提示函数已经定义过了

**Comment by semigodking** [comment]
那你用个最简单最粗暴的方法解决问题先 ^_^ 　把tsearch_avl.c中的remove 函数直接重名，比如remove_123，然后把tsearch_avl.c所有对remove函数的引用都相应改成remove_123　这总可以吧。一共３处引用，两处在remove 函数内部，一处在tdelete函数内。

**Comment by lmzmem** [comment]
这里改了通过了，libevent2里面又报错了，也不知道是不是这个libevent2，shadowsocks里面已经没有libevent2，只有libevent，在别处找的libevent2

/root/redsocks/android/jni/libevent2/select.c: In function 'select_init':
/root/redsocks/android/jni/libevent2/select.c:67:36: error: 'fd_mask' undeclared (first use in this function)
  (DIV_ROUNDUP(n, NFDBITS) * sizeof(fd_mask))
                                    ^
/root/redsocks/android/jni/libevent2/select.c:108:25: note: in expansion of macro 'SELECT_ALLOC_SIZE'
  if (select_resize(sop, SELECT_ALLOC_SIZE(32 + 1))) {
                         ^
/root/redsocks/android/jni/libevent2/select.c:67:36: note: each undeclared identifier is reported only once for each function it appears in
  (DIV_ROUNDUP(n, NFDBITS) * sizeof(fd_mask))
                                    ^
/root/redsocks/android/jni/libevent2/select.c:108:25: note: in expansion of macro 'SELECT_ALLOC_SIZE'
  if (select_resize(sop, SELECT_ALLOC_SIZE(32 + 1))) {
                         ^
/root/redsocks/android/jni/libevent2/select.c: In function 'select_add':
/root/redsocks/android/jni/libevent2/select.c:255:26: error: 'fd_mask' undeclared (first use in this function)
   if (fdsz < (int)sizeof(fd_mask))
                          ^
make: *** [/root/redsocks/android/obj/local/armeabi/objs/event2/libevent2/select.o] Error 1

**Comment by semigodking** [comment]
libevent2 官方就有。这个我帮不到你

**Comment by edveen** [comment]
我从@yanggis那里获得了一份编译好的redsocks，已经可以在安卓上运行起来了。现在的问题是UDP不能代理，安卓上面好像没有tproxy，请问如何能让UDP正常代理起来？

**Comment by semigodking** [comment]
我也听说没有tproxy, 那只能redirect到指定IP，别无它法。

**Comment by edveen** [comment]
我试过用iptables redirect，UDP数据没网

**Comment by edveen** [comment]
哦，理解错了，您意思是指定到固定的地址，这样的话，不能全局代理了吧

**Comment by semigodking** [comment]
是，也就只能用于dns代理这样。像tcp那样透明代理是没办法的了。

2016年11月28日 20:52，"edveen" <notifications@github.com>写道：

**Comment by edveen** [comment]
看来要另外想办法了，不知道shadowsocks是如何做到udp全局代理的

**Comment by semigodking** [comment]
下源码去研究下呗。

2016年11月28日 21:16，"edveen" <notifications@github.com>写道：

**Comment by edveen** [comment]
旷日持久的痛苦开始了

**Comment by semigodking** [comment]
已包含进repo
