### ISSUE TITLE
能不能支持 TCP direct tproxy ，有没有添加支持的计划

### ISSUE THREAD

**Issue by hnkeyang** [semigodking/redsocks#53]

**Comment by semigodking** [comment]
TPROXY 已支持。

2016年9月12日 01:22，"hnkeyang" <notifications@github.com>写道：

**Comment by hnkeyang** [comment]
我按 doc/balabit-TPROXY-README.txt 配置了规则,使用 squid tproxy 代理正常，源IP也是真实用户IP，但使用redsocks 就无法访问了，redsocks 不使用iptables redirect  到redsocks 时访问是正常的
tproxy iptables 和 ip rule 配置如下：
iptables -t mangle -N DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 111
iptables -t mangle -A DIVERT -j ACCEPT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A PREROUTING -p tcp -m tcp --dport 80 -j TPROXY --on-port 3129 --on-ip 0.0.0.0 --tproxy-mark 0x6f/0xffffffff

ip rule add fwmark 111 lookup 100
ip route add local default dev lo table 100

redsocks.conf redsocks { } 配置如下

redsocks {
    local_ip = 0.0.0.0;
    //local_port = 12345;
    local_port = 3129;

    ip = 1.1.1.1;
    port = 10080;
    type = direct;
    autoproxy = 0;
    timeout = 10;
}
是配置有问题吗

**Comment by semigodking** [comment]
为什么需要花时间在ＴＣＰ　ＴＰＲＯＸＹ上呢? REDIRECT的方式简单好用啊，还不用搞ip rules。

**Comment by semigodking** [comment]
对不起，我前面记错了。REDSOCKS目前是不支持TCP的TPROXY的，一般没有这种需求，所以也没有人去尝试添加这个功能。对于TCP来说，直接使用REDIRECT会方便很多，因为不需要修改ip rule和ip route

**Comment by semigodking** [comment]
已添加TCP TPROXY支持。

**Comment by hnkeyang** [comment]
非常感谢！
已经可以使用。

**Comment by shellus** [comment]
@semigodking 
你前面不是说“一般没有这种需求，所以也没有人去尝试添加这个功能。对于TCP来说，直接使用REDIRECT会方便很多，因为不需要修改ip rule和ip route” 吗？为什么后面还是添加了这个功能呢？

是因为发现TCP TPROXY还是有某些特殊的作用吗？

**Comment by semigodking** [comment]
好像也没什么。如果有什么的话，那就是方便配合ip rules 做特殊路由。当时也只是顺手加上去的

**Comment by hnkeyang** [comment]
我当时用这个功能是测试 redsocks 部署在一个启用了bbr的系统上，做透明代理截断TCP做加速，同时又不改变源地址
