### ISSUE TITLE
Compile failed in Openwrt with commit on 13 oct

### ISSUE THREAD

**Issue by hqvv** [semigodking/redsocks#54]
redsocks.c: In function 'display_mallinfo':
redsocks.c:893:21: error: storage size of 'mi' isn't known
     struct mallinfo mi;
                     ^
redsocks.c:895:10: warning: implicit declaration of function 'mallinfo' [-Wimplicit-function-declaration]
     mi = mallinfo();
          ^
redsocks.c:893:21: warning: unused variable 'mi' [-Wunused-variable]
     struct mallinfo mi;
                     ^
<builtin>: recipe for target 'redsocks.o' failed

Many thank for your great work!

**Comment by semigodking** [comment]
This function display_mallinfo can be safely removed,it is for debugging
purpose. I will remove it a bit later.

2016年10月15日 18:14，"Hanqing" <notifications@github.com>写道：

**Comment by semigodking** [comment]
已修复
