### ISSUE TITLE
通过VPN interface转发流量要怎么做？

### ISSUE THREAD

**Issue by ekenchan** [semigodking/redsocks#57]
我用interface=<VPN interface>转发流量不成功

**Comment by semigodking** [comment]
那个interface的参数，看wiki。说下你的具体需求。

**Comment by semigodking** [comment]
Autoproxy和 redsocks 两个都是可以接受interface参数的。

**Comment by ekenchan** [comment]
我有一个vpn连接，想用redsocks打开一个socks5端口做透明代理，用chnroute区分国外流量，用iptables把流量redirect到redsocks端口，然后redsocks把流量用vpn的interface发出去

**Comment by semigodking** [comment]
那就用direct方式，指定interface为vpn interface，不开autoproxy。

2016年11月28日 21:07，"ekenchan" <notifications@github.com>写道：
