### ISSUE TITLE
使用redsocks代理ss-local连接无法上网

### ISSUE THREAD

**Issue by phoebushome** [semigodking/redsocks#58]
我使用redsocks+ss-local代理上网，不能访问网络。
本人是新手，期待各位大大的帮助
在路由器上执行测试命令：curl --proxy 192.168.1.1:8080 www.sina.com
返回结果为：curl: (52) Empty reply from server。
ss-local的代理可正常工作，测试方法是：curl --socks5 192.168.1.1:1080 www.sina.com；返回结果是正常的。
路由器上没有设置iptables，若需要请告知必须的设置。
---------------
redsocks的配置文件内容为：
base {
  log_debug = on;
  log_info = on;
  //log = stderr;
  log = "file:/jffs/redsocks2.log";
  daemon = on;
  redirector= iptables;
}

redsocks {
  local_ip = 0.0.0.0;
  local_port = 8080;
  ip = 192.168.1.1;
  port = 1080;
  type = socks5;
  timeout = 3;
  autoproxy = 1;
}

autoproxy {
  no_quick_check_seconds = 0;
  quick_connect_timeout = 1;
}

ipcache {
  cache_size = 8;
  cache_file = "/jffs/test/redsocks2/ipcache.txt";
  stale_time = 7200;
  autosave_interval = 3600;
  port_check = 1;
}

**Comment by phoebushome** [comment]
下面是redsocks的日志文件：
[redsocks2.txt](https://github.com/semigodking/redsocks/files/643520/redsocks2.txt)

**Comment by semigodking** [comment]
这两个一般不一起用。具体配置参考wiki

2016年12月10日 10:17，"phoebushome" <notifications@github.com>写道：

**Comment by phoebushome** [comment]
刚开始时在redsocks2中直接使用Shadowsock的配置，不知道什么原因数据包转发不出去，然后将这个步骤分开来寻找问题。还请指点

**Comment by semigodking** [comment]
你为什么不直接让redsocks2 连接ss服务器？iptables 可照着这里的做
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=165801&mobile=2

2016年12月10日 13:39，"phoebushome" <notifications@github.com>写道：
