### ISSUE TITLE
FreeBSD Compilation fails: header not found

### ISSUE THREAD

**Issue by fabianfrz** [semigodking/redsocks#59]
Error:
```
base.c:42:11: fatal error: 'netinet/ip_fil.h' file not found
```

FreeBSD Version 10.3

**Comment by fabianfrz** [comment]
Just to be complete: I had to add this include too: '-I/usr/local/include/'

**Comment by semigodking** [comment]
Yes. The readme is not updated to include instructions for freebsd
compilation. I guess freebsd users know how to solve it. :)

2016年12月19日 14:49，"Fabian Franz" <notifications@github.com>写道：

**Comment by semigodking** [comment]
To build on FreeBSD with gmake:

export CFLAGS="-I/usr/local/include -L/usr/local/lib"
gmake


2016年12月19日 20:35，"Semigod King" <semigodking@gmail.com>写道：

**Comment by v20z** [comment]
Please take a look here:
https://github.com/semigodking/redsocks/issues/48
May be it will help you.

**Comment by fabianfrz** [comment]
@v20z I am not using IPF - I tried to compile it on OPNsense which is using IPFW (Captive Portal, Traffic shaper) and PF (main Firewall).

**Comment by v20z** [comment]
Also I've noticed that release source distribution compiles successfully without any patches and much issues under FreeBSD 11.

**Comment by v20z** [comment]
Redsocks works well with ipfw as mentioned and described at most bottom on https://github.com/semigodking/redsocks/issues/48
Please investigate workability and PF rules by yourself and then share found solution with us here.
