### ISSUE TITLE
有打算集成SSR吗

### ISSUE THREAD

**Issue by realgtk** [semigodking/redsocks#60]
貌似SS协议部分地区已经被墙

**Comment by semigodking** [comment]
我没认真了解过ssr, 根据其描述，我感觉ssr已经把ss
协议变得很复杂了，又没有协议说明文档，全靠看代码，想支持它也不容易啊，那得多少时间啊。哪天ss用不了了，我觉得简单变换下协议或伪装下就好，不用搞那么复杂啊。使用轻量协议，哪天不爽哪天变，墙想三天两头跟着变也跟不上啊。

2016年12月19日 21:44，"realgtk" <notifications@github.com>写道：

**Comment by hqvv** [comment]
反对支持ssr
那东西太花哨了，而且一直在有意无意的靠造谣中伤ss来宣传自己

**Comment by realgtk** [comment]
：）也有道理，反正现在SS还能正常用，等大规模被墙的时候再说吧。
