### ISSUE TITLE
Everything goes fine,but icmp would not be through to dest.

### ISSUE THREAD

**Issue by cebernic** [semigodking/redsocks#63]
TCP & UDP worked,but icmp doesn't relay in same host of dest ,it timeout always. why?

**Comment by semigodking** [comment]
Redsocks does not handle icmp packages.

2017年1月17日 22:54，"cebernic" <notifications@github.com>写道：

**Comment by cebernic** [comment]
Well,...Thanks for your response....xD..... and could it be handling on ICMP at abit futrue? I think it's very important for some else games and apps within global proxy.

Anyway ,you did a nice work ,wish you keep it going...

**Comment by semigodking** [comment]
thanks. I do not think icmp is supported by the following kinds of proxy: http/socks5/shadowsocks.  You need network layer VPN to support ICMP.
