### ISSUE TITLE
Ubuntu 16.04.2 LTS Xenial Xerus x64 r0.66 Partial Compile

### ISSUE THREAD

**Issue by entianbucali** [semigodking/redsocks#65]
Hello,

I am using Ubuntu 16.04.2 LTS (Xenial Xerus) x64.

I have installed all the necessary prerequisites to compile redsocks correctly:

`sudo apt-get install git-core libssl-dev libevent-dev build-essential autoconf g++ subversion linux-source linux-headers build-essential tofrodos git-core dos2unix make gcc automake cmake checkinstall dpkg-dev fakeroot pbuilder dh-make debhelper devscripts patchutils quilt git-buildpackage pristine-tar git yasm cvs mercurial`

when I enter in Terminal:

`brett@brettub:~/compile/redsocks-release-0.66$ make`

I receive the following errors and 'redsocks2' is compiled but it doesn't work.

`Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
mkdir -p gen
touch gen/.build
rm -f gen/version.c.tmp
echo '/* this file is auto-generated during build */' > gen/version.c.tmp
echo '#include "../version.h"' >> gen/version.c.tmp
echo 'const char* redsocks_version = ' >> gen/version.c.tmp
if [ -d .git ]; then \
echo '"redsocks.git/'`git describe --tags`' OpenSSL"'; \
if [ `git status --porcelain | grep -v -c '^??'` != 0 ]; then \
echo '"-unclean"'; \
fi \
else \
echo '"redsocks/0.66 OpenSSL"'; \
fi >> gen/version.c.tmp
echo ';' >> gen/version.c.tmp
mv -f gen/version.c.tmp gen/version.c
gcc -MM parser.c main.c redsocks.c log.c direct.c ipcache.c autoproxy.c encrypt.c shadowsocks.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c socks5-udp.c shadowsocks-udp.c tcpdns.c gen/version.c 2>/dev/null >.depend || \
( \
for I in redsocks.h libc-compat.h list.h encrypt.h shadowsocks.h parser.h version.h main.h log.h md5.h socks5.h base64.h redudp.h tcpdns.h ipcache.h utils.h base.h http-auth.h; do \
export ${I//[-.]/_}_DEPS="`sed '/^\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $I`"; \
done; \
echo -n >.depend; \
for SRC in parser.c main.c redsocks.c log.c direct.c ipcache.c autoproxy.c encrypt.c shadowsocks.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c socks5-udp.c shadowsocks-udp.c tcpdns.c gen/version.c; do \
echo -n "${SRC%.c}.o: " >>.depend; \
export SRC_DEPS="`sed '/\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $SRC | sort`"; \
while true; do \
export SRC_DEPS_OLD="$SRC_DEPS"; \
export SRC_DEEP_DEPS=""; \
for HDR in $SRC_DEPS; do \
eval export SRC_DEEP_DEPS="\"$SRC_DEEP_DEPS \$${HDR//[-.]/_}_DEPS\""; \
done; \
export SRC_DEPS="`echo $SRC_DEPS $SRC_DEEP_DEPS | sed 's/ */\n/g' | sort -u`"; \
test "$SRC_DEPS" = "$SRC_DEPS_OLD" && break; \
done; \
echo $SRC $SRC_DEPS >>.depend; \
done; \
)
Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o parser.o parser.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o main.o main.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o redsocks.o redsocks.c
In file included from redsocks.c:41:0:
redsocks.c: In function ‘redsocks_relay_readcb’:
redsocks.c:277:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 10 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "RCB %s, in: %u", from == client->cli
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c: In function ‘process_shutdown_on_write_’:
redsocks.c:298:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 12 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c:298:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 13 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c:298:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 14 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c: In function ‘redsocks_dump_client’:
redsocks.c:860:42: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 13 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, loglevel, "client(%i): (%s)%s%s input %u output
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c:860:42: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 14 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, loglevel, "client(%i): (%s)%s%s input %u output
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c:860:42: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 19 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, loglevel, "client(%i): (%s)%s%s input %u output
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
redsocks.c:860:42: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 20 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, loglevel, "client(%i): (%s)%s%s input %u output
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o log.o log.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o direct.o direct.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o ipcache.o ipcache.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o autoproxy.o autoproxy.c
In file included from autoproxy.c:30:0:
autoproxy.c: In function ‘auto_recv_timeout_cb’:
autoproxy.c:225:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 10 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "RECV Timeout, state: %d, data_sent:
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c: In function ‘handle_write_to_relay’:
autoproxy.c:273:47: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 9 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "sent: %u, recv: %u, in:%u, out:%
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c:273:47: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 10 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "sent: %u, recv: %u, in:%u, out:%
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c:273:47: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 11 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "sent: %u, recv: %u, in:%u, out:%
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c:273:47: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 12 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "sent: %u, recv: %u, in:%u, out:%
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c: In function ‘direct_relay_clientreadcb’:
autoproxy.c:377:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 9 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "client in: %u", input_size);
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c: In function ‘direct_relay_relayreadcb’:
autoproxy.c:390:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 9 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "relay in: %u", input_size);
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c: In function ‘process_shutdown_on_write_2’:
autoproxy.c:424:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 12 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c:424:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 13 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
autoproxy.c:424:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 14 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
redsocks_log_error(client, LOG_DEBUG, "WCB %s, fs: %u, ts: %u, fin: %u, fou
^
redsocks.h:109:113: note: in definition of macro ‘redsocks_log_error’
_LINE__, __func__, 0, &(client)->clientaddr, &(client)->destaddr, prio, ## msg)
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o encrypt.o encrypt.c
encrypt.c: In function ‘enc_key_init’:
encrypt.c:919:17: warning: unused variable ‘cipher_info’ [-Wunused-variable]
cipher_kt_t cipher_info;
^
encrypt.c: At top level:
encrypt.c:146:12: warning: ‘crypto_stream_xor_ic’ defined but not used [-Wunused-function]
static int crypto_stream_xor_ic(uint8_t *c, const uint8_t *m, uint64_t mlen,
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o shadowsocks.o shadowsocks.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-connect.o http-connect.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks4.o socks4.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks5.o socks5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-relay.o http-relay.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o base.o base.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o base64.o base64.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o md5.o md5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o http-auth.o http-auth.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o utils.o utils.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o redudp.o redudp.c
redudp.c:158:13: warning: ‘bound_udp4_put’ defined but not used [-Wunused-function]
static void bound_udp4_put(const struct sockaddr_in *addr)
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o socks5-udp.o socks5-udp.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o shadowsocks-udp.o shadowsocks-udp.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o tcpdns.o tcpdns.c
tcpdns.c: In function ‘tcpdns_readcb’:
tcpdns.c:108:33: warning: format ‘%d’ expects argument of type ‘int’, but argument 9 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
tcpdns_log_error(LOG_DEBUG, "response size: %d", input_size);
^
tcpdns.c:37:124: note: in definition of macro ‘tcpdns_log_error’
__func__, 0, &req->client_addr, &req->instance->config.bindaddr, prio, ## msg)
^
tcpdns.c: At top level:
tcpdns.c:350:13: warning: ‘check_dns_delay’ defined but not used [-Wunused-function]
static void check_dns_delay()
^
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -c -o gen/version.o gen/version.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -o redsocks2 parser.o main.o redsocks.o log.o direct.o ipcache.o autoproxy.o encrypt.o shadowsocks.o http-connect.o socks4.o socks5.o http-relay.o base.o base64.o md5.o http-auth.o utils.o redudp.o socks5-udp.o shadowsocks-udp.o tcpdns.o gen/version.o -levent -lssl -lcrypto`

Am I missing something? Should I add any additional parameters for Ubuntu? As you may understand I am new at the scene of source compilation and I am rather interested in getting this right. I would appreciate anyone's input so I can go ahead and have a successful compile.

Thanks

**Comment by semigodking** [comment]
You can ignore those warnings. I think you successfully compiled it. The binary is generated
