### ISSUE TITLE
有没有openwrt平台编译好的二进制文件呀？

### ISSUE THREAD

**Issue by yanggis** [semigodking/redsocks#66]
现在openwrt用，请问有没有openwrt平台编译好的二进制文件呀？不想搭建openwrt交叉编译平台了，有点太麻烦了。

**Comment by semigodking** [comment]
具体什么硬件平台

2017年3月11日 12:44，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
谢谢回复，AR71xx的

**Comment by semigodking** [comment]
改天帮你弄一下,  你在wrt是哪一个版本？15.01?周末不方便弄.  如果你急的话，嗯山应该有。

2017年3月11日 13:02，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
好，非常感谢，Chaos Calmer 15.05.1

**Comment by yanggis** [comment]
恩山那个太老了，等您有空再弄吧，这个不着急。非常感谢。

**Comment by AlexZhuo** [comment]
这种小事不用麻烦大神了https://github.com/AlexZhuo/BreakwallOpenWrt/raw/master/ar71xx/ImageBuilder/packages/base/redsocks2_0.66-1_ar71xx.ipk

**Comment by yanggis** [comment]
@AlexZhuo 感谢！！
