### ISSUE TITLE
openwrt上的redsocks2突然无法使用

### ISSUE THREAD

**Issue by lijunhao731** [semigodking/redsocks#67]
之前好好的，也没改过参数，突然被墙的网站全打不开了，用的shadowsocks模式，确认ss服务器没问题，直接代理是能够用的，能否帮忙看下日志？
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.164:63380->17.167.192.244:443]: relay in: 137
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.164:63380->17.167.192.244:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:41 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:44 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: accepted
Mon Mar 27 22:42:44 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:45 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:45 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:45 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: Audit client list for instance (shadowsocks @ 0.0.0.0:11111):
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55706->35.185.132.241:10086]: client(74): (R/-) SHUT_WR input 0 output 0, relay(75): (-/W) SHUT_RD input 0 output 0, age: 243 sec, idle: 152 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55706->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55694->35.185.132.241:10086]: client(68): (R/-) SHUT_WR input 0 output 0, relay(69): (-/W) SHUT_RD input 0 output 0, age: 246 sec, idle: 178 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55694->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55693->35.185.132.241:10086]: client(64): (R/-) SHUT_WR input 0 output 0, relay(67): (-/W) SHUT_RD input 0 output 0, age: 246 sec, idle: 181 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55693->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55690->35.185.132.241:10086]: client(60): (R/-) SHUT_WR input 0 output 0, relay(61): (-/W) SHUT_RD input 0 output 0, age: 246 sec, idle: 178 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55690->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55692->35.185.132.241:10086]: client(58): (R/-) SHUT_WR input 0 output 0, relay(59): (-/W) SHUT_RD input 0 output 0, age: 246 sec, idle: 178 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55692->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55691->35.185.132.241:10086]: client(36): (R/-) SHUT_WR input 0 output 0, relay(48): (-/W) SHUT_RD input 0 output 0, age: 246 sec, idle: 178 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55691->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55680->35.185.132.241:10086]: client(49): (R/-) SHUT_WR input 0 output 0, relay(52): (-/W) SHUT_RD input 0 output 0, age: 248 sec, idle: 178 sec.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55680->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: End of auditing client list.
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:46 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: relay, errno(0), State: 10000, what: 0|WRITING|0|0|TIMEOUT|0|0x0: Success
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: IP Blocked
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: ADD IP to cache: 93.46.8.89
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: dropping relay only 
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: data relaying started
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: WCB relay, fs: 0, ts: 0, fin: 517, fout: 0, tin: 0
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 524, tin: 0
Mon Mar 27 22:42:47 2017 daemon.debug redsocks[7121]: [172.22.22.162:55828->93.46.8.89:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:37788->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:37788->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:1711->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:1711->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:53623->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:53623->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: accepted
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: accepted
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: data relaying started
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB relay, fs: 0, ts: 0, fin: 207, fout: 0, tin: 0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: sent: 0, recv: 0, in:207, out:0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 207, tin: 207
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB relay, fs: 0, ts: 0, fin: 207, fout: 0, tin: 0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: sent: 207, recv: 0, in:207, out:0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: data relaying started
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 219, fout: 0, tin: 0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: sent: 0, recv: 0, in:219, out:0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 219, tin: 219
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 219, fout: 0, tin: 0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: sent: 219, recv: 0, in:219, out:0
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:59556->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:53 2017 daemon.debug redsocks[7121]: [127.0.0.1:59556->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 4096
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: IP Confirmed
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 1664
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: RECV Timeout, state: 10001, data_sent: 207
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: IP Confirmed
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 964
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: relay in: 3310
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: client in: 318
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: client in: 318
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 51
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: client in: 2091
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: client in: 616
Mon Mar 27 22:42:54 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 1225
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: client in: 2150
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: client in: 616
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [127.0.0.1:15723->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [127.0.0.1:15723->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [127.0.0.1:31901->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [127.0.0.1:31901->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: relay in: 51
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: client in: 1231
Mon Mar 27 22:42:55 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: relay in: 534
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.167:58152->17.110.232.46:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:37788->8.8.8.8:53]: Client timeout. First: 1490625773, last_client: 1490625773, last_relay: 0.
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:37788->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:1711->8.8.8.8:53]: Client timeout. First: 1490625773, last_client: 1490625773, last_relay: 0.
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:1711->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: relay in: 1225
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.167:58153->17.154.66.73:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:53623->8.8.8.8:53]: Client timeout. First: 1490625773, last_client: 1490625773, last_relay: 0.
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:53623->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: relay in: 63
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: relay, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: WCB client, fs: 2, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: client, errno(0), State: 10002, what: READING|0|EOF|0|0|0|0x0: Success
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: WCB relay, fs: 6, ts: 2, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: both client and server disconnected
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [172.22.22.162:55668->35.185.132.241:10086]: dropping client @ state: 0
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:59556->8.8.8.8:53]: Client timeout. First: 1490625773, last_client: 1490625773, last_relay: 0.
Mon Mar 27 22:42:56 2017 daemon.debug redsocks[7121]: [127.0.0.1:59556->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB client, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [172.22.22.162:55519->74.125.204.138:443]: WCB relay, fs: 0, ts: 0, fin: 0, fout: 0, tin: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [127.0.0.1:15723->8.8.8.8:53]: Client timeout. First: 1490625775, last_client: 1490625775, last_relay: 0.
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [127.0.0.1:15723->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [127.0.0.1:31901->8.8.8.8:53]: Client timeout. First: 1490625775, last_client: 1490625775, last_relay: 0.
Mon Mar 27 22:42:58 2017 daemon.debug redsocks[7121]: [127.0.0.1:31901->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:43:02 2017 daemon.debug redsocks[7121]: [127.0.0.1:52008->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:43:02 2017 daemon.debug redsocks[7121]: [127.0.0.1:52008->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:43:02 2017 daemon.debug redsocks[7121]: [127.0.0.1:31823->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:43:02 2017 daemon.debug redsocks[7121]: [127.0.0.1:31823->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:43:03 2017 daemon.debug redsocks[7121]: [127.0.0.1:16418->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:43:03 2017 daemon.debug redsocks[7121]: [127.0.0.1:16418->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:43:03 2017 daemon.debug redsocks[7121]: [127.0.0.1:48796->8.8.8.8:53]: got 1st packet from client
Mon Mar 27 22:43:03 2017 daemon.debug redsocks[7121]: [127.0.0.1:48796->8.8.8.8:53]: Starting UDP relay
Mon Mar 27 22:43:05 2017 daemon.debug redsocks[7121]: [127.0.0.1:52008->8.8.8.8:53]: Client timeout. First: 1490625782, last_client: 1490625782, last_relay: 0.
Mon Mar 27 22:43:05 2017 daemon.debug redsocks[7121]: [127.0.0.1:52008->8.8.8.8:53]: Dropping client @ state: 0
Mon Mar 27 22:43:05 2017 daemon.debug redsocks[7121]: [127.0.0.1:31823->8.8.8.8:53]: Client timeout. First: 1490625782, last_client: 1490625782, last_relay: 0.
Mon Mar 27 22:43:05 2017 daemon.debug redsocks[7121]: [127.0.0.1:31823->8.8.8.8:53]: Dropping client @ state: 0

**Comment by semigodking** [comment]
从55828这个连接来看,你的DNS是有污染的,这个目标地址好像是一个被污染了的IP。
5519这个连接比较奇怪, 双方一直不发送数据.
根据剩下的信息判断不出其他问题。

2017年3月27日 22:43，"lijunhao731" <notifications@github.com>写道：
