### ISSUE TITLE
Format for domain user to be used in config file of https proxy

### ISSUE THREAD

**Issue by hqvv** [semigodking/redsocks#71]
Hello Gentlemen,

Thanks to you great work on this project. 
I was using your redsocks2 as a transparent proxy in company's internal network, because we use a https server to go through to internet.
The proxy got update recently, it requires a active directory authentication now.
It wont work if I still leave username and password as blank.

I had put my username and password in config file, but it didn't work. 
I guess I shall provide the domain to server with those information together.
I noticed that there is no field like Domain defined in struct redsocks_config_t.
so I have tried domain\username format, but it didn't work either.

Please kindly advise how can I update the conf file to connect to the new server.
or, where can I find related information about this.

Thanks 

HQ

**Comment by semigodking** [comment]
Updating confif file is not adequate. Support of Http Authentication scheme
NTLM needs to be implemented. See
https://www.innovation.ch/personal/ronald/ntlm.html

Hanqing Wong <notifications@github.com>于2017年6月1日周四 12:39写道：

**Comment by hqvv** [comment]
Many thanks for your advices.
I can not find the NTLM package for openwrt, It seems not easy to get it work on my router.

Another question is about the autoproxy feature,
Could you please advise what the option is used for ?
in which condition the option should be turn off?  I noticed one of my server wont work if the switch is on.

Thanks

**Comment by semigodking** [comment]
Usually, I have two redsocks sections. One of them has autoproxy turned on
while the other one has autoproxy turned off. For majority cases, I want
traffic go through auto proxy. But, sometimes you want certain traffic go
through the underling proxy directly. For examples, all traffic to google's
IP ranges. Sometimes, you may also want some traffic go directly via
underling proxy. In this case, you do not need to make any change to
redsocks config. You just need to redirect the traffic to the port of
redsocks having autoproxy turned off.

**Comment by semigodking** [comment]
https://github.com/curl/curl/ contains implementation for NTLM
authentication as well as usage sample. Hopefully some people have
interest, time and skills to bring this feature to redsocks2.

**Comment by hqvv** [comment]
Many thanks for your help.
The issue was solved with win10 hotspot.
