### ISSUE TITLE
非53端口的tcpdns支持

### ISSUE THREAD

**Issue by zhaibin18** [semigodking/redsocks#72]
目前使用的tcpdns使用的是5353端口，是否能支持非53端口的tcpdns，多谢。

**Comment by semigodking** [comment]
容易，等有空加上去

zhaibin18 <notifications@github.com>于2017年7月16日周日 10:28写道：

**Comment by semigodking** [comment]
Done. See commit 07b4faeaf941985d19c20bb149240e02de7399c4
