### ISSUE TITLE
ENABLE_HTTPS_PROXY on Ubuntu 17.04

### ISSUE THREAD

**Issue by spvkgn** [semigodking/redsocks#73]
For use `ENABLE_HTTPS_PROXY=true` on Ubuntu 17.04 I have edit `https-connect.c` as follows, otherwise build failed.
```
--- a/https-connect.c
+++ b/https-connect.c
@@ -35,9 +35,6 @@
 #include "redsocks.h"
 #include "http-auth.h"
 
-#ifndef EVENT__HAVE_OPENSSL
-#error The libevent2 you are compiling with does not have OpenSSL enabled!
-#endif
 
 typedef enum httpsc_state_t {
     httpc_new,
```

**Comment by semigodking** [comment]
Maybe I need to verify it on Ubuntu 17.04 when I have time. I guess it is caused by different Libevent library installed.
