### ISSUE TITLE
Build failure due to type incomplete with openssl v1.1.0

### ISSUE THREAD

**Issue by bailove** [semigodking/redsocks#75]
What version of redsocks are you using?

v0.66

What operating system are you using?

Debian 4.9.30-1kali1

What did you do?

Compile package

What did you expect to see?

Compile success

What did you see instead?

cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o encrypt.o encrypt.c
In file included from encrypt.c:50:0:
encrypt.h:92:18: error: field ‘evp’ has incomplete type
     cipher_evp_t evp;
                  ^~~
encrypt.c: In function ‘enc_key_init’:
encrypt.c:919:17: error: storage size of ‘cipher_info’ isn’t known
     cipher_kt_t cipher_info;
                 ^~~~~~~~~~~
encrypt.c:919:17: warning: unused variable ‘cipher_info’ [-Wunused-variable]
At top level:
encrypt.c:146:12: warning: ‘crypto_stream_xor_ic’ defined but not used [-Wunused-function]
 static int crypto_stream_xor_ic(uint8_t *c, const uint8_t *m, uint64_t mlen,
            ^~~~~~~~~~~~~~~~~~~~
encrypt.c:139:18: warning: ‘supported_ciphers_key_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_key_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
encrypt.c:134:18: warning: ‘supported_ciphers_iv_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_iv_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'encrypt.o' failed
make: *** [encrypt.o] Error 1

**Comment by semigodking** [comment]
Unfortunately, openssl 1.1 is not supported yet.

**Comment by bailove** [comment]
can't pass through on change openssl openssl-1.0.2l .  which version openssl suit for redsocks? 

Compile with OpenSSL by default. To compile with PolarSSL, run 'make USE_CRYPTO_POLARSSL=true' instead.
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -o redsocks2 parser.o main.o redsocks.o log.o direct.o ipcache.o autoproxy.o encrypt.o shadowsocks.o http-connect.o socks4.o socks5.o http-relay.o base.o base64.o md5.o http-auth.o utils.o redudp.o socks5-udp.o shadowsocks-udp.o tcpdns.o gen/version.o  -levent -lssl -lcrypto
encrypt.o: In function `ss_encrypt':
encrypt.c:(.text+0xc06): undefined reference to `EVP_CIPHER_CTX_cleanup'
encrypt.o: In function `ss_decrypt':
encrypt.c:(.text+0xd76): undefined reference to `EVP_CIPHER_CTX_cleanup'
encrypt.o: In function `enc_ctx_init':
encrypt.c:(.text+0xe50): undefined reference to `EVP_CIPHER_CTX_init'
encrypt.c:(.text+0xeb4): undefined reference to `EVP_CIPHER_CTX_cleanup'
encrypt.o: In function `enc_init':
encrypt.c:(.text+0x2b76): undefined reference to `OPENSSL_add_all_algorithms_noconf'
encrypt.o: In function `enc_ctx_free':
encrypt.c:(.text+0xee5): undefined reference to `EVP_CIPHER_CTX_cleanup'
collect2: error: ld returned 1 exit status
Makefile:108: recipe for target 'redsocks2' failed
make: *** [redsocks2] Error 1

**Comment by semigodking** [comment]
Openssl 1.0should work. I am afraid you are not linking against correct
libcrypto or libssl.

bailove <notifications@github.com>于2017年8月5日周六 22:31写道：

**Comment by bailove** [comment]
thank you!
