### ISSUE TITLE
HTTP request sent; waiting for response.

### ISSUE THREAD

**Issue by FoleyX90** [semigodking/redsocks#79]
I have a shadowsocks server set up and I'm trying to connect redsocks2 to it. I've added all of the recommended IPtables info but if I try to do "lynx ipchicken.com" i just get HTTP request sent; waiting for response.

It's not a server issue because ss-redir works (but I'm having issues with DNSMASQ not sending connected devices the DNS) so I wanted to try redsocks.

**Comment by semigodking** [comment]
You need to at least provide the following information for me to understand your problems.
1. redsocks2.conf
2. iptables configs
3. redsocks2 debug logs for your requests.
4. pcap for your requests if possible.

**Comment by FoleyX90** [comment]
Thanks for the quick response! I'll upload my config momentarily.

**Comment by FoleyX90** [comment]
shadowsocks config.json:

{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "timeout":60,
    "method": "aes-256-cfb",
    "password": "********", // hidden for this post
    "verbose": 5
}

redsocks2.conf:

base {
        log_debug = off;

        log_info = on;

        log = stderr;
        daemon = off;

        redirector = iptables;

}

redsocks {
        local_ip = 127.0.0.1;
        local_port = 12345;


        ip = 12.35.70.131;
        port = 8388;

        type = shadowsocks;

        autoproxy = 1;
        timeout = 10;

        login = aes-256-cfb;// field 'login' is reused as encryption
                                           // method of shadowsocks
        password = "********"; // hidden for this post
}

root@stratapointe:/opt/redsocks2# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N REDSOCKS
-A OUTPUT -p tcp -j REDSOCKS
-A REDSOCKS -d 0.0.0.0/8 -j RETURN
-A REDSOCKS -d 10.0.0.0/8 -j RETURN
-A REDSOCKS -d 127.0.0.0/8 -j RETURN
-A REDSOCKS -d 169.254.0.0/16 -j RETURN
-A REDSOCKS -d 172.16.0.0/12 -j RETURN
-A REDSOCKS -d 192.168.0.0/16 -j RETURN
-A REDSOCKS -d 224.0.0.0/4 -j RETURN
-A REDSOCKS -d 240.0.0.0/4 -j RETURN
-A REDSOCKS -p tcp -j REDIRECT --to-ports 12345

**Comment by semigodking** [comment]
Not sure which subnet your connections originate from, but usually, we do not config redsocks local_ip as 127.0.0.1. Because REDIRECT requires that the connection must from the same subnet as the local_ip. So, if you want to proxy all connections from subnet 192.168.0.1/24, you need to set local_ip as 192.168.0.1 (suppose 192.168.0.1 is the gateway). 
And, we usually do redirect in prerouting chain instead of OUTPUT chain.
