### ISSUE TITLE
当ss服务器不稳定时redsocks不能自动恢复

### ISSUE THREAD

**Issue by ghostry** [semigodking/redsocks#8]
我发现如果我的ss服务器出现有一段时间连接不上后，redsocks2需要restart才能继续使用，否则走代理的部分就会打不开。

**Comment by semigodking** [comment]
哦，我以后留意测试一下这种情况。

Semigod King
2015年4月29日 上午11:47于 "ghostry" <notifications@github.com>写道：

**Comment by rampageX** [comment]
的确有这个问题，用 redsocks 直接连接远程 ss 服务器就会发生有时候连不上需要重启 redsocks，但是如果是连接 ss-local 建立的监听就不会。

**Comment by semigodking** [comment]
连不上是指所有网站吗？请尝试提供 debug log

Semigod King
2015年5月20日 上午1:08于 "rampageX" <notifications@github.com>写道：

**Comment by hero18688** [comment]
也遇到rampageX的问题

**Comment by semigodking** [comment]
请尝试提供足够的出问题时的现场信息，如：
redsocks的配置
iptables的配置
ifconfig
Debug log
Kill -SIGUSR1 的输出等

Semigod King
2015年7月12日 上午9:07于 "hero18688" <notifications@github.com>写道：

**Comment by hero18688** [comment]
是用这个固件的最新版完全按照帖子说的配置的http://www.right.com.cn/forum/thread-146171-1-1.html

2015-07-12 17:21 GMT+08:00 semigodking <notifications@github.com>:

**Comment by semigodking** [comment]
Ss服务器不稳定时是否其ip发生变化？

Semigod King
2015年7月12日 下午5:24于 "hero18688" <notifications@github.com>写道：

**Comment by ghostry** [comment]
没有变化,服务器是静态IP的.

**Comment by semigodking** [comment]
那我可以测试下

Semigod King
2015年7月21日 下午7:08于 "ghostry" <notifications@github.com>写道：

**Comment by semigodking** [comment]
问题无法重现。 在正常使用的过程中，关掉ss服务，刷新各种被墙网页，redsocks报大量 connection refused. 恢复ss,
网页又可正常打开。过程中 redsocks 没动过。

Semigod King
2015年7月21日 下午7:22于 "Semigod King" <semigodking@gmail.com>写道：
