### ISSUE TITLE
(FreeBSD 11.1 ) main.c:221 main(...) evsignal_add: Bad file descriptor

### ISSUE THREAD

**Issue by v20z** [semigodking/redsocks#80]
Hello dear Semigodking

Can you please take a look for issue on FreeBSD 11.1 where redsocks2 from git (and starting from 0.66 release) halts with message:
1513751084.231277 main.c:221 main(...) evsignal_add: Bad file descriptor

Older version 0.65 continues to run but not accept  connection and continuosly log messages:
1513751541.075100 redsocks.c:1080 redsocks_init(...) evsignal_add SIGUSR2: Bad file descriptor
1513751546.094984 base.c:370 myproc(...) Failed to send SIGUSR2 to pid 12257
1513751547.158666 redsocks.c:1080 redsocks_init(...) evsignal_add SIGUSR2: Bad file descriptor
1513751552.240035 base.c:370 myproc(...) Failed to send SIGUSR2 to pid 12258

Thank You.

**Comment by semigodking** [comment]
I need to find a proper time to install BSD 11 and do some tests. It looks
like parameters for setting up signals are incorrect.

**Comment by semigodking** [comment]
I tried on FreeBSD 11.1. It works fine. 

```
user1@freebsd11:~/redsocks2 % uname -a
FreeBSD freebsd11 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by v20z** [comment]
Thanks for your reply,  Semigodking.

I've found that this issue occurs when directive "daemon = on;" present in config file.
When running without it in background (&) executable starts and serves requests normally. 

If you still have FreeBSD installation alive can you please investigate this issue for future maintenance and development?

Thank You.

**Comment by semigodking** [comment]
Hi @v20z,
I've the code updated. Would you please have a try to see if it works for you?

**Comment by v20z** [comment]
Oh yes! Now it is all right! It works as supposed!

I've downloaded actual git tarball, compiled source, started executable with "daemon = on;" option in config file and successfully connected through redsocks2 to target.

Thank you for your concern and efforts! See you when the next problem appears ;-) 

Your annoying user ;-)

**Comment by semigodking** [comment]
Cool. You are welcome!
