### ISSUE TITLE
any option for redirecting packets to another app untouched?

### ISSUE THREAD

**Issue by rezad1393** [semigodking/redsocks#86]
what I mean is that the packets that get to redsocks2 could be directed to another app and that app see the traffic as if iptables directed the packets to that app.

to be more clear what I mean is ,for example ,can I daisy chain another resocks(or app like redsocks) downstream of redsocks? 

direct,http-relay and so on don't work like this ,correct? all of the redsocks options for proxies change the packets according to that option?

**Comment by semigodking** [comment]
No. Source address is always changed.

**Comment by rezad1393** [comment]
so there is no way to do this ? maybe a workaround? maybe an option to be added for later?

**Comment by semigodking** [comment]
The problem is to not change source address. I did not see a workaround.
