### ISSUE TITLE
使用当中的一个小问题

### ISSUE THREAD

**Issue by yanggis** [semigodking/redsocks#87]
您好，想问您一个redsocks2作为直接中转的一个问题，
比如ISP不允许多台电脑共享上网，但经过REDSOCKS2中转后就可以共享了。做如下配置：
redsocks {
 local_ip = 192.168.1.1;
 local_port = 1088;
 type = direct;
 timeout = 20;
}
这个时候redsocks2是以tcp模式运行的，还是http模式运行的呢？
谢谢您解惑。

**Comment by semigodking** [comment]
Tcp

**Comment by yanggis** [comment]
好的， 谢谢回复。
