### ISSUE TITLE
请帮我看看是不是设置有问题，不能转发所有udp，多谢。

### ISSUE THREAD

**Issue by caonimac** [semigodking/redsocks#89]
![default](https://user-images.githubusercontent.com/35394132/37875582-fd15290e-3073-11e8-9d8e-eed90c4f499a.JPG)

我在debian x64软路由里做redsocks2透明代理，iptables转发到redsocks2的12345，redsocks2再转发到v2ray的inbound端口。
正常科学上网，可是打开youteube，通过 netstat -nap | grep udp 在路由里查看，就会看到有很多udp连接直连谷歌ip。
用NatTypeTester测试udp转发，显示Symmetric。

如上图所示。

我用redsocks(0.5-1)，v2ray自带的Dokodemo-door做透明代理，都有同样问题。Dokodemo-door加载视频很慢，加载成功会卡顿，redsocks要好一点，redsocks2最流畅。

有人说是quic协议的问题，不知道怎么回事。

请帮我看看是不是我的规则错了。
chinadns_chnroute.txt 为最新，已确认里面不会有图中的谷歌ip。

iptables规则：

ipset create chnroute hash:net
cat /etc/chinadns_chnroute.txt | xargs -I ip ipset add chnroute ip
ip route add local 0.0.0.0/0 dev lo table 100
ip rule add fwmark 1 lookup 100
#
iptables -t nat -N V2RAY
iptables -t mangle -N V2RAY
#
iptables -t nat -A V2RAY -d 0/8 -j RETURN
iptables -t nat -A V2RAY -d 127/8 -j RETURN
iptables -t nat -A V2RAY -d 10/8 -j RETURN
iptables -t nat -A V2RAY -d 169.254/16 -j RETURN
iptables -t nat -A V2RAY -d 172.16/12 -j RETURN
iptables -t nat -A V2RAY -d 192.168/16 -j RETURN
iptables -t nat -A V2RAY -d 224/4 -j RETURN
iptables -t nat -A V2RAY -d 240/4 -j RETURN
#
iptables -t nat -A V2RAY -d 代理服务器 -j RETURN
#
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
#
iptables -t mangle -A V2RAY -d 0/8 -j RETURN
iptables -t mangle -A V2RAY -d 127/8 -j RETURN
iptables -t mangle -A V2RAY -d 10/8 -j RETURN
iptables -t mangle -A V2RAY -d 169.254/16 -j RETURN
iptables -t mangle -A V2RAY -d 172.16/12 -j RETURN
iptables -t mangle -A V2RAY -d 192.168/16 -j RETURN
iptables -t mangle -A V2RAY -d 224/4 -j RETURN
iptables -t mangle -A V2RAY -d 240/4 -j RETURN
#
iptables -t mangle -A V2RAY -d 代理服务器 -j RETURN
#
iptables -t mangle -A V2RAY -p udp -j TPROXY --tproxy-mark 0x01/0x01 --on-port 12345
#
iptables -t nat -A PREROUTING -p tcp -m set --match-set chnroute dst -j RETURN
iptables -t nat -A OUTPUT -p tcp -m set --match-set chnroute dst -j RETURN
iptables -t mangle -A PREROUTING -p udp -m set --match-set chnroute dst -j RETURN
#
iptables -t nat -A OUTPUT -p tcp -j V2RAY
iptables -t mangle -A PREROUTING -s 192.168/16 -j V2RAY
iptables -t nat -A PREROUTING -p tcp -s 192.168/16 -j V2RAY
#
iptables -t nat -A POSTROUTING -j MASQUERADE

**Comment by caonimac** [comment]
redsocks监听0.0.0.0或者192.168.2.1都是一样的。刚刚表扬完redsocks2,现在换个youteube视频，一直转圈，根本看不了了。

**Comment by semigodking** [comment]
那些ip都是local 这端的，你用了tproxy  ，这些ip是本地用来假装包是从这些ip发回来的。没问题啊

**Comment by caonimac** [comment]
哦，好的，谢谢，只好关掉udp转发了。

**Comment by semigodking** [comment]
使用这个也没有什么问题。 udp包从外面加密收回，然后再假装从那些地址发回来，发回给本地应用，不泄露什么

**Comment by caonimac** [comment]
谢谢，知道了。可是不能youteube，UDP还是关了吧。
