### ISSUE TITLE
编译中有些警告，请问影响使用吗？谢谢

### ISSUE THREAD

**Issue by caonimac** [semigodking/redsocks#91]
提示如下:

Compile with PolarSSL.
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o parser.o parser.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o main.o main.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o redsocks.o redsocks.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o log.o log.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o direct.o direct.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o ipcache.o ipcache.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o autoproxy.o autoproxy.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o encrypt.o encrypt.c
encrypt.c: In function ‘enc_key_init’:
encrypt.c:919:17: warning: unused variable ‘cipher_info’ [-Wunused-variable]
     cipher_kt_t cipher_info;
                 ^~~~~~~~~~~
At top level:
encrypt.c:146:12: warning: ‘crypto_stream_xor_ic’ defined but not used [-Wunused-function]
 static int crypto_stream_xor_ic(uint8_t *c, const uint8_t *m, uint64_t mlen,
            ^~~~~~~~~~~~~~~~~~~~
encrypt.c:139:18: warning: ‘supported_ciphers_key_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_key_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
encrypt.c:134:18: warning: ‘supported_ciphers_iv_size’ defined but not used [-Wunused-const-variable=]
 static const int supported_ciphers_iv_size[] =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o shadowsocks.o shadowsocks.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o http-connect.o http-connect.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o socks4.o socks4.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o socks5.o socks5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o http-relay.o http-relay.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o base.o base.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o base64.o base64.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o md5.o md5.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o http-auth.o http-auth.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o utils.o utils.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o redudp.o redudp.c
redudp.c:158:13: warning: ‘bound_udp4_put’ defined but not used [-Wunused-function]
 static void bound_udp4_put(const struct sockaddr_in *addr)
             ^~~~~~~~~~~~~~
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o socks5-udp.o socks5-udp.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o shadowsocks-udp.o shadowsocks-udp.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o tcpdns.o tcpdns.c
tcpdns.c:350:13: warning: ‘check_dns_delay’ defined but not used [-Wunused-function]
 static void check_dns_delay()
             ^~~~~~~~~~~~~~~
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL   -c -o gen/version.o gen/version.c
cc -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_POLARSSL -o redsocks2 parser.o main.o redsocks.o log.o direct.o ipcache.o autoproxy.o encrypt.o shadowsocks.o http-connect.o socks4.o socks5.o http-relay.o base.o base64.o md5.o http-auth.o utils.o redudp.o socks5-udp.o shadowsocks-udp.o tcpdns.o gen/version.o  -levent -lpolarssl

**Comment by semigodking** [comment]
不影响

**Comment by caonimac** [comment]
嗯嗯感谢
