### ISSUE TITLE
能实现本机UDP透明代理吗？

### ISSUE THREAD

**Issue by shellus** [semigodking/redsocks#93]
众所周知，UDP透明代理需要依赖TPROXY内核模块。但是tproxy匹配只适用于mangle 表。
如果是要本机透明代理，需要使用nat表的OUTPUT链。但是tproxy匹配不能用于这个链。

那么，还有什么办法可以实现本机的UDP透明代理吗？

**Comment by semigodking** [comment]
我能想到的方法就是起个虚拟机，在上面安VPN ，然后本机拨VPN, 在VPN 上转发。VPN 要一个网卡和本机网卡桥接，另一个网卡是host Only

**Comment by shellus** [comment]
这个办法不错，我也尝试过了，但是发现对网卡有要求，我使用wifi不行，使用有线网卡就可用。

semigodking <notifications@github.com>于2018年4月10日 周二20:26写道：

> 我能想到的方法就是起个虚拟机，在上面安VPN ，然后本机拨VPN, 在VPN 上转发。VPN 要一个网卡和本机网卡桥接，另一个网卡是host
> Only
>

**Comment by semigodking** [comment]
那在linux 用docker

**Comment by shellus** [comment]
使用docker代替虚拟机是个不错的想法。

semigodking <notifications@github.com>于2018年4月10日 周二23:32写道：

> 那在linux 用docker
>
>

**Comment by shellus** [comment]
看起来不会有其他办法了。
