### ISSUE TITLE
是否可以设置类似X-Forwarded-For的header

### ISSUE THREAD

**Issue by Totti0135** [semigodking/redsocks#95]
## 目的
在配置文件设置的目标代理中可以获取到用户的真实IP地址
## 现状
只能获取到redsocks2的ip地址

**Comment by semigodking** [comment]
不支持此功能。原版redsocks是有此功能，但我没有验证过，也没有试过将此功能移过来。

**Comment by Totti0135** [comment]
由于对这块不是很熟悉，不知道能否指点一下，如果我自己想添加这个功能的话，可以再哪个函数上进行修改？

**Comment by Totti0135** [comment]
由于对这块不是很熟悉，不知道能否指点一下，如果我自己想添加这个功能的话，可以再哪个函数上进行修改？

**Comment by Totti0135** [comment]
非常感谢！最后问下有没有相关群组可以进行讨论的？

**Comment by semigodking** [comment]
没有  用这个东西的人还是比较少的
