### ISSUE TITLE
无法使用tproxy

### ISSUE THREAD

**Issue by dynos01** [semigodking/redsocks#96]
运行redsocks2后，报错如下：

1527230019.217434 err utils.c:472 make_socket_transparent(...) setsockopt(..., S�OL_IP, IP_TRANSPARENT): Operation not permitted

1527230019.217484 warning redsocks.c:986 redsocks_init_instance(...) Continue wi�thout TPROXY support

1527230019.217643 err utils.c:472 make_socket_transparent(...) setsockopt(..., S�OL_IP, IP_TRANSPARENT): Operation not permitted

配置文件udp部分如下：

type = socks5;
local_ip = 本地;
local_port = 10053;
ip = 远程;
port = 1080;
login = 用户名;
password = 密码;
udp_timeout = 30;

环境是全新的Debian 9。是不是内核的问题呢？

谢谢

**Comment by kuleyang** [comment]
需要root权限
