### ISSUE TITLE
android编译的问题

### ISSUE THREAD

**Issue by yanggis** [semigodking/redsocks#98]
您好作者，又来麻烦您了。
现在最新版本用NDK编译的时候会报错，这个错误：
Module redsocks depends on undefined modules: ev
找不到ev模块，请问怎么解决啊？谢谢您。

**Comment by semigodking** [comment]
这可是个麻烦事儿, 等我有空把环境弄好试试先，要不无从查起

**Comment by yanggis** [comment]
好的，谢谢您。

**Comment by yanggis** [comment]
如果我忽略前面那个错误，往下编译还会碰到这样的错误：

In file included from E:/Android_SDK/redsocks5/android/jni/libevent2/evutil_rand.c:125:0:
E:/Android_SDK/redsocks5/android/jni/libevent2/./arc4random.c:497:1: error: static declaration of 'arc4random_buf' follows non-static declaration
 arc4random_buf(void *_buf, size_t n)
 ^
In file included from E:/Android_SDK/redsocks5/android/jni/libevent2/util-internal.h:35:0,
                 from E:/Android_SDK/redsocks5/android/jni/libevent2/evutil_rand.c:39:
e:\android_ndk\android-ndk-r17\sysroot\usr\include\stdlib.h:130:6: note: previous declaration of 'arc4random_buf' was here
 void arc4random_buf(void* __buf, size_t __n);
      ^
make: *** [E:/Android_SDK/redsocks5/android/obj/local/arm64-v8a/objs/event2/libevent2/evutil_rand.o] Error 1

**Comment by yanggis** [comment]
@semigodking 另外想问一下，redsocks有没有配置等待超时的参数，现在测试发现，如果是利用redsocks连接比较偏远的网络，需要等待时间长一些才能返回结果，但是貌似redsocks等待不了那么久就以超时结束会话了。如果可以修改redsocks的等待参数，让等待时间长一些，就可以解决这个问题。请指导。谢谢。

**Comment by semigodking** [comment]
有timeout 参数啊

**Comment by yanggis** [comment]
好的，非常感谢回复。

**Comment by semigodking** [comment]
解决了？欢迎把方法贴出来。

**Comment by yanggis** [comment]
arc4random_buf这个函数和linux系统文件里定义重复了，注释掉就可以编译通过了
